[13.0][MIG] sale_order_line_date
OCA/sale-workflow pull request #1045
Opened 2020-01-13 14:57 UTC by NuriaMForgeFlow

Migration of the module sale_order_line_date to v13.

2020-01-15 08:18 UTC, AdriaGForgeFlow requested changes
Code review :+1: 

Just a comment below:

2020-01-15 08:18 UTC, AdriaGForgeFlow commented on sale_order_line_date/migrations/12.0.1.0.0/pre-migration.py
>  from openupgradelib import openupgrade
This is no longer needed, you can remove it.

2020-01-16 10:06 UTC, AdriaGForgeFlow approved these changes

2020-01-17 15:35 UTC, rousseldenis commented
@NuriaMForgeFlow Could you check isort configuration as travis failed?

2020-01-20 09:03 UTC, AaronHForgeFlow approved these changes
:+1: Tested on runbot. Works as expected.

2020-01-20 09:37 UTC, rousseldenis approved these changes
Code review

2020-02-06 10:31 UTC, MiquelRForgeFlow approved these changes

2020-02-06 10:31 UTC, MiquelRForgeFlow commented on sale_order_line_date/models/sale_order_line.py
> +    commitment_date = fields.Datetime()
```suggestion
    commitment_date = fields.Datetime('Delivery Date')
```
Like in sale orders.

2020-02-11 12:34 UTC, LoisRForgeFlow commented
@rousseldenis ready to merge I guess ;)

2020-02-11 12:34 UTC, rousseldenis commented
/ocabot merge

2020-02-11 12:49 UTC, merged