[MIG] Migrated sale_order_line_price_history to v13.
OCA/sale-workflow pull request #1082
Opened 2020-02-29 13:07 UTC by sudhir-erpharbor

2020-03-02 08:11 UTC, pedrobaeza approved these changes
You can try to convert the onchange in the transient to new computed readonly=False field.

2020-03-02 08:12 UTC, pedrobaeza commented
@ernestotejeda please review this TT22594

2020-03-24 15:40 UTC, ernestotejeda reviewed
@sudhir-erpharbor  would you see why the runbot is red? please

2020-03-28 06:23 UTC, sudhir-erpharbor commented
> @sudhir-erpharbor would you see why the runbot is red? please

The runbot has issue with the python version. I found following details in the runbot logs.

>File "/home/odoo/OCB-13.0/odoo/__init__.py", line 19, in <module>
assert sys.version_info > (3, 6), "Outdated python version detected, Odoo requires Python >= 3.6 to run."
AssertionError: Outdated python version detected, Odoo requires Python >= 3.6 to run.

2020-04-08 21:10 UTC, ernestotejeda requested changes
I can't see pre-commit metafiles, maybe that's why the runbot is red, perhaps you sould rebase on 13.0 branch

2020-04-08 21:10 UTC, ernestotejeda commented on sale_order_line_price_history/wizards/sale_order_line_price_history.xml
> +                                <field name="partner_id"/>
```suggestion
                                <field name="partner_id" attrs="{'column_invisible': [('parent.partner_id', '=', False)]}"/>
```
With this we can remove the first statement in ROADMAP section:
https://github.com/OCA/sale-workflow/pull/1082/files#diff-93b55544ac6a86454091405656f9ca6dR55

2020-08-21 14:07 UTC, pedrobaeza commented
Please include #1215

2020-10-12 10:12 UTC, dennybiasiolli commented
I was re-creating the migration for this module, but then I discovered this PR. I would be happy to contribute in this migration, @sudhir-erpharbor do you need help?

2020-10-12 10:22 UTC, sudhir-erpharbor commented
> I was re-creating the migration for this module, but then I discovered this PR. I would be happy to contribute in this migration, @sudhir-erpharbor do you need help?

Sorry, I won't be able to finish it in time. So if you wish, you can take over the PR or improve it.

2020-10-12 10:40 UTC, dennybiasiolli requested changes

2020-10-12 10:40 UTC, dennybiasiolli commented on sale_order_line_price_history/wizards/sale_order_line_price_history.xml
> +                                <field name="price_unit"/>
after this line you should add

```
<label for="discount" groups="sale.group_discount_per_so_line"/>
<div name="discount" groups="sale.group_discount_per_so_line">
    <field name="discount" class="oe_inline"/> %%
</div>
```

2020-10-12 10:40 UTC, dennybiasiolli commented on sale_order_line_price_history/wizards/sale_order_line_price_history.xml
> +                            <field name="price_unit"/>
after this line you should add
```
<field name="discount" groups="sale.group_discount_per_so_line"/>
```

2020-10-12 10:40 UTC, dennybiasiolli commented on sale_order_line_price_history/wizards/sale_order_line_price_history.xml
> +                            <field name="partner_id"/>
this line, in 12.0 was
```
<field name="partner_id"
       column_invisible': [('parent.partner_id', '!=', False)]}"/>
```

@ernestotejeda how can we do in this case?

2020-10-28 21:17 UTC, rousseldenis commented
@sudhir-erpharbor So, we can take into account #1289 instead and close this?

2020-10-29 04:37 UTC, closed without merging