12.0 imp sale min qty
OCA/sale-workflow pull request #1154
Opened 2020-05-26 11:24 UTC by mourad-ehm

Improve  sale_order_min_qty module by adding multiple order management. 
It add hierarchical setting management.
Settings are defined on product, if values are not set we use settings from product template. If settings are not set on product template we use settings from product category otherwise parent category.

2020-05-26 11:25 UTC, mourad-ehm commented
ping @sebastienbeau

2020-05-26 14:47 UTC, bealdav commented
Not sure and not mandatory but it seems there is some duplicate code. Did you consider mixin to avoid that ?

2020-05-26 17:20 UTC, mourad-ehm commented
@bealdav , 
Thanks for review. 
Code refactored. Could you check ?

2020-05-26 20:53 UTC, bealdav requested changes
It's really easier to read with the mixin. Thanks

2020-05-26 20:53 UTC, bealdav commented on sale_order_min_qty/models/product_category.py
> +        res = super(ProductCategory, self)._get_sale_min_multiple_qty()
In python 3 no more super with the same class name than current one
```suggestion
        res = super()._get_sale_min_multiple_qty()
```

2020-05-26 20:53 UTC, bealdav commented on sale_order_min_qty/models/sale.py
> +    @api.multi
no more api.multi in v13, make migration easier, remove
```suggestion
```

2020-05-26 20:53 UTC, bealdav commented on sale_order_min_qty/models/product_min_multiple_mixin.py
> +        " use the value defined in the parent category.",
Is it always ok for product or template ?

2020-05-26 20:53 UTC, bealdav commented on sale_order_min_qty/models/sale.py
>      @api.multi
```suggestion
```

2020-05-26 20:53 UTC, bealdav commented on sale_order_min_qty/models/product_min_multiple_mixin.py
> +        string="multiple Sale Qty", digits=dp.get_precision("Product Unit of Measure")
```suggestion
        string="Multiple Sale Qty", digits=dp.get_precision("Product Unit of Measure")
```

2020-05-26 20:53 UTC, bealdav commented on sale_order_min_qty/views/sale_views.xml
> +                <attribute name="decoration-danger">is_qty_not_multiple_qty ==  True</attribute>
```suggestion
                <attribute name="decoration-danger">is_qty_not_multiple_qty == True</attribute>
```

2020-05-27 11:10 UTC, mourad-ehm commented
I do not understand error of runbot.
Someone can explain me ?

2020-05-27 12:10 UTC, bealdav commented on sale_order_min_qty/models/product_min_multiple_mixin.py
> +        "Product/product Template/product category/parent categoroies ",
Small remarks, not mandatory:
- there are typo errors and expression to fix 
- there are duplicate strings : if you would use CONSTANT VAR to define strings, there will no duplicates and make it easy to fix
- Missing \n make odoo help popup difficult to read

2020-05-27 12:13 UTC, bealdav commented
Runbot is accessible when I test

2020-05-27 12:18 UTC, bealdav commented
Naming and ergonomy could be improved in product and in category

![Selection_011](https://user-images.githubusercontent.com/1853434/83017681-5bf0dc80-a024-11ea-992b-172e0286d5bf.png)
 i.e.
```
<group name=".." string="Sale Quantity">
   <group>
      <group>
         <field ... 1>
         <field ... 2>
      </group>
      <group>
         <field ... 3>
         <field ... 3>
      </group>
   </group>
</group>

```

2020-05-27 15:52 UTC, mourad-ehm commented
Why runbot test is red ? which is the problem ?

2020-05-28 08:13 UTC, rousseldenis commented
> Why runbot test is red ? which is the problem ?

You need to click on runbot details. Then, look at the icon (danger or error). Then, click on the cogs and select 'Full all logs'. Depending on icon, look for ERROR or WARNING. You'll find your problem. I rebuild as logs were no more accessible

2020-05-28 09:10 UTC, mourad-ehm commented
When I click on runbot detail a got :
![image](https://user-images.githubusercontent.com/15939329/83122259-a67d6200-a0d3-11ea-866b-e29b662d3e32.png)

and full base log display:
![image](https://user-images.githubusercontent.com/15939329/83122326-c14fd680-a0d3-11ea-8963-f6a0d87efe35.png)

2020-05-28 09:37 UTC, rousseldenis commented
> When I click on runbot detail a got :
> ![image](https://user-images.githubusercontent.com/15939329/83122259-a67d6200-a0d3-11ea-866b-e29b662d3e32.png)
> 
> and full base log display:
> ![image](https://user-images.githubusercontent.com/15939329/83122326-c14fd680-a0d3-11ea-8963-f6a0d87efe35.png)

Ok, will see with Alex. But you can test locally, look for WARNING and the error is there

2020-05-28 09:38 UTC, bealdav commented
Click on "Full all logs"

2020-05-28 09:58 UTC, mourad-ehm commented
Full all logs give the same error.

2020-05-28 13:06 UTC, HaraldPanten commented
Can you force a new push and see if it works, then?

2020-05-28 19:30 UTC, ValentinVinagre commented
Any solution for runbot? same problem.

2020-06-19 14:59 UTC, mourad-ehm commented
runbot display this errors: ??
Done. Phantomjs binary available at /home/odoo/build/OCA/sale-workflow/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
[91mnpm WARN saveError ENOENT: no such file or directory, open '/home/odoo/build/OCA/sale-workflow/package.json'
[91mERROR: pylint-odoo 0.0.1.dev459 has requirement docutils==0.14, but you'll have docutils 0.12 which is incompatible.
ERROR: pylint-odoo 0.0.1.dev459 has requirement lxml>=4.2.3, but you'll have lxml 3.7.1 which is incompatible.r ?

2020-12-02 10:36 UTC, mourad-ehm commented
Thanks @sebastienbeau for refactor code.
Could you merge this PR Please ?

2020-12-08 10:22 UTC, sebastienbeau approved these changes
LGTM code review and test

2020-12-10 11:00 UTC, bealdav approved these changes

2021-01-21 11:39 UTC, gaikaz commented
One of our clients might need this functionality for Odoo 13.0 pretty soon, but this PR is changing the name of the module.
So I suppose it's not a good idea to migrate it as `sale_min_qty`?
Can we push this PR to get merged?

2021-01-21 12:32 UTC, rousseldenis commented
@mourad-ehm @sebastienbeau @bealdav This seems a bad idea renaming the module in a same version. Why not keeping it and proposing enhancements to 13 or 14 ?

2021-05-01 16:42 UTC, dreispt commented
/ocabot merge major

2021-05-01 18:08 UTC, merged