[FIX][sale_order_line_packaging_qty] Prevent product.packaging without quantity case
OCA/sale-workflow pull request #1178
Opened 2020-07-02 10:45 UTC by Tonow-c2c

Issue to fix by this PR

* Flag a product as "Only sell by packaging"
* Ensure there is no defined packaging for this product
* Create a SO and add a line you have a crash

```python
File "/odoo/external-src/sale-workflow/sale_order_line_packaging_qty/models/sale_order_line.py", line 97, in product_id_change
self.product_uom_qty = min(self.product_id.packaging_ids.mapped("qty"))
ValueError: min() arg is an empty sequence
```

2020-07-02 13:06 UTC, jgrandguillaume approved these changes

2020-07-02 13:07 UTC, jbaudoux approved these changes

2020-07-09 13:59 UTC, grindtildeath requested changes
I find this fix a bit illogical. 
If we want to restrict the sale of a product with its packaging, IMO an error should be raised when the flag is set on a product and no packaging is defined.

Moreover, I tend to think the restriction of selling by packaging should have been done in a separated module to avoid a mix of features in this one that had a well defined perimeter...
cc @guewen  @jgrandguillaume

2020-07-09 13:59 UTC, grindtildeath commented on sale_order_line_packaging_qty/models/sale_order_line.py
> +                self.product_uom_qty = min(quantites)
```suggestion
            quantities = self.product_id.packaging_ids.mapped("qty")
            if quantities:
                self.product_uom_qty = min(quantities)
```

2020-07-10 08:32 UTC, guewen commented
Why the option to force using a packaging on a sale line is in the module that adds the package qty on lines? Seems unrelated?

2020-07-13 15:33 UTC, grindtildeath commented
This PR shouldn't be needed after merging #1191 especially considering https://github.com/OCA/sale-workflow/pull/1174#pullrequestreview-447241590

2020-07-22 15:06 UTC, simahawk commented
closing in favour of https://github.com/OCA/sale-workflow/pull/1191

2020-07-22 15:06 UTC, closed without merging