[IMP] : sale_product_multi_add and sale_order_price_recalculation : homogenize button displays
OCA/sale-workflow pull request #1232
Opened 2020-09-08 10:47 UTC by legalsylvain

Trivial patch.
- homogenize displays of buttons of the module ``sale_product_multi_add`` and ``sale_order_price_recalculation``. some buttons are before lines, some other are after.
- use odoo class instead of custom css. (save some space)

## Before

![image](https://user-images.githubusercontent.com/3407482/92467161-6a2cc800-f1d1-11ea-8083-2fbe863f4da6.png)

## After

![image](https://user-images.githubusercontent.com/3407482/92466834-fdb1c900-f1d0-11ea-9db7-ce01b3801b9b.png)

@SandieFavre, @quentinDupont

#GRAPOCA

2020-09-08 11:06 UTC, pedrobaeza commented
I prefer buttons on bottom, as they are not so important to be before lines.

2020-09-08 11:48 UTC, legalsylvain commented
Hi @pedrobaeza 

> I prefer buttons on bottom, as they are not so important to be before lines.

Well, I think it depends ;-). For some odoo instances, the button is not so important, but for others, with a big use of pricelists, it is very important.

but my point was not about if it is important or not. It's just about UX. 
1) when there are a lot lines, the button are at the bottom of the page, so changing pricelist then update prices is not a user friendly process.
2) this module introduces a concept that is totally new in all Odoo, "a button at the bottom of a form". In fact, when we showed the sale module to newcomers in GRAP, they just did'nt found the button. That's a UX issue IMO.

2020-09-08 11:50 UTC, pedrobaeza commented
Well, I'm only using the recalculation module, and I don't want to have it on top, as it impacts also on the mobile view. If you find a better position (maybe in the header), it's OK for me. If not, I don't accept the change.

2020-09-08 11:54 UTC, legalsylvain commented
> If you find a better position (maybe in the header), it's OK for me

The header is great also. I'm totally agree. I was just saying that putting a button on the bottom of a form is very bad.

2020-09-08 12:18 UTC, hparfr commented
Thanks for the harmonization. 
I prefer when buttons are all on top.

2020-09-08 12:21 UTC, hparfr approved these changes

2020-09-08 12:22 UTC, pedrobaeza requested changes
Change both to header then.

2020-09-08 12:26 UTC, pedrobaeza approved these changes

2020-09-08 12:29 UTC, legalsylvain commented
thanks you both for your review !

2020-09-14 07:16 UTC, pedrobaeza commented
/ocabot merge minor

2020-09-14 07:33 UTC, merged