12.0 add sale order no create partner
OCA/sale-workflow pull request #1275
Opened 2020-10-05 11:46 UTC by MarioVillaescusaPesol

2020-10-09 09:02 UTC, angelmoya approved these changes
tested on runbot :+1:

2020-10-09 09:31 UTC, atchuthan approved these changes

2020-10-12 09:29 UTC, rousseldenis requested changes
Code review. Some changes

2020-10-12 09:29 UTC, rousseldenis commented on sale_order_no_create_partner/__manifest__.py
> +    'maintainers': 'MarioVillaescusaPesol',
This should be in a list.

2020-10-12 09:29 UTC, rousseldenis commented on sale_order_no_create_partner/__manifest__.py
> +    'website': 'https://github.com/OCA/',
You should point the repo. 
```suggestion
    'website': 'https://github.com/OCA/sale-workflow',
```

2020-10-12 09:29 UTC, rousseldenis commented on sale_order_no_create_partner/__manifest__.py
> +# # License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Please set url to https

2020-10-12 09:29 UTC, rousseldenis commented on sale_order_no_create_partner/__init__.py
> +# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
You can remove license here. Not necessary

2020-10-13 08:26 UTC, HaraldPanten approved these changes

2021-03-02 09:11 UTC, MarioVillaescusaPesol commented
@rousseldenis Changes done, can you approve the changes?

2022-10-06 09:20 UTC, rousseldenis commented
/ocabot rebase

2022-10-06 09:21 UTC, rousseldenis commented
@MarioVillaescusaPesol

2022-10-06 09:38 UTC, angelmoya commented
Hi @rousseldenis ... I'm not sure, can I add permission to OCA-git-bot to our repository... this way this will work

2022-10-06 09:43 UTC, rousseldenis commented
@angelmoya No need to. Could you rebase ?

2022-10-06 10:33 UTC, angelmoya commented
Ok, rebase done

2023-03-12 12:23 UTC, closed without merging