[13.0][MIG] sale_stock_picking_note: Migration to 13.0
OCA/sale-workflow pull request #1300
Opened 2020-10-23 08:49 UTC by joao-p-marques

@Tecnativa
TT25948

ping @carlosdauden @chienandalu

2020-10-23 10:37 UTC, HaraldPanten approved these changes
Functional review using runbot 👍

2020-10-24 08:55 UTC, carlosdauden requested changes
Fix travis error:
E231 missing whitespace after ','

2020-10-24 08:55 UTC, carlosdauden commented on sale_stock_picking_note/tests/test_sale_stock_picking_note.py
> +        cls.partner = cls.env["res.partner"].create({"name": "Mr. Odoo",})
```suggestion
        cls.partner = cls.env["res.partner"].create({"name": "Mr. Odoo"})
```

2020-10-24 08:55 UTC, carlosdauden commented on sale_stock_picking_note/tests/test_sale_stock_picking_note.py
> +            {"name": "Test product", "type": "product",}
```suggestion
            {"name": "Test product", "type": "product"}
```

2020-10-24 08:55 UTC, carlosdauden commented on sale_stock_picking_note/tests/test_sale_stock_picking_note.py
> +                    (0, 0, {"product_id": cls.product.id, "product_uom_qty": 1,})
```suggestion
                    (0, 0, {"product_id": cls.product.id, "product_uom_qty": 1})
```

2020-10-26 07:22 UTC, joao-p-marques commented
Thank you @carlosdauden. Changes made.

2020-10-26 11:31 UTC, carlosdauden approved these changes
Travis error unrelated

2020-10-27 11:54 UTC, victoralmau commented
@joao-p-marques Travis errors need solved to review

2020-10-27 12:18 UTC, victoralmau requested changes

2020-10-27 12:18 UTC, victoralmau commented on sale_stock_picking_note/tests/test_sale_stock_picking_note.py
> +        )
```suggestion
        super(TestSaleStockPickingNote, cls).setUpClass()        
        cls.partner = cls.env["res.partner"].create({"name": "Mr. Odoo"})
        cls.product = cls.env["product.product"].create(
            {"name": "Test product", "type": "product"}
        )
        cls.order = cls.env["sale.order"].create(
            {
                "partner_id": cls.partner.id                
            }
        )
        cls.group_id = cls.env["procurement.group"].create(
            {
                "move_type": "one", 
                "sale_id": cls.order.id, 
                "name": cls.order.name
            }
        )
        cls.order_line_1 = cls.env["sale.order.line"].create(
            {
                "order_id": cls.order.id,
                "product_id": cls.product.id,
                "product_uom_qty": 1,
                "name": cls.product.name,
                "procurement_group_id: cls.group_id.id
            }
        )
```

2020-10-27 12:18 UTC, victoralmau commented on sale_stock_picking_note/tests/test_sale_stock_picking_note.py
> +        )
Maybe it solve Travis errors related to `sale_procurement_group_by_line`

2020-10-28 07:50 UTC, joao-p-marques commented
Thanks for the review @victoralmau 
However, taking a look at the latest builds from Travis, there seems to be a problem with `sale_procurement_group_by_line`, indeed, that is affecting all builds: https://travis-ci.com/github/OCA/sale-workflow/jobs/407234444 
I tried changing my test as suggested but I didn't improve the situation...

2020-10-28 13:50 UTC, joao-p-marques commented
Issue opened about this: https://github.com/OCA/sale-workflow/issues/1304

2020-10-28 20:54 UTC, rousseldenis commented
@joao-p-marques Could you rebase when #1305 is merged ?

2020-10-28 21:58 UTC, pedrobaeza commented
You can rebase now

2020-11-09 12:05 UTC, victoralmau commented
Please, check Travis error

2020-11-09 12:31 UTC, joao-p-marques commented
Thank you @victoralmau 
Travis errors are related to prettier, and I think it might be related to https://github.com/pre-commit/pre-commit/issues/1674.
Seems like this was fixed in the 13.0 branch, so I rebased and pushed.

2020-11-09 13:17 UTC, victoralmau approved these changes

2020-11-09 17:13 UTC, pedrobaeza commented
/ocabot merge nobump

2020-11-09 17:34 UTC, merged