[ADD] sale_force_whole_invoiceability: New module
OCA/sale-workflow pull request #1437
Opened 2021-02-02 17:36 UTC by chienandalu

cc @Tecnativa TT27917

2021-02-05 16:17 UTC, pedrobaeza approved these changes
Great reuse of the core!

2021-02-05 16:17 UTC, pedrobaeza commented on sale_force_whole_invoiceability/README.rst
> +of the products invoive policy and the delivered quantities.
```suggestion
This module allows to the sale managers to force all the lines to invoice independently
of the invoice policy and the delivered quantities of the products.
```

2021-02-05 16:26 UTC, rousseldenis requested changes

2021-02-05 16:26 UTC, rousseldenis commented on sale_force_whole_invoiceability/__manifest__.py
> +    "website": "https://www.github.com/OCA/partner-contact",
```suggestion
    "website": "https://www.github.com/OCA/sale-workflow",
```

2021-02-05 16:27 UTC, chienandalu commented on sale_force_whole_invoiceability/README.rst
> +of the products invoive policy and the delivered quantities.
done :+1:

2021-02-05 16:27 UTC, chienandalu commented on sale_force_whole_invoiceability/__manifest__.py
> +    "website": "https://www.github.com/OCA/partner-contact",
ups, thanks!

2021-02-05 16:28 UTC, chienandalu commented on sale_force_whole_invoiceability/__manifest__.py
> +    "website": "https://www.github.com/OCA/partner-contact",
fixed

2021-02-05 16:30 UTC, rousseldenis approved these changes

2021-02-05 16:35 UTC, marcelsavegnago commented on sale_force_whole_invoiceability/readme/USAGE.rst
> +#. But if you are a `Sales Manger`, you have a new button *Force Invoice Policy*
```suggestion
#. But if you are a `Sales Manager`, you have a new button *Force Invoice Policy*
```

2021-02-05 16:37 UTC, chienandalu commented on sale_force_whole_invoiceability/readme/USAGE.rst
> +#. But if you are a `Sales Manger`, you have a new button *Force Invoice Policy*
thanks @marcelsavegnago ! fixed

2021-02-05 16:50 UTC, marcelsavegnago approved these changes

2021-02-05 17:04 UTC, pedrobaeza commented
/ocabot merge nobump

2021-02-05 18:27 UTC, pedrobaeza commented
@chienandalu It seems Travis has gone to red in the last push.

2021-02-08 16:17 UTC, chienandalu commented
Looks like a test from `sale_order_lot_generator` is failing on a missing attribute. The weird thing is that it didn't fail until now: https://travis-ci.com/github/OCA/sale-workflow/jobs/479997013#L2637

2021-02-08 16:37 UTC, pedrobaeza commented
#1446

2021-02-15 15:25 UTC, chienandalu commented
Rebased and fixed

2021-02-16 07:29 UTC, pedrobaeza commented
/ocabot merge nobump

2021-02-16 11:17 UTC, merged

2021-02-16 12:41 UTC, chienandalu commented
Forward ported https://github.com/OCA/sale-workflow/pull/1470