WIP [ADD] module sale_business_provider
OCA/sale-workflow pull request #1448
Opened 2021-02-05 16:26 UTC by mourad-ehm

2021-02-05 16:29 UTC, rousseldenis commented on sale_business_provider/reports/sale_report.py
> +    def _query(self, with_clause="", fields=None, groupby="", from_clause=""):
A little docstring here would be reasonable

2021-02-05 16:29 UTC, rousseldenis commented on sale_business_provider/models/sale.py
> +    business_provider_id = fields.Many2one(comodel_name="res.partner")
Maybe an index ?

2021-02-05 16:54 UTC, mourad-ehm commented on sale_business_provider/models/sale.py
> +    business_provider_id = fields.Many2one(comodel_name="res.partner")
Yes

2021-02-12 09:08 UTC, hparfr requested changes
I suggest to rename this module to "sale_business_introducer" or "sale_business_facilitator".

2021-02-12 09:12 UTC, hparfr requested changes

2021-02-12 09:12 UTC, hparfr commented on sale_business_provider/README.rst
> +commercial transaction.
Too specific and not done in this module. Can be quoted as example of business practice.

2021-02-12 09:12 UTC, hparfr commented on sale_business_provider/README.rst
> +A "Business provider" is a medelmann hwo simply create a link between
```suggestion
A "Business provider" is a middleman who simply create a link between
```

2023-02-12 12:24 UTC, closed without merging