[ADD] Sale Order Weight: New module to 12.0
OCA/sale-workflow pull request #1557
Opened 2021-04-14 09:01 UTC by manuelcalerosolis

This module is used to calculate the weight in a sale order.

![image](https://user-images.githubusercontent.com/3088246/114683777-992f8d00-9d10-11eb-8c6e-699137b9c0b9.png)

2021-04-21 14:15 UTC, legalsylvain commented on sale_order_weight/models/sale_order.py
> +    weight = fields.Float(compute='_compute_weight', string='Weight', store=True)
Hi. This field should not be a computed field, but a field populated by an ochange in my opinion. 
If you change the weight of a product, it should not change the weight of the older orders. (same mechanism as for the price).

don't you think ?

2021-04-22 09:37 UTC, legalsylvain commented
Hi. Thanks for the changes. 

Some ideas, to make the module more generic : 

- I think you could replace the ``weight`` field by a ``unit_weight`` field (in the same spirit as ``unit_price``), on the ``sale.order.line``, and so remove the ``product_uom_qty`` from the ``onchange``.
- Once done ``total_weight`` renamed to ``total_ordered_weight``, computed depends on ``order_line.unit_weight`` and ``order_line.product_uom_qty``
- Then, merge features present in the ``sale_order_delivery_weight``, adding in the current module (``sale_order_weight``) the field ``total_delivery_weight``, computed, depends on ``order_line.unit_weight`` and ``order_line.qty_delivered``

Finally one module, more complete, instead of two, and a homogeneous design to compute each ``total_xx_weight``.

What do you think

2021-04-22 09:57 UTC, manuelcalerosolis commented
> * unit_weight

I like your vision of the solution, I'm going to get on with it.
Thank you for your interest in this module.

2021-04-22 21:53 UTC, legalsylvain approved these changes
Thanks !

2021-04-23 07:00 UTC, rousseldenis requested changes
LGTM apart the digits precision

2021-04-23 07:00 UTC, rousseldenis commented on sale_order_weight/models/sale_order.py
> +    total_ordered_weight = fields.Float(
You should use digits precision for every weight fields:

https://github.com/odoo/odoo/blob/12.0/addons/product/models/product_template.py#L88

2021-04-23 07:00 UTC, rousseldenis commented on sale_order_weight/models/sale_order.py
> +class SaleOrderLine(models.Model):
Could you please put one model per file ?

2021-04-23 07:15 UTC, manuelcalerosolis commented on sale_order_weight/models/sale_order.py
> +    total_ordered_weight = fields.Float(
done!

2021-04-23 07:15 UTC, manuelcalerosolis commented on sale_order_weight/models/sale_order.py
> +class SaleOrderLine(models.Model):
done!

2021-07-28 12:05 UTC, legalsylvain commented
@rousseldenis : could you update your review ? (and merge if all is ok)

2021-07-28 12:10 UTC, rousseldenis approved these changes

2021-07-28 12:10 UTC, rousseldenis commented
/ocabot merge patch

2021-07-28 17:45 UTC, HaraldPanten approved these changes

2021-07-28 20:48 UTC, merged