[14.0][ADD] sale_product_rating_verified
OCA/sale-workflow pull request #1565
Opened 2021-04-21 13:13 UTC by david-popa

Verify if a user has previously bought a product

2021-04-22 18:00 UTC, rousseldenis requested changes
LGTM. Could you maybe add a USAGE fragment with a screenshot ?

2021-04-22 18:00 UTC, rousseldenis commented on sale_product_rating_verified/models/rating.py
> +    purchase_verified = fields.Boolean(
Could you put fields definition on top ?

2021-04-22 18:00 UTC, rousseldenis commented on sale_product_rating_verified/models/rating.py
> +        required=True, default=False, compute="_compute_verified", store=True
I would have done _compute_purchase_verified()

2021-05-05 17:54 UTC, rousseldenis approved these changes

2021-06-02 11:58 UTC, gurneyalex approved these changes
looks a bit strange that the "verified" badge does not change when the invoice gets paid, or that the date of the invoice is before the advice. This could be mentionned in the readme, I think.

2021-07-19 20:11 UTC, dreispt commented
/ocabot merge nobump

2021-07-28 15:18 UTC, rousseldenis commented
/ocabot merge patch

2021-07-28 19:45 UTC, merged