[14.0][MIG] sale_promotion_rule_assortment
OCA/sale-workflow pull request #1584
Opened 2021-05-11 16:19 UTC by xavier-bouquiaux

2021-05-18 08:56 UTC, rousseldenis commented
Depends on:

- [ ] #1583

2022-04-19 16:28 UTC, elvise commented
hi @sbidoul can you check the runboat ?

2022-04-19 16:34 UTC, sbidoul commented
@xavier-bouquiaux can you rebase this PR ?

2023-06-12 08:25 UTC, xavier-bouquiaux commented
> @xavier-bouquiaux can you rebase this PR ?

Done

2023-06-14 09:22 UTC, xavier-bouquiaux commented
rebased as #1583 has been merged

2023-06-14 10:14 UTC, rousseldenis approved these changes

2023-06-14 10:15 UTC, xavier-bouquiaux commented
@acsonefho

2023-06-14 11:11 UTC, acsonefho requested changes

2023-06-14 11:11 UTC, acsonefho commented on sale_promotion_rule_assortment/models/sale_promotion_rule.py
> +            return order_lines
If no `order` and no `line`, you will return `order_lines` before declaring it.

2023-06-14 11:11 UTC, acsonefho commented on sale_promotion_rule_assortment/models/sale_promotion_rule.py
> +        order_line_ids = order_lines.filtered(
Same here: `order_lines` may not exist.

2023-06-14 11:11 UTC, acsonefho commented on sale_promotion_rule_assortment/models/sale_promotion_rule.py
> +        res = super(SalePromotionRule, self)._get_restrictions()
Please use python3 format: `super()._get_restrictions()`

2023-06-14 11:11 UTC, acsonefho commented on sale_promotion_rule_assortment/models/sale_promotion_rule.py
> +        res = super(SalePromotionRule, self)._is_promotion_valid_for_line(line)
Same here: `super()._is_promotion_valid_for_line(line)`

2023-06-14 11:11 UTC, acsonefho commented on sale_promotion_rule_assortment/tests/test_promotion_rule_assortment.py
> +        super(TestPromotionRuleAssortment, self).setUp()
`super().setUp()`

2023-06-14 12:47 UTC, xavier-bouquiaux commented
@rousseldenis : this one is mergeable i think

2023-06-14 13:15 UTC, acsonefho approved these changes

2023-06-16 08:34 UTC, rousseldenis commented
@xavier-bouquiaux Could you squash those commits ? 

![image](https://github.com/OCA/sale-workflow/assets/19529533/bb32e21e-59cc-42ff-9b62-051210b05836)

2023-10-23 05:31 UTC, acsonefho commented
> @xavier-bouquiaux Could you squash those commits ?
> 
> ![image](https://user-images.githubusercontent.com/19529533/246363777-bb32e21e-59cc-42ff-9b62-051210b05836.png)

@xavier-bouquiaux Can you squash please :pray: Then @rousseldenis can merge it :muscle:

2023-11-07 11:02 UTC, xavier-bouquiaux commented
@rousseldenis @acsonefho : squash done  :can we merge ?

2023-11-26 19:26 UTC, dreispt commented
/ocabot merge nobump

2023-11-26 19:50 UTC, merged