[13.0][FIX] sale_order_product_recommendation: commercial_partner_id on delivery_address
OCA/sale-workflow pull request #1588
Opened 2021-05-14 09:07 UTC by CarlosRoca13

On delivery address we want to take into account just this field and not
the commercial_partner_id.

And fixed 1 term to make it impersonal.

cc @Tecnativa TT29597

please @pedrobaeza @victoralmau review this

2021-05-14 11:22 UTC, victoralmau requested changes

2021-05-14 11:22 UTC, victoralmau commented on sale_order_product_recommendation/wizards/sale_order_recommendation.py
> +                (sale_order_partner_field, "child_of", partner.id,),
```suggestion
                (sale_order_partner_field, "child_of", partner.id),
```

2021-05-14 12:50 UTC, pedrobaeza approved these changes

2021-05-14 13:54 UTC, CarlosRoca13 commented
@victoralmau Change done!

2021-05-17 07:09 UTC, victoralmau approved these changes

2021-05-17 07:10 UTC, pedrobaeza commented
/ocabot merge patch

2021-05-17 07:26 UTC, merged