[14.0] [NEW] sale_product_approval: New module added in the repo.
OCA/sale-workflow pull request #1647
Opened 2021-07-07 09:41 UTC by Chandresh-OSI

2021-07-07 14:22 UTC, patrickrwilson commented
@Chandresh-OSI I was testing this on my local instance and couldn't get the 'sale_ok' field to properly set when changing stages. During troubleshooting, if I made the sale_ok not readonly it worked so that seemed to be preventing the field to change properly. I'm testing on enterprise, can you try this on enterprise and see if you see the same issue?

2021-07-07 17:40 UTC, dreispt commented on sale_product_approval/models/product_state.py
> +        string="Approved to be Sold",
To not break current behavior once installed 
```suggestion
        string="Approved to be Sold",
        default=True,
```

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +    )
On install, we need a script to copy the `sale_ok` values to the `candidate_sale` column.

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +    def _onchange_product_state(self):
This won't work for direct API writes, only for user form interaction.
I suggest instead adding a new-stype "onchange" computation to sale_ok.

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +            self.sale_ok = True
```suggestion
        if self.product_state_id:
            self.sale_ok = self.candidate_sale and self.product_state_id.approved_sale
```

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +    def _get_default_product_state_id(self):
Is this missing from the product_state module?

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +            self.env["sale.order"]._log_product_state(order_ids, self)
Instead of "pushing" these updates to Sales Orders, we could have them "pulled" on Sales Orders Lines with a computed field, and then on Sales Order with a computed field depending on SO Lines.

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +    def _onchange_product_state(self):
Not sure we will need this, once we have a computed field.

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/product_state.py
> +                product.sale_ok = True
Make sale_ok computed, and this won't be needed.

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +    exceptions = fields.Boolean(
Field name look too short prone to name collisions 
```suggestion
    exceptions_sale_approval = fields.Boolean(
```

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +        for order in documents:
OOP antipattern
```suggestion
    def _log_exception_activity_sale(self, render_method, product_id):
        for order in self:
```

2021-07-07 18:11 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +    def _log_product_state(self, documents, product_id, cancel=False):
I now see why there we have the write() logic calling this.
Thinking that maybe we could do this with a cron, but let's not go that way for now.

2021-07-19 15:25 UTC, patrickrwilson commented
@Chandresh-OSI It mostly works, I can see the exception banner on the SO and the icon on the SO line but the exception activity doesn't seem to be created anymore. Is this on purpose or a bug?
![image](https://user-images.githubusercontent.com/36892066/126185202-46fc696a-f959-46a9-a538-5438f6216283.png)

2021-07-19 20:05 UTC, patrickrwilson commented
@Chandresh-OSI Tested and works great after the last commit, just need a bit more coverage on tests.

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +    @api.depends("product_state_id")
Missing dependencies
```suggestion
    @api.depends("candidate_sale", "product_state_id.approved_sale")
```

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +                        .ids
Tip: as a general rule, work with records, and extracts ids as late as possible

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +                                ("product_id", "in", product_variant_ids),
`product_variant_ids` is available as a One2many field
```suggestion
                                ("product_id", "in", product.product_variant_ids.ids),
```

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/product_state.py
> +        return res
`sale_ok` is already computed, so this code should not be needed.
```suggestion
```

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +    def _log_exception_activity_sale(self, render_method, documents, product_id):
OOP smells: `documents` is a Sales Order recordset. Just use `self`!

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +    def _log_product_state(self, documents, product_id, cancel=False):
Still not fixed.

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +    def _compute_exceptions(self):
Missing dependencies
```suggestion
    @api.depends("order_line.approved_sale")
    def _compute_exceptions(self):
```

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +            self.exceptions_sale_approval = True
Simplifying
```suggestion
        self.exceptions_sale_approval = any(not line.approved_sale for line in self.order_line)
```

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/product_product.py
> +                    self.env["sale.order"]._log_product_state(order_ids, self)
Can we trigger the exception directly on the the Sale order Line, and have that logic there propagate the exception status up to the Sales Order?
The _log_product_state method causes an exception to be presented so the method name is surprising, and that's not a good thing.

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +        def _render_product_state_excep(order, product_id):
Why a nested method. These are not extensible, do we want to prevent that?

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +        self.env["sale.order"]._log_exception_activity_sale(
Why `self.env["sale.order"]`if self is already a a sales order?

2021-08-04 10:00 UTC, dreispt commented on sale_product_approval/models/sale_order.py
> +            _render_product_state_excep, documents, product_id
Why pass a method as an argument?
This adds complexity, and I don''t see the need or the benefit.

2021-08-04 10:03 UTC, dreispt commented
@Chandresh-OSI @patrickrwilson There are some coding issues here that need improvement, can you work on this please?

Also, there is already a feature for exception handling.
It should be leveraged, and improved if it doesn't do the Activities already.
See https://github.com/OCA/sale-workflow/tree/14.0/sale_exception

2021-08-13 21:44 UTC, patrickrwilson commented
@Chandresh-OSI Looks very close but can you check travis? A test may need changes resulting from your last update. Thanks.

2021-09-07 21:58 UTC, patrickrwilson commented
@Chandresh-OSI can you squash commits then this should be ready to move forward.

2021-09-08 09:12 UTC, Chandresh-OSI commented
supersede by #1713

2021-09-08 09:22 UTC, dreispt commented
Why a new PR was needed?

2021-09-08 09:24 UTC, Chandresh-OSI commented
Due to commit squash issue. I have some merge commits in this PR and it is hard to squash individual commits. So I created new PR for the same code.

2021-09-08 09:31 UTC, dreispt commented
That doesn't require a new PR that restarts the review process.
You squash commits with `git rebase -i` and then force push the same branch.
Do you want to reopen and try that?
Reach out to me if you need more details.

2021-09-08 14:14 UTC, patrickrwilson approved these changes
This works great, LGTM

2021-09-08 14:19 UTC, dreispt commented
...there seems to be an issue with `sale_order_carrier_auto_assign` that is causing tests to fail: https://app.travis-ci.com/github/OCA/sale-workflow/jobs/536164726#L2357

2021-09-08 14:22 UTC, dreispt commented
Trying merge anyway...

2021-09-08 14:22 UTC, dreispt commented
/ocabot merge nobump

2021-11-11 15:15 UTC, rousseldenis requested changes
Code review

2021-11-11 15:15 UTC, rousseldenis commented on sale_product_approval/models/product_product.py
> +                    order_ids = (
Try to move this search outside the loop for performances reasons

2021-11-11 15:15 UTC, rousseldenis commented on sale_product_approval/models/sale_order.py
> +class SaleOrder(models.Model):
Please put one model per file.

2021-11-11 15:15 UTC, rousseldenis commented on sale_product_approval/models/sale_order.py
> +        self.exceptions_sale_approval = any(
You should modify this in order to support multi recordset

2021-11-11 15:15 UTC, rousseldenis commented on sale_product_approval/tests/test_product_approval.py
> +class TestSaleOrderLineDates(TransactionCase):
SavepointCase (until v14) is better in terms of performance.

You can look at this at 6:22:00 https://www.youtube.com/watch?v=lT___hG110Q

2022-04-08 08:07 UTC, rousseldenis commented
@Chandresh-OSI Could you attend comments and solve Travis ?

As you break standard behaviour you need to find a mean to activate or not this behaviour.

2023-06-22 09:51 UTC, rousseldenis commented
@Chandresh-OSI @dreispt What's the status of this ?

2023-08-30 11:01 UTC, rousseldenis commented
@Chandresh-OSI @dreispt

2023-11-26 21:04 UTC, dreispt commented
All review comments addressed, merging.

/ocabot merge nobump

2023-12-18 08:58 UTC, dreispt commented
/ocabot merge nobump

2023-12-18 09:27 UTC, dreispt commented
/ocabot merge nobump

2024-06-02 12:22 UTC, closed without merging