[14.0] [mig] sale_procurement_group_by_line
OCA/sale-workflow pull request #1689
Opened 2021-08-09 07:14 UTC by fredzamoabg

Migration to v14. 
Just the same as https://github.com/OCA/sale-workflow/pull/1498 including commit squash required (because no updates from Jun 23)

2021-10-15 14:35 UTC, SimoRubi requested changes
Thanks for the PR!
The module `sale_procurement_group_by_line` in v13 (https://github.com/OCA/sale-workflow/tree/13.0/sale_procurement_group_by_line) is more updated than the one you are migrating here, for instance https://github.com/OCA/sale-workflow/pull/1631 here is missing.
Can you include the missing changes?

2021-10-15 14:35 UTC, SimoRubi commented on sale_procurement_group_by_line/model/sale.py
> +                errors.append(error.name)
`name` is deprecated:
https://github.com/odoo/odoo/blob/29e844a86508b39031fa8c3f1a2ef3735f71e6f2/odoo/exceptions.py#L34-L39
please replace it with the suggested field.

2021-10-15 14:35 UTC, SimoRubi commented on sale_procurement_group_by_line/model/sale.py
> +                procurement_uom = quant_uom
This part has been extracted in method `uom.uom._adjust_uom_quantities` (https://github.com/odoo/odoo/blob/48698838dd47442145395d3d4396b64b6901dba1/addons/stock/models/product.py#L906)
Why don't we call that method instead of doing again the same actions?

2021-10-15 14:35 UTC, SimoRubi commented on sale_procurement_group_by_line/model/sale.py
> +    def _action_launch_stock_rule(self, previous_product_uom_qty=False):
This method looks mostly like a copy-paste of https://github.com/odoo/odoo/blob/ca7d5701c6a46f7781bdc9af9f2d26cca880eb93/addons/sale_stock/models/sale_order.py#L560, can you update this to reflect changes that happened in upstream?
For instance here we are missing https://github.com/odoo/odoo/blob/ca7d5701c6a46f7781bdc9af9f2d26cca880eb93/addons/sale_stock/models/sale_order.py#L569

2021-10-18 08:17 UTC, rousseldenis commented
@fredzamoabg There is yet another PR for this module : #1498 as you mentionned

Could you review that one instead ?

2021-10-18 08:22 UTC, rousseldenis commented
I pinged the author from the other one. We'll wait a bit, then if no response, switch on this.

2021-10-18 13:11 UTC, SimoRubi requested changes

2021-10-18 13:11 UTC, SimoRubi commented on sale_procurement_group_by_line/model/sale.py
> +                        line.order_id.company_id,
Does @koenloodts agree with including this change in its commit?
If you haven't asked the commit's author, please do your changes in your own commits.

Also note that changes coming from `13.0` should not be in the migration commit, can you include them by cherry-picking the original commit instead?
Ideally, the migration should include all commits from `13.0`, and then whatever is needed for the migration, see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch.
https://github.com/OCA/odoo-module-migrator can help with the process.

2021-10-18 13:11 UTC, SimoRubi commented on sale_procurement_group_by_line/model/sale.py
> +                qty=product_qty, quant_uom=quant_uom
`qty` and `quant_uom` are positional arguments, why are they here assigned like keyword arguments?

2021-10-18 13:56 UTC, fredzamoabg commented on sale_procurement_group_by_line/model/sale.py
> +                        line.order_id.company_id,
performed cherry-pick as requested.

2021-10-19 12:40 UTC, SimoRubi requested changes

2021-10-19 12:40 UTC, SimoRubi commented on sale_procurement_group_by_line/model/sale.py
> +                        line.order_id.company_id,
> Does @koenloodts agree with including this change in its commit?
If you haven't asked the commit's author, please do your changes in your own commits.

2021-12-06 10:31 UTC, francesco-ooops commented
hi @fredzamoabg , any plan to finish/merge this?
Thanks!

2021-12-06 10:36 UTC, fredzamoabg commented
> hi @fredzamoabg , any plan to finish/merge this? Thanks!

Hi, I'm not able to merge PRs, anyway I did not plan to do nothing else on this so I think you can do a code review (or functional review).

2021-12-06 10:41 UTC, francesco-ooops commented
@SimoRubi @rousseldenis any chance to review?

2021-12-06 10:58 UTC, SimoRubi requested changes

2021-12-06 10:58 UTC, SimoRubi commented on sale_procurement_group_by_line/model/sale.py
> +                        line.order_id.company_id,
>>Does @koenloodts agree with including this change in its commit?
>>If you haven't asked the commit's author, please do your changes in your own commits.

2021-12-07 10:20 UTC, koenloodts commented on sale_procurement_group_by_line/model/sale.py
> +                        line.order_id.company_id,
I agree! (sorry for the late response)

2021-12-22 08:37 UTC, BernatPForgeFlow approved these changes
Functional test OK with sale_stock_delivery_address in this PR #1833

2021-12-22 12:27 UTC, rousseldenis approved these changes
Code review

2021-12-22 12:28 UTC, rousseldenis commented
/ocabot migration sale_procurement_group_by_line

2021-12-23 08:37 UTC, JoanMForgeFlow approved these changes
Code review LG!

2022-01-07 09:29 UTC, JoanMForgeFlow reviewed
could we merge this?

2022-01-10 08:01 UTC, BernatPForgeFlow commented
@rousseldenis  Can you try again ocabot migration?

2022-01-13 08:38 UTC, BernatPForgeFlow commented
@SimoRubi Could you please review this PR? Thank you

2022-01-18 13:28 UTC, rousseldenis commented
/ocabot migration sale_procurement_group_by_line

2022-02-01 11:29 UTC, JoanMForgeFlow commented
@simahawk could you merge this please?

2022-02-08 07:17 UTC, simahawk commented
/ocabot merge nobump

2022-02-08 07:44 UTC, merged