[14.0][IMP] sale_discount_display_amount: Adds hook for depends
OCA/sale-workflow pull request #1704
Opened 2021-08-30 07:53 UTC by rousseldenis

Allows to override the different amount computations.

@chafique-delli @simahawk

2021-09-06 09:31 UTC, simahawk requested changes

2021-09-06 09:31 UTC, simahawk commented on sale_discount_display_amount/models/sale_order.py
> +    def _get_compute_discount_total_domain(self):
```suggestion
    def _compute_discount_total_depends(self):
```

2021-09-06 09:31 UTC, simahawk commented on sale_discount_display_amount/models/sale_order_line.py
> +    def _get_compute_amount_domain(self):
```suggestion
    def _compute_amount_depends(self):
```

2021-09-06 09:32 UTC, simahawk approved these changes
not blocking indeed. Pre-approving anyway ;)

2021-10-08 08:58 UTC, rousseldenis commented
@simahawk Done

2021-10-28 15:50 UTC, ivantodorovich approved these changes

2021-11-26 10:07 UTC, dreispt commented
/ocabot merge patch

2021-11-26 11:54 UTC, merged