[14.0] [ADD] sale_product_approval_stock: Added new module to handle delivery order product workflow.
OCA/sale-workflow pull request #1718
Opened 2021-09-23 11:37 UTC by Chandresh-OSI

Depends on #1647

2021-09-24 13:53 UTC, patrickrwilson commented
@Chandresh-OSI during testing I noticed two things on the delivery order.
1. Can you change the wording on the exception activity to say 'Deliverable' instead of 'Saleable' where is says the product is marked as not saleable.
2. After the delivery order is created and you move the product to a stage that doesn't allow shipping, it seems to generate two exceptions on the DO. Can you make it only create one.
![image](https://user-images.githubusercontent.com/36892066/134685939-33263e9e-0e4f-415a-bc4d-0ce7fa18fd0f.png)

2021-11-11 15:21 UTC, rousseldenis requested changes
Code review

2021-11-11 15:21 UTC, rousseldenis commented on sale_product_approval_stock/models/product_template.py
> +class ProductProduct(models.Model):
Please split one model per file

2021-11-11 15:21 UTC, rousseldenis commented on sale_product_approval_stock/models/product_template.py
> +                pick_ids = self.env["stock.picking"].search(
Please do the search before loop.

2021-11-11 15:21 UTC, rousseldenis commented on sale_product_approval_stock/models/stock_picking.py
> +    do_exceptions = fields.Boolean(
IMHO, things have to be split as following the name of this, it should be moved in a more generic module.

2021-11-11 15:21 UTC, rousseldenis commented on sale_product_approval_stock/models/stock_picking.py
> +        for do in self:
```suggestion
        for picking in self:
```
is more explicit for reviewer

2021-11-11 15:21 UTC, rousseldenis commented on sale_product_approval_stock/models/stock_picking.py
> +class StockMove(models.Model):
Please split one model per file

2021-11-11 15:21 UTC, rousseldenis commented on sale_product_approval_stock/views/delivery_order_exception.xml
> +    <data>
```suggestion
```

2023-10-29 12:20 UTC, closed without merging