14.0 mig product form sale link
OCA/sale-workflow pull request #1722
Opened 2021-09-24 11:10 UTC by dani-xtendoo

Product form sale link migration to 14.0

2021-10-01 14:25 UTC, ajaniszewska-dev approved these changes

2021-10-04 15:47 UTC, rousseldenis requested changes
Hi @dani-xtendoo 

Thanks for your contribution.

Could you read https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 ?

Especially the 'Full process' part ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#howto

You need to have one commit for pre-commit and one for the migration itself.

2021-10-04 15:47 UTC, rousseldenis commented on product_form_sale_link/__manifest__.py
> +# Copyright 2021 Xtendoo
Don't add yourself to authors for a migration.

You should add just a line in CONTRIBUTORS

2021-10-04 15:47 UTC, rousseldenis commented on product_form_sale_link/__manifest__.py
> +    "author": "Xtendoo, ACSONE SA/NV,Odoo Community Association (OCA)",
Same as above

2021-10-04 15:47 UTC, rousseldenis commented on product_form_sale_link/__manifest__.py
> +    "version": "14.0.1.0.1",
You need to reset this to 14.0.1.0.0

2021-10-04 15:47 UTC, rousseldenis commented on product_form_sale_link/views/product_product.xml
> +<!-- Copyright 2021 Xtendoo
Same as above

2021-10-04 15:47 UTC, rousseldenis commented on product_form_sale_link/views/product_template.xml
> +<!-- Copyright 2021 Xtendoo
Same as above

2021-10-04 15:47 UTC, rousseldenis commented on product_form_sale_link/views/sale_order_line.xml
> +<!-- Copyright 2021 Xtendoo
Same as above

2021-12-22 13:34 UTC, manuelcalerosolis approved these changes
Functional and code review!

2022-03-02 09:16 UTC, colmeirin commented
There is a bit of an issue with the module. It works OK with only "sale" module installed but if you have installed "stock" module, it crashes the installation with the view product_template.xml. This happens because odoo core "stock" module has a view that deletes the button name="action_view_sales" by replacing it(id="product_template_view_form_inherit_sale") and redefines it in another view(id="product_template_view_form_inherit_stock") so this module can't find the button to inherit and therefore crashes the instalation.

2022-05-16 13:06 UTC, rousseldenis commented
Closing this as already migrated in #2012

2022-05-16 13:06 UTC, closed without merging