[ADD] pricelist_cache_rest
OCA/sale-workflow pull request #1764
Opened 2021-11-08 03:32 UTC by kv1612

2021-11-08 07:23 UTC, simahawk requested changes
LG. Docs should be improved.

2021-11-08 07:23 UTC, simahawk commented on pricelist_cache_rest/readme/DESCRIPTION.rst
> +Provides an endpoint to get product prices for a given customer
```suggestion
Provides an endpoint to expose product prices cached by `pricelist_cache`.
Endpoint authorization is based on `auth_api_key`.
```
then pls add a `USAGE.rst` module to explain how to use like:

```rst
The endpoint requires the partner ID of the customer prices for which you want to retrieve prices.
It should be called like this::

    curl -X GET "http://your.odoo/pricelist/$partner_id" -H "accept: /" -H "API-KEY: XYZ"

By default you'll get a list of dict like this::

    [
        {"id": $product_id, "price": $price},
        {"id": $product_id, "price": $price},
        {"id": $product_id, "price": $price},
    ]

You can modify the `ir.exports` configuration named "Pricelist Cache Parser" to change this schema.
```
Then add a `CONFIGURATION.rst` to describe how to configure api keys and set them on the company.

2021-11-08 08:21 UTC, TDu commented on pricelist_cache_rest/wizards/res_config_settings.py
> +# TODO: this should be moved to `../models`
This todo should be attended

2021-11-08 12:33 UTC, kv1612 commented
Hi @simahawk, @TDu ! Thanks for your review. This PR has been updated.

2021-11-08 14:20 UTC, mmequignon approved these changes

2021-11-09 10:41 UTC, simahawk requested changes

2021-11-09 10:41 UTC, simahawk commented on pricelist_cache_rest/wizards/res_config_settings.xml
> +                <b modifiers="{}">Authored Pricelist Cache API keys</b>
```suggestion
                <b modifiers="{}">Authorized Pricelist Cache API keys</b>
```

2021-11-09 10:41 UTC, simahawk commented on pricelist_cache_rest/readme/CONFIGURATION.rst
> +#. Go to `Settings > Units of Measure`.
UoM? :thinking: 
We should have a specific box for this IMO.

2021-11-09 10:41 UTC, simahawk commented on pricelist_cache_rest/readme/CONFIGURATION.rst
> +#. Add your api keys to table `Authored Pricelist Cache API keys`.
```suggestion
#. Add your api keys to table `Authorized Pricelist Cache API keys`.
```

2021-11-11 05:12 UTC, kv1612 commented
Hi @simahawk, thank for your review. I created another box and put table `Authorized Pricelist Cache API keys` in it. This PR has been updated.

2021-11-11 07:22 UTC, simahawk approved these changes

2021-11-11 07:47 UTC, simahawk commented
/ocabot merge nobump

2021-11-11 08:09 UTC, merged