[15.0][MIG] sale force invoiced
OCA/sale-workflow pull request #1823
Opened 2021-12-14 11:30 UTC by JasminSForgeFlow

Standard Migration
@ForgeFlow

2021-12-15 16:40 UTC, ChrisOForgeFlow approved these changes
+1

2021-12-16 10:35 UTC, HaraldPanten requested changes
**Functional review**

Steps to reproduce:

After activating Locking options for Sale orders:

1- Create a quotation and confirm it.
2- You have a locked sale order.
3- Unlock the SO.
4- Edit and mark the checkbox for forcing the invoice status to fully invoiced.

Shouldn't the checkbox be available to be edited only when SO is locked?

2021-12-21 08:49 UTC, LoisRForgeFlow commented
> **Functional review**
> 
> Steps to reproduce:
> 
> After activating Locking options for Sale orders:
> 
> 1- Create a quotation and confirm it. 2- You have a locked sale order. 3- Unlock the SO. 4- Edit and mark the checkbox for forcing the invoice status to fully invoiced.
> 
> Shouldn't the checkbox be available to be edited only when SO is locked?

Hi @HaraldPanten Thas was change here https://github.com/OCA/sale-workflow/pull/1823/commits/4e799dc60bf6f66407d89325aee39201b18c49aa. Since locking a SO is a manual actions, not all companies lock them and just let them in sales status, thefore instead of forcing them to lock SOs, we preferred to add more flexibility to the functionality.

Does this makes sense to you?

2021-12-21 08:50 UTC, LoisRForgeFlow commented on sale_force_invoiced/README.rst
> +#. Lock the Sale Order, to change the status of it to 'Done'.
@HaraldPanten maybe what is missing is to update the usage?

2021-12-21 09:21 UTC, HaraldPanten commented
Hi @LoisRForgeFlow Definitely, I didn't keep in mind that commit... you're right.

@JasminSForgeFlow just update the Readme as Lois is suggesting and I'll approve it.

THX.

2021-12-22 09:38 UTC, JasminSForgeFlow commented
Hi @HaraldPanten ,

Usage has been update.

Thanks

2021-12-22 10:41 UTC, HaraldPanten approved these changes
Functional review, LGTM

2021-12-22 15:44 UTC, LoisRForgeFlow commented
@HaraldPanten you can merge at your convenience!

2021-12-22 17:47 UTC, HaraldPanten commented
/ocabot merge nobump

2021-12-22 17:52 UTC, merged