[13.0][MIG] sale_order_line_note
OCA/sale-workflow pull request #1828
Opened 2021-12-20 07:31 UTC by dalonsod

Standard migration

2021-12-20 08:39 UTC, dalonsod commented
@sebastienbeau @danimv5 could you review? Thanks!

2021-12-23 13:20 UTC, rousseldenis commented
/ocabot migration sale_order_line_note

2021-12-23 13:23 UTC, rousseldenis requested changes
Code review

2021-12-23 13:23 UTC, rousseldenis commented on sale_order_line_note/__manifest__.py
> +    "external_dependencies": {"python": [], "bin": []},
Please remove void entries

2024-02-04 12:19 UTC, closed without merging