[14.0][MIG] sale_product_set_layout
OCA/sale-workflow pull request #1839
Opened 2021-12-23 15:13 UTC by rousseldenis

2021-12-23 15:14 UTC, rousseldenis commented
/ocabot migration sale_product_set_layout

2022-01-12 16:14 UTC, ajaniszewska-dev approved these changes

2022-06-13 13:17 UTC, rousseldenis commented
@manuelregidor Could you review this ?

2022-06-15 10:01 UTC, manuelregidor requested changes

2022-06-15 10:01 UTC, manuelregidor commented on sale_product_set_layout/models/product_set.py
> +class ProductSet(models.Model):
Shouldn't it be ProductSetLine?

2022-06-15 10:01 UTC, manuelregidor commented on sale_product_set_layout/tests/__init__.py
> +# from . import test_product_set_layout
Tests are not launched

2022-06-15 10:01 UTC, manuelregidor commented on sale_product_set_layout/views/product_set.xml
> +            <xpath expr="//field[@name='set_line_ids']/tree" position="inside">
I think the lines in this tree view shoul be editable, so more products/notes/sections can be added from outside the form view.

2022-06-15 10:01 UTC, manuelregidor commented on sale_product_set_layout/views/product_set.xml
> +                <field name="display_type" />
Shouldn't this field be invisble?

2024-02-25 12:19 UTC, closed without merging