[15.0][MIG] sale_stock_picking_blocking
OCA/sale-workflow pull request #1888
Opened 2022-01-26 17:53 UTC by kirca

2022-02-03 08:10 UTC, rousseldenis commented
/ocabot migration sale_stock_picking_blocking

2022-02-03 08:16 UTC, rousseldenis requested changes
@kirca Thanks for your contribution. Could you attend comments ?

I advise you to follow for the next time https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

And especially the Full process part. Thanks

2022-02-03 08:16 UTC, rousseldenis commented on sale_stock_picking_blocking/tests/test_sale_stock_picking_blocking.py
> +    def setUp(self):
Could you change this to classmethod setUpClass ? It will allow to not load this at each test.

2022-02-03 08:16 UTC, rousseldenis commented on sale_stock_picking_blocking/models/sale_order.py
> +    delivery_block_id = fields.Many2one(
Could you put fields definition on top ?

2022-02-03 08:46 UTC, kirca commented
Thanks @rousseldenis I've added the changes.

I did follow to migration guideline however and they do not seem to appear in the pre-commit checks.

2022-02-03 09:05 UTC, rousseldenis commented
> Thanks @rousseldenis I've added the changes.
> 
> I did follow to migration guideline however and they do not seem to appear in the pre-commit checks.

It's about these lines that should be done before the code migration itself:

![image](https://user-images.githubusercontent.com/19529533/152312315-28cc5a3e-c4fd-4feb-a4c8-f8f6215dd8c2.png)

2022-05-12 13:23 UTC, JuanyDForgeflow commented
@kirca Do you plan to continue this?

2022-06-08 13:23 UTC, leemannd approved these changes
Thank you

2022-06-09 07:59 UTC, yvaucher approved these changes

2022-06-09 08:03 UTC, yvaucher commented
@rousseldenis comments are solved this is ready to merge

2022-06-09 08:03 UTC, yvaucher commented
/ocabot merge nobump

2022-06-09 08:12 UTC, merged