[14.0][IMP] sale_order_line_discount_validation: add test cases
OCA/sale-workflow pull request #1908
Opened 2022-02-10 23:31 UTC by csil300

2022-02-18 19:06 UTC, rafaelbn commented
Dear @csil300 thank you for this great contribution. Please could you check https://github.com/OCA/sale-workflow/pull/1908#issuecomment-1035641291 and sign CLA? Thank you

Dear @rousseldenis this looks like a good improvement adding just test, what do you think? Thank you

2022-02-21 07:45 UTC, rousseldenis requested changes

2022-02-21 07:45 UTC, rousseldenis commented on sale_order_line_discount_validation/tests/test_sale_order_line_discount_validation.py
> +    def setUp(self):
@csil300 Thanks for this. Could you change to SavepointCase as it is faster and change setup to setUpClass ? Thanks

2022-03-11 19:11 UTC, max3903 commented
> Hey @csil300, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet. You can read and sign our full Contributor License Agreement here: http://odoo-community.org/page/cla Here is a list of the users:
> 
> * @csil300 (login unknown in OCA database)
> 
> Appreciation of efforts, OCA CLAbot

Fixed

2022-03-12 22:08 UTC, rafaelbn commented
After @csil300 answer to https://github.com/OCA/sale-workflow/pull/1908#discussion_r810849243 we can go ahead!

2024-04-14 14:41 UTC, closed without merging