[14.0][MIG] sale_order_invoicing_finished_task: Migration to 14.0
OCA/sale-workflow pull request #1924
Opened 2022-02-17 22:07 UTC by ernestotejeda

Cc @Tecnativa TT34133

2022-02-17 22:20 UTC, ernestotejeda commented
ping @carlosdauden @sergio-teruel @Tardo

2022-02-18 08:07 UTC, sergio-teruel requested changes

2022-02-18 08:07 UTC, sergio-teruel commented on sale_order_invoicing_finished_task/models/project.py
> +        readonly=True,
readonly=True for related fields is not needed, is the default value

2022-02-18 08:07 UTC, sergio-teruel commented on sale_order_invoicing_finished_task/views/project_view.xml
> +            <xpath expr="//field[@name='partner_id']/.." position="inside">
Please by change this 

```
            <div name="button_box" position="inside">
                <field name="invoiceable" invisible="1"/>
                <button
                    name="toggle_invoiceable"
                    type="object"
                    attrs="{'invisible': [('invoicing_finished_task','=', False)]}"
                    class="oe_stat_button"
                    icon="fa-file"
                >
                    <span class="text-success" attrs="{'invisible': [('invoiceable', '=', False)]}">Invoiceable</span>
                    <span class="text-danger" attrs="{'invisible': [('invoiceable', '!=', False)]}">Not Invoiceable</span>
                </button>
            </div>

```

2022-02-18 19:01 UTC, rafaelbn commented
/ocabot migration sale_order_invoicing_finished_task

2022-02-23 20:51 UTC, ernestotejeda commented
@sergio-teruel changes done

2022-02-24 08:58 UTC, pedrobaeza commented
Travis red due to error in upstream Odoo. Fix in https://github.com/odoo/odoo/pull/85269

2022-02-24 23:05 UTC, carlosdauden approved these changes

2022-06-18 08:37 UTC, sergio-teruel approved these changes
Functional test OK!!

Code review OK!!

2022-06-18 15:10 UTC, pedrobaeza commented
CI fixed in #2081

/ocabot merge nobump

2022-06-18 15:30 UTC, merged