14.0 add sale order line last price
OCA/sale-workflow pull request #1925
Opened 2022-02-18 13:00 UTC by dani-xtendoo

Added sale_line_last_price, which extends the functionality of sale_order_line_price_history, removing filtering by customers

2022-03-11 16:04 UTC, flotho requested changes
functionnaly tested and it rocks.
I would just recommend to put your icon next to the unit price so that user will be able to understand what is this behaviour.

2022-04-28 15:50 UTC, angelmoya requested changes
Can you explain the behavior for this development?

I checked that you disable customer filter, but this filter is useful.

Also you talk about sale_line_last_price, but I can only see that you disable the original partner filter.

2022-04-28 15:50 UTC, angelmoya commented on sale_order_line_last_price/README.rst
> +   all customers.
This comment is not acording with the code... in code you hide partner field... that also is not ritght

2022-04-28 15:50 UTC, angelmoya commented on sale_order_line_last_price/wizards/sale_order_line_last_price.xml
> +            </xpath>
Why do you use replace? Why not to show it and be able to set or unset partner to show related history

2024-03-18 16:47 UTC, rousseldenis commented
@dani-xtendoo What's the status of this ?

2024-08-25 12:25 UTC, closed without merging