[15.0][MIG] sale_stock_picking_note
OCA/sale-workflow pull request #1930
Opened 2022-02-22 22:59 UTC by juanpgarza

Standard migration

2022-02-23 07:28 UTC, legalsylvain requested changes
Could you split sale_stock.py, a file per model ?

Otherwise,lgtm. Code review / no test.

2022-02-23 08:08 UTC, rousseldenis commented
@juanpgarza Thanks for this. Could you check tests ?

2022-02-23 23:28 UTC, juanpgarza commented
> @juanpgarza Thanks for this. Could you check tests ?

I can't see the error. Could you help me please?

2022-05-12 13:29 UTC, JuanyDForgeflow commented
@juanpgarza The test error is not related to this module but on the sale_automatic_workflow module

![image](https://user-images.githubusercontent.com/103428640/168085953-343da92f-5b21-4aa0-b3df-d32929ad9940.png)

2022-05-16 18:16 UTC, rousseldenis commented
/ocabot rebase

2022-05-16 18:18 UTC, rousseldenis commented on sale_stock_picking_note/models/sale_order.py
> +    picking_note = fields.Html(string="Picking Internal Note")
@juanpgarza Why changing this to Html ?

2023-02-17 18:45 UTC, AaronHForgeFlow commented
The module is migrated. This can be closed.

2023-06-22 15:05 UTC, closed without merging