15.0 mig sale order revision
OCA/sale-workflow pull request #1931
Opened 2022-02-24 10:05 UTC by jwaes

#1741

2022-06-22 15:03 UTC, leemannd approved these changes
Migration ok and module tested. Works like a charm

2022-09-20 10:10 UTC, CRogos approved these changes
Code and functional review LGTM!

2022-09-20 22:34 UTC, CRogos commented
https://github.com/OCA/server-ux/pull/522 has been accepted. Could you re trigger the build to see if build and tests are ok?

2022-11-11 08:08 UTC, cyrilmanuel approved these changes
@jwaes LGTM Could you re trigger the build ?

2022-11-11 09:35 UTC, simahawk commented
/ocabot migration sale_order_revision

2022-11-11 09:36 UTC, simahawk commented
@jwaes pls rebase and drop the merge commit, thanks.

2022-11-11 09:37 UTC, simahawk requested changes
waiting for rebase and green build

2022-11-23 09:08 UTC, leemannd commented
Hello @simahawk I superseeds the PR in -> https://github.com/OCA/sale-workflow/pull/2275

2022-11-23 13:20 UTC, simahawk commented
@leemannd ok but is red too ;)

2022-11-23 13:20 UTC, closed without merging

2022-11-23 13:29 UTC, leemannd commented
@simahawk Yep, I'll be fixing the test inbetween this week and early next one