[IMP] sales_team_security: salesman and channel inherited
OCA/sale-workflow pull request #1938
Opened 2022-03-08 12:00 UTC by chienandalu

We want to propagate any salesman or sales channel change to the entity
children.

cc @Tecnativa TT34055

please check @pedrobaeza @victoralmau

2022-03-08 14:48 UTC, pedrobaeza commented
Check Travis. And not sure if the method should be that one. There's already code for the propagation AFAIK.

2022-03-15 10:31 UTC, rousseldenis requested changes

2022-03-15 10:31 UTC, rousseldenis commented on sales_team_security/models/res_partner.py
> +        return super()._commercial_fields() + ["user_id", "team_id"]
This has nothing common with module purpose.

This should be in another module IMHO

2022-03-15 10:40 UTC, pedrobaeza commented
This one is not needed at all, at least not this way.

2022-03-15 10:40 UTC, closed without merging