[15.0][mig] sale_product_seasonality
OCA/sale-workflow pull request #1992
Opened 2022-04-22 14:16 UTC by damdam-s

set installable=False because of pending refactoring https://github.com/OCA/product-attribute/pull/1063

2022-04-22 14:17 UTC, damdam-s commented
@simahawk something like this one? and now I create a new PR with the refactoring?

2022-04-22 14:28 UTC, simahawk requested changes
yes, no need for any migration process tho: just port the module AS IS from v14 and set it as not installable (like when we used to have pre-initialized repos)

2022-04-22 14:28 UTC, simahawk commented on sale_product_seasonality/__manifest__.py
> +# Copyright 2021 - 2022 Camptocamp SA
no need to add current year

2022-04-22 14:28 UTC, simahawk commented on sale_product_seasonality/__manifest__.py
> +    "version": "15.0.1.0.0",
if we don't keep the name is pointless to change this number

2024-03-18 17:01 UTC, rousseldenis commented
/ocabot migration sale_product_seasonality

2024-03-18 17:02 UTC, rousseldenis commented
@damdam-s What's the status of this ?

2024-07-16 07:45 UTC, rousseldenis commented
@damdam-s Could we close this as the depending PR is closed too ?

2024-12-22 12:27 UTC, closed without merging