[15.0]ADD sale_blanket_order_margin
OCA/sale-workflow pull request #2090
Opened 2022-06-22 12:48 UTC by leemannd

2022-06-23 14:45 UTC, leemannd commented on sale_blanket_order_margin/views/sale_blanket_order_views.xml
> +    <!-- TODO: Check, this seems related to the report -->
TODO: I'm currently checking if we want to add it also into reports

2022-06-24 06:25 UTC, santostelmo approved these changes
LG

2022-07-19 11:29 UTC, yvaucher approved these changes

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/__init__.py
> +from . import blanket_order_line
Please don't use plurals :wink:

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_orders.py
> +                    blanket.amount_untaxed and blanket.margin / blanket.amount_untaxed
I have a hard time to understand what a boolean and a numerical operator are doing together :confused:

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_orders.py
> +                    blanket.amount_untaxed and blanket.margin / blanket.amount_untaxed
same as above

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/tests/test_sale_blanket_order_margin.py
> +        blanket_order.sudo().onchange_partner_id()
Try to use `Form` in your test to avoid having to call onchanges explicitely :wink:

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_order_line.py
> +                line.price_subtotal and line.margin / line.price_subtotal
Same again

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_order_line.py
> +    purchase_price = fields.Float(
Can't we call this the `cost_price` as we don't necessarily purchase it?

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_order_line.py
> +        groups="base.group_user",
I don't think we need to set this group here or do I miss something? :thinking:

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_order_line.py
> +        to_cur = self.currency_id or self.order_id.currency_id
```suggestion
        to_cur = self.currency_id
```
This is a related field

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_order_line.py
> +            date = self.date_shedule
```suggestion
            date = self.date_schedule
```
:warning:

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_order_line.py
> +            if to_cur and product_cost
Shouldn't `to_cur` always be defined? I feel like the currency conversion should only happen if we have different currencies but I might be wrong.

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_order_line.py
> +    @api.depends("product_id", "company_id", "currency_id", "original_uom_qty")
Missing dependency on `product_id.standard_price` and `product_id.uom_id`.

2022-11-29 18:07 UTC, grindtildeath commented on sale_blanket_order_margin/models/blanket_order_line.py
> +        readonly=False,
If the computed field is editable, don't you need to check if it was edited before triggering recomputation?

2022-11-30 06:59 UTC, simahawk requested changes

2022-11-30 06:59 UTC, simahawk commented on sale_blanket_order_margin/__manifest__.py
> +    "summary": "Blanket Orders",
the summary is shorter than the name? :thinking:

2022-11-30 06:59 UTC, simahawk commented on sale_blanket_order_margin/models/blanket_order_line.py
> +            date = self.date_shedule
no tests? :/

2022-11-30 06:59 UTC, simahawk commented on sale_blanket_order_margin/tests/test_sale_blanket_order_margin.py
> +        self.blanket_order_obj = self.env["sale.blanket.order"]
never use setUp unless you really need it, go for setUpClass pls :pray: 
And disable tracking, tnx!

2023-01-26 13:22 UTC, closed without merging