[15.0][MIG] sale_order_line_input: Migration to 15.0
OCA/sale-workflow pull request #2114
Opened 2022-07-06 11:26 UTC by cesar-tecnativa

@Tecnativa TT36521

2022-07-06 19:38 UTC, cesar-tecnativa commented
@CarlosRoca13 could you check?

2022-07-07 05:13 UTC, CarlosRoca13 approved these changes

2022-07-12 05:29 UTC, cesar-tecnativa commented
@pedrobaeza could you check please?

2022-07-12 08:42 UTC, pedrobaeza requested changes

2022-07-12 08:42 UTC, pedrobaeza commented on sale_order_line_input/models/sale_order.py
> +    with_company_id = fields.Many2one(
You don't need to rename this field.

2022-07-12 08:42 UTC, pedrobaeza commented on sale_order_line_input/models/sale_order.py
> +        SaleOrder = self.with_context(with_company=self.with_company_id.id).env[
https://www.odoo.com/documentation/15.0/es/developer/howtos/company.html

```suggestion
        SaleOrder = self.with_company(self.force_company_id).env[
```

2022-07-12 08:42 UTC, pedrobaeza commented
/ocabot migration sale_order_line_input

2022-07-25 18:11 UTC, pedrobaeza commented on sale_order_line_input/models/sale_order.py
> +                or self.env.context.get("with_company")
I think you have to look into `allowed_company_ids` context variable.

2022-07-26 22:58 UTC, carlosdauden requested changes

2022-07-26 22:58 UTC, carlosdauden commented on sale_order_line_input/i18n/es.po
> +msgstr "Línea de pedido de venta"
Bad translation

2022-07-26 22:58 UTC, carlosdauden commented on sale_order_line_input/views/sale_order_line_view.xml
> +                    string="Open Sale Order"
Remove this to avoid waste space

2022-09-14 13:44 UTC, victoralmau commented
Could you review it again?

2022-09-15 14:10 UTC, sergio-teruel approved these changes

2022-09-15 14:11 UTC, sergio-teruel commented
@victoralmau Add yourself as contributor

2022-09-15 14:11 UTC, sergio-teruel commented
ping @carlosdauden

2022-09-16 11:09 UTC, carlosdauden commented
Attend this:
https://github.com/OCA/sale-workflow/pull/2114#discussion_r930477479

2022-09-16 13:53 UTC, victoralmau commented
Changes done.

2022-09-17 10:09 UTC, sergio-teruel commented
@pedrobaeza review, if all is ok, Can you merge it?

2022-09-17 13:24 UTC, carlosdauden approved these changes

2022-09-17 13:26 UTC, pedrobaeza commented on sale_order_line_input/models/sale_order.py
> +                or self.env.context.get("with_company")
This is not correct afaik. You should check allowed companies

2022-09-18 22:54 UTC, carlosdauden commented on sale_order_line_input/models/sale_order.py
> +                or self.env.context.get("with_company")
Don't change original line:
```suggestion
                or self.env.context.get("force_company")
```

2022-09-19 06:14 UTC, victoralmau commented on sale_order_line_input/models/sale_order.py
> +                or self.env.context.get("with_company")
Change done.

2022-09-19 07:01 UTC, pedrobaeza approved these changes

2022-09-19 07:01 UTC, pedrobaeza commented
/ocabot merge nobump

2022-09-19 07:17 UTC, merged