[13.0][FIX] Set default account_analytic_account when duplicating a sale order.
OCA/sale-workflow pull request #2124
Opened 2022-07-15 06:06 UTC by cesar-tecnativa

@Tecnativa TT38012

2022-07-15 06:06 UTC, cesar-tecnativa commented
@sergio-teruel please review

2022-07-15 06:13 UTC, pedrobaeza commented
Incorrect commit and PR message. Follow the guidelines (https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message)

- Short on main line
- Module name
- TT on the content, not on the main line

```
[FIX] sale_order_type: Analytic account on copy

When a sale order is duplicated, we set the default account analytic
account that is configured in the order type.

TT38012
```

2022-07-15 06:27 UTC, cesar-tecnativa commented
Done

2022-07-15 06:36 UTC, pedrobaeza requested changes

2022-07-15 06:36 UTC, pedrobaeza commented on sale_order_type/models/sale.py
> +        return super().copy(default)
You should read the type on the defaults, as you don't know if there's any override or default value set on the DB (and respect kw args):

```suggestion
        res = super().copy(default=default)
        sale_type = self.env["sale.order.type"].browse(res.get("type_id", False)) or self.type_id
        if sale_type.analytic_account_id:
            res["analytic_account_id"] = sale_type.analytic_account_id.id
        return res
```

2022-07-15 08:30 UTC, sergio-teruel commented
@cesar-tecnativa Can you add some test to coverage this.?

2022-07-27 21:38 UTC, cesar-tecnativa commented
> @cesar-tecnativa Can you add some test to coverage this.?

done

2022-07-28 07:09 UTC, pedrobaeza commented on sale_order_type/models/sale.py
> +    def copy(self, default=None):
Doing this in the method `copy_data` you avoid an extra write, although you would need to do a browse over ` type_id` ID result if exists.

2022-07-28 07:09 UTC, pedrobaeza commented on sale_order_type/tests/test_sale_order_type.py
> +        """
PEP257 indicates that the docstring should be put this way:

```suggestion
        """Test when duplicating the sale order the account analytic account is set.
        """
```

2022-07-28 07:09 UTC, pedrobaeza commented on sale_order_type/tests/test_sale_order_type.py
> +        self.analytic_account = self.env["account.analytic.account"].create(
You should put these changes in a separate commit with the message:

```
[IMP] sale_order_type: Don't depend on demo data for tests
```

for not mixing unrelated things in the diff.

2022-08-31 06:14 UTC, pedrobaeza commented
@carlosdauden please attend my comments.

2023-04-11 19:28 UTC, pedrobaeza commented
@sergio-teruel can you please do the requested changes?

2024-07-16 08:24 UTC, rousseldenis commented
@sergio-teruel What's the status of this ?

2024-12-22 12:27 UTC, closed without merging