[15.0] [MIG] sale_elaboration: Migration to v15
OCA/sale-workflow pull request #2204
Opened 2022-09-28 10:43 UTC by CarlosRoca13

cc @Tecnativa TT37689

please @carlosdauden @sergio-teruel review this

2022-09-28 15:21 UTC, victoralmau requested changes
Code review OK, some suggestions to reduce code.

2022-09-28 15:21 UTC, victoralmau commented on sale_elaboration/models/product_elaboration.py
> +            args = []
```suggestion
        args = args if args else []
```

2022-09-28 15:21 UTC, victoralmau commented on sale_elaboration/models/product_elaboration.py
> +            limit_rest = limit
```suggestion
        limit_rest = limit - len(recs) if limit else limit
```

2022-09-28 15:21 UTC, victoralmau commented on sale_elaboration/views/sale_elaboration_views.xml
> +                    <group>
```suggestion
                    <widget name="web_ribbon" title="Archived" bg_color="bg-danger" attrs="{'invisible': [('active', '=', True)]}"/>
                    <field name="active" invisible="1"/>
                    <group>
```

2022-09-28 15:21 UTC, victoralmau commented on sale_elaboration/views/sale_elaboration_views.xml
> +                <field name="active" invisible="1" />
```suggestion
```

2022-09-28 15:21 UTC, victoralmau commented on sale_elaboration/tests/test_sale_elaboration.py
> +        cls.order = cls.env["sale.order"].create(so._convert_to_write(so._cache))
```suggestion        
        cls.order = cls._create_sale_order(cls, [(cls.product, 10, cls.elaboration_a)])
        
        def _create_sale_order(self, products_info):
          order_form = Form(self.env["sale.order"])
          order_form.partner_id = self.partner
          for product, qty, elaboration in products_info:
            with order_form.order_line.new() as line_form:
                line_form.product_id = self.product
                line_form.product_uom_qty = qty
                if elaboration:
                   line_form.elaboration_id = elaboration
        return order_form.save()

```

2022-09-28 15:21 UTC, victoralmau commented on sale_elaboration/tests/test_sale_elaboration.py
> +            {"name": "test", "tracking": "none"}
```suggestion
            {"name": "test", "tracking": "none", "list_price": 1000}
```

2022-09-28 15:21 UTC, victoralmau commented on sale_elaboration/tests/test_sale_elaboration.py
> +        self.order = self.env["sale.order"].create(so._convert_to_write(so._cache))
```suggestion
        self.order = self._create_sale_order([(self.product_elaboration_A, 1, False),(self.product_elaboration_B, 1, False)])
```

2022-09-29 07:03 UTC, rousseldenis commented
@victoralmau Shouldn't reviews be done on 14 migration PR and then pushed here ?

2022-09-29 08:19 UTC, victoralmau commented
> @victoralmau Shouldn't reviews be done on 14 migration PR and then pushed here ?

Ok, sorry, I didn't see the v14 migration PR.
@CarlosRoca13, can you apply these changes in v14?

2022-09-29 14:20 UTC, victoralmau reviewed
Code review OK (It is probably better to merge v14 first, and then this one only with the necessary changes with respect to v15).

2022-10-17 07:01 UTC, victoralmau commented
Can you update the commit history? The module is already merged in 14.0.

2022-10-21 06:36 UTC, rousseldenis commented
/ocabot migration sale_elaboration

2022-10-21 06:38 UTC, rousseldenis commented
@CarlosRoca13

2022-10-21 10:21 UTC, sergio-teruel commented
@CarlosRoca13 You have already attended to @victoralmau  comments, right?

2022-10-24 06:31 UTC, CarlosRoca13 commented
All changes done

2022-10-24 06:33 UTC, victoralmau approved these changes
Code review OK

2022-10-24 08:48 UTC, carlosdauden approved these changes

2022-10-24 10:01 UTC, pedrobaeza commented
/ocabot merge nobump

2022-10-24 10:16 UTC, merged