[IMP] sale_order_line_date: update existing moves date_deadline
OCA/sale-workflow pull request #2289
Opened 2022-11-29 14:11 UTC by ferran-S73

Update existing moves `date_deadline` when writing on sol's `commitment_date`. This is useful when the `sale.order` is already confirmed.

2022-11-30 15:55 UTC, hildickethan-S73 commented on sale_order_line_date/models/sale_order_line.py
> +                        moves_to_upd += move
```suggestion
            for move in self.move_ids:
                if move.state not in ["cancel", "done"]:
                    moves_to_upd += move
```

2022-12-01 08:30 UTC, ferran-S73 commented on sale_order_line_date/models/sale_order_line.py
> +                        moves_to_upd += move
done @hildickethan-S73

2022-12-01 08:38 UTC, hildickethan-S73 approved these changes

2022-12-07 15:51 UTC, rousseldenis requested changes
Code review.

Could you add a test ?

2022-12-07 15:51 UTC, rousseldenis commented on sale_order_line_date/models/sale_order_line.py
> +        res = super(SaleOrderLine, self).write(vals)
```suggestion
        res = super().write(vals)
```

2022-12-07 15:51 UTC, rousseldenis commented on sale_order_line_date/models/sale_order_line.py
> +        moves_to_upd = self.env["stock.move"]
```suggestion
        moves_to_upd = set()
```

2022-12-07 15:51 UTC, rousseldenis commented on sale_order_line_date/models/sale_order_line.py
> +                    moves_to_upd += move
```suggestion
                    moves_to_upd.append(move.id)
```

2022-12-07 15:51 UTC, rousseldenis commented on sale_order_line_date/models/sale_order_line.py
> +            moves_to_upd.write({"date_deadline": vals.get("commitment_date")})
```suggestion
            self.env["stock.move"].browse(moves_to_upd).write({"date_deadline": vals.get("commitment_date")})
```

2022-12-12 08:25 UTC, ferran-S73 commented
Hi @rousseldenis changes made and test added

2022-12-13 08:41 UTC, rousseldenis approved these changes
Code review

@AaronHForgeFlow @nikul-serpentcs @SerpentCS Want to have your functional advice here

2022-12-14 05:14 UTC, nikul-serpentcs commented on sale_order_line_date/models/sale_order_line.py
> +        return res
Here we improve code like this.
```
    def write(self, vals):
        res = super().write(vals)
        if "commitment_date" in vals and vals.get('commitment_date', False):
            moves_to_upd = self.move_ids.filtered(lambda m: m.state not in ["cancel", "done"])
            if moves_to_upd:
                moves_to_upd.write(
                    {"date_deadline": vals.get("commitment_date")}
                )
        return res
```

2022-12-14 07:17 UTC, ferran-S73 commented on sale_order_line_date/models/sale_order_line.py
> +        return res
Hi, thanks for the suggestion. We've actually tested code like this and the use of `self.move_ids.filtered()` iterates twice the moves whereas my original code does it once. So I think it's better for performance to leave it as it is.

2022-12-14 12:19 UTC, AaronHForgeFlow approved these changes
LGTM

2023-06-06 08:57 UTC, ferran-S73 commented
@rousseldenis could you please merge this pr

2023-06-13 09:06 UTC, rousseldenis commented on sale_order_line_date/models/sale_order_line.py
> +        return res
I +1 on this

2023-06-13 09:07 UTC, rousseldenis commented
/ocabot merge minor

2023-06-13 09:21 UTC, merged