[16.0][MIG] sale_rental
OCA/sale-workflow pull request #2325
Opened 2023-01-03 13:14 UTC by Murtaza-OSI

2023-01-05 09:33 UTC, chandni299 commented
Hello @Murtaza-OSI , If I am not wrong then we need to migrate the first module `sale_start_end_dates` to 16.0 as it is part of `__manifest__.py` file of module `sale_rental` here

2023-01-26 08:02 UTC, rousseldenis commented
/ocabot migration sale_rental

2023-08-14 10:15 UTC, pedrobaeza commented
This one should be definitively be moved to OCA/vertical-rental on this version.

2023-12-14 13:13 UTC, Kev-Roche requested changes
Hi @Murtaza-OSI do you plan to fix this PR and move it top OCA/vertical-rental like suggested by @pedrobaeza ? 
If no, I can do it.

2023-12-14 13:13 UTC, Kev-Roche commented on sale_rental/tests/test_sale_rental.py
> +        sol = so.order_line
In order to play the onchange
```suggestion
        with so_form.order_line.new() as line:
            line.product_id = self.test_rental_prod
            line.start_date = "2022-01-01"
            line.end_date = "2022-01-10"
            line.rental_qty = 1
            line.product_uom_qty = 10
        so = so_form.save()
        sol = so.order_line
```

2023-12-14 13:13 UTC, Kev-Roche commented on sale_rental/tests/test_sale_rental.py
> +        self.assertEqual(sol.price_subtotal, 60)
```suggestion
        self.assertEqual(sol.price_subtotal, 600)
```

2023-12-14 13:13 UTC, Kev-Roche commented on sale_rental/tests/test_sale_rental.py
> +        so.write({"order_line": [(0, 0, line_vals)]})
The line values are already defined in the upper lines. 
```suggestion
```

2024-02-28 09:00 UTC, coffeinisfun commented
I have made a PR to move this module to OCA/vertical-rental like suggested by @pedrobaeza: https://github.com/OCA/vertical-rental/pull/45

2024-02-28 12:11 UTC, closed without merging