[15.0][MIG] sale_missing_cart_tracking: Migration to version 15.0
OCA/sale-workflow pull request #2339
Opened 2023-01-16 08:06 UTC by pilarvargas-tecnativa

cc @Tecnativa TT39009

2023-01-16 09:02 UTC, chienandalu requested changes
- Review tests.
- Some formal comments:

2023-01-16 09:02 UTC, chienandalu commented on sale_missing_cart_tracking/models/sale_missing_tracking.py
> +                # doc_ids= moves.ids,
Remove commented code

2023-01-16 09:02 UTC, chienandalu commented on sale_missing_cart_tracking/models/sale_missing_tracking.py
> +    #         exceptions
```suggestion
```

2023-01-16 09:02 UTC, chienandalu commented on sale_missing_cart_tracking/models/sale_missing_tracking.py
> +        return result
```suggestion
        return [(x.id, f"{x.partner_id.name} - {x.product_id.display_name}") for x in self]
```

2023-01-16 09:02 UTC, chienandalu commented on sale_missing_cart_tracking/models/sale_missing_tracking.py
> +    #     self.reason_id = self.env.context.get('reason_id')
```suggestion
```

2023-01-16 09:02 UTC, chienandalu commented on sale_missing_cart_tracking/models/sale_missing_tracking_exception.py
> +        return result
```suggestion
        return [(x.id, f"{x.partner_id.name} - {x.product_id.display_name}") for x in self]
```

2023-01-16 09:02 UTC, chienandalu commented on sale_missing_cart_tracking/views/sale_missing_cart_tracking_views.xml
> +                <!--                />-->
```suggestion
```

2023-01-16 09:02 UTC, chienandalu commented on sale_missing_cart_tracking/views/sale_missing_cart_tracking_views.xml
> +                                <!--                                <div t-if="record.tracking_exception_ids">-->
```suggestion
```

2023-01-16 09:02 UTC, chienandalu commented on sale_missing_cart_tracking/views/sale_missing_cart_tracking_views.xml
> +                <!--                 <field name="consumption" type="measure" />-->
```suggestion
```

2023-01-16 10:06 UTC, pilarvargas-tecnativa commented
> * Review tests.
> * Some formal comments:

I have already made the changes and review the tests, thank you :)

2023-01-16 10:41 UTC, chienandalu approved these changes
Looks good. Some small fixes:

2023-01-16 10:41 UTC, chienandalu commented on sale_missing_cart_tracking/tests/test_sale_missing_cart_tracking.py
> +    def _create_sale_order(cls, product):
This can be a regular instance method
```suggestion
    def _create_sale_order(self, product):

2023-01-16 10:41 UTC, chienandalu commented on sale_missing_cart_tracking/tests/test_sale_missing_cart_tracking.py
> +        # import wdb; wdb.set_trace()
```suggestion

2023-01-25 16:09 UTC, rousseldenis commented
/ocabot migration sale_missing_cart_tracking


@pilarvargas-tecnativa As I understand the aim of this in a ecommerce context, maybe, as this does depends on sale module only, a renaming without 'cart' word should be great (as salesman maybe want to track missing sales without website.

2023-01-25 17:41 UTC, sergio-teruel commented on sale_missing_cart_tracking/wizards/sale_missing_cart_tracking_wiz.py
> +        # compute="_compute_missing_tracking_ids",
Remove commented code..

2023-01-26 07:12 UTC, pilarvargas-tecnativa commented
> /ocabot migration sale_missing_cart_tracking
> 
> @pilarvargas-tecnativa As I understand the aim of this in a ecommerce context, maybe, as this does depends on sale module only, a renaming without 'cart' word should be great (as salesman maybe want to track missing sales without website.

Right, I'm going to rename it. Thank you

2023-01-26 08:11 UTC, sergio-teruel approved these changes

2023-02-08 11:00 UTC, sergio-teruel approved these changes

2023-02-08 11:45 UTC, pedrobaeza commented
/ocabot merge nobump

2023-02-08 12:03 UTC, merged