[16.0][MIG] - sale_stock_picking_blocking
OCA/sale-workflow pull request #2366
Opened 2023-02-07 17:08 UTC by sbejaoui

2023-02-07 17:09 UTC, sbejaoui commented
/ocabot migration sale_stock_picking_blocking

2023-02-07 17:10 UTC, sbejaoui commented
#2215

2023-02-08 06:54 UTC, lmignon requested changes

2023-02-08 06:54 UTC, lmignon commented on sale_stock_picking_blocking/models/sale_order.py
> +        res = super()._onchange_partner_id_warning()
@sbejaoui  `delivery_block_id` should become a compted field with `readonly=False`. It is important that no more business logic depends on onchange methods to make sure that the logic is applied even if the creation is done by a call to the create method from within the code.

2023-02-08 16:06 UTC, lmignon approved these changes
LGTM (Code review)

2023-02-08 16:34 UTC, lmignon commented
LGTM (Functional testsà

2023-02-09 09:42 UTC, rousseldenis commented
/ocabot migration sale_stock_picking_blocking

2023-02-09 09:58 UTC, rousseldenis requested changes
Code review

2023-02-09 09:58 UTC, rousseldenis commented on sale_stock_picking_blocking/models/sale_order.py
> +    @api.onchange("partner_id")
```suggestion
    @api.depends("partner_id")
```

2023-02-09 09:58 UTC, rousseldenis commented on sale_stock_picking_blocking/models/sale_order.py
> +            order.write({"delivery_block_id": False})
```suggestion
            orders_to_unblock_ids = set()
            orders_to_unblock = self.filtered(...)
            orders_to_unblock.write({"delivery_block_id": False})
            orders_to_unblock.mapped("order_line").(...)
```

2023-02-09 15:58 UTC, rousseldenis approved these changes
Code review

2023-02-24 13:38 UTC, dreispt commented
/ocabot merge nobump

2023-02-24 13:47 UTC, merged