[15.0][MIG] sale_missing_cart_tracking_tier_validation > sale_missing_tracking_tier_validation: Migration to version 15.0
OCA/sale-workflow pull request #2368
Opened 2023-02-08 08:28 UTC by pilarvargas-tecnativa

cc @Tecnativa TT40150

Pending from:
- [x] #2339 

@sergio-teruel @chienandalu please review :)

2023-02-08 11:05 UTC, sergio-teruel requested changes

2023-02-08 11:05 UTC, sergio-teruel commented on sale_missing_tracking_tier_validation/__manifest__.py
> +    "author": "Open Source Integrators, Odoo Community Association (OCA)",
Change author to Tecnativa

2023-02-08 11:05 UTC, sergio-teruel commented on sale_missing_tracking_tier_validation/models/__init__.py
> +from . import sale_missing_cart_tracking_exception
remove cart

2023-02-08 15:15 UTC, pilarvargas-tecnativa commented
@sergio-teruel changes made, thanks for suggestions :)

2023-03-27 06:36 UTC, pilarvargas-tecnativa commented
@chienandalu can you check this please?

2023-04-19 08:46 UTC, rousseldenis commented
/ocabot migration sale_missing_tracking_tier_validation

2023-04-20 10:39 UTC, pilarvargas-tecnativa commented
@carlosdauden can you take a look?

2024-02-15 16:30 UTC, victoralmau approved these changes
Code review OK

2024-02-15 16:30 UTC, victoralmau commented on sale_missing_tracking_tier_validation/__manifest__.py
> +    "name": "Sale Tier Validation",
Perhaps the name could be more explanatory (although the description already is).

2024-02-15 16:32 UTC, chienandalu reviewed
Would you push again to have a runboat?

2024-02-15 17:01 UTC, pilarvargas-tecnativa commented on sale_missing_tracking_tier_validation/__manifest__.py
> +    "name": "Sale Tier Validation",
thanks :)

2024-02-15 17:08 UTC, pilarvargas-tecnativa commented
> Would you push again to have a runboat?

There it is! :smiley_cat:

2024-02-15 17:11 UTC, chienandalu approved these changes
Tested :+1:

2024-02-15 21:00 UTC, pedrobaeza commented
/ocabot merge nobump

2024-02-15 21:17 UTC, merged