[UPDATE] sale_exception
OCA/sale-workflow pull request #2378
Opened 2023-02-16 17:52 UTC by aliciagaarzo

After testing the migrated module, I’ve found some improvements:

- Description field is noy properly displayed; user needs to scroll to the right to see it.

- Allow to ignore exceptions even if the “is blocking” option is checked

2023-02-17 11:01 UTC, amarcosg approved these changes

2023-02-17 14:05 UTC, rousseldenis requested changes
Minor change. Could you add a test for this ?

2023-02-17 14:05 UTC, rousseldenis commented on sale_exception/wizard/sale_exception_confirm.py
> +        exceptions_blocking = self.exception_ids.filtered(lambda s: s.is_blocking)
```suggestion
        exceptions_blocking = self.exception_ids.filtered("is_blocking")
```

2023-03-27 12:13 UTC, aliciagaarzo commented
Good afternoon @rousseldenis , can you check if the changes are correct?

2023-04-19 09:05 UTC, aliciagaarzo commented
@rousseldenis Have you been able to review the changes?

2023-04-19 12:02 UTC, HugoCordobaLeal approved these changes
LGTM

2023-04-19 12:02 UTC, HugoCordobaLeal commented
@rousseldenis

2023-04-20 07:26 UTC, rousseldenis commented
@aliciagaarzo Could you rebase to allow running runboat and test functionally ?

2023-04-20 08:01 UTC, aliciagaarzo commented
> @aliciagaarzo Could you rebase to allow running runboat and test functionally ?

Done, thanks for the review!

2023-04-21 07:39 UTC, aliciagaarzo commented
@rousseldenis Can you approve the changes after the rebase?

2023-05-03 11:36 UTC, glitchov commented
LGTM code & functional

2023-05-03 18:54 UTC, aliciagaarzo commented
@rousseldenis

2023-05-04 11:32 UTC, rousseldenis commented
/ocabot merge minor

2023-05-04 11:38 UTC, merged