[16.0][MIG] sale delivery split date: Migration to 16.0
OCA/sale-workflow pull request #2404
Opened 2023-03-07 20:57 UTC by kimirondon

2023-03-07 21:39 UTC, kimirondon commented
depending on #2341 and #2403

2023-03-31 12:37 UTC, ajaniszewska-dev commented
to include dependencies and fix build you could add  test-requirements.txt and in it something like:

odoo-addon-<dependency_addon_name> @ git+https://github.com/OCA/<addon_repo>.git@refs/pull/<PR number>/head#subdirectory=setup/<addon_name>

just in separate commit like "[DO NOT MERGE] test-requirements.txt"

2023-07-06 17:15 UTC, kimirondon commented
hello @ajaniszewska-dev ! thanks a lot for the help.

2023-07-11 09:34 UTC, nguyenminhchien requested changes

2023-07-11 09:34 UTC, nguyenminhchien commented on sale_delivery_split_date/models/sale_order_line.py
> +                return (priority, self.commitment_date.date())
@kimirondon 
Hello, my timezone is GMT+7
i create an order having 2 lines:
- 1st line: Delivery date at 07/13/2023 05:00:00
- 2nd line: Delivery date at 07/13/2023 10:00:00
They are in the same date (07/13/2023) but 2 delivery orders are created after confirming the order.
this line `return (priority, self.commitment_date.date())` should take into account the user timezone
![image](https://github.com/OCA/sale-workflow/assets/8724793/4755c7c3-f3fd-453e-9514-fe48232345db)

2023-07-11 09:34 UTC, nguyenminhchien commented on sale_delivery_split_date/models/sale_order_line.py
> +                return (priority, self.commitment_date.date())
we should add an unittest for this case as well.

2023-07-13 03:08 UTC, nguyenminhchien approved these changes
look good as in previous version

2023-07-13 03:08 UTC, nguyenminhchien commented on sale_delivery_split_date/models/sale_order_line.py
> +                return (priority, self.commitment_date.date())
we can add another commit to improve this later.

2023-07-21 16:28 UTC, kimirondon commented
hello @nguyenminhchien !! yes like you said is the same in previous versions, it could be tricky to split by time, if the difference is seconds it will create different pickings.

2023-11-17 10:26 UTC, gurneyalex approved these changes

2023-11-17 10:27 UTC, gurneyalex commented
/ocabot merge nobump

2023-11-17 10:38 UTC, merged

2025-03-12 17:29 UTC, rousseldenis commented
/ocabot migration sale_delivery_split_date