[16.0][MIG] sale_order_product_recommendation: Migration to version 16.0
OCA/sale-workflow pull request #2491
Opened 2023-04-25 03:41 UTC by Yadier-Tecnativa

@Tecnativa TT42432

2023-04-25 07:35 UTC, rousseldenis commented
/ocabot migration sale_order_product_recommendation

2023-05-05 06:37 UTC, pedrobaeza commented
The width of the one2many is not fitting the whole width.

2023-05-05 16:35 UTC, Yadier-Tecnativa commented
> The width of the one2many is not fitting the whole width.

changed

2023-05-05 17:27 UTC, pedrobaeza commented
OK, the CI error is on other module and doesn't seem related to this.

2023-05-13 06:09 UTC, sergio-teruel requested changes

2023-05-13 06:09 UTC, sergio-teruel commented on sale_order_product_recommendation/wizards/sale_order_recommendation.py
> +                ).lst_price
You are breaking the module behavior.
Is you get this field the sale order pricelist is omitted.
Please, use a method to get price from pricelist

You can take a look to unit_price in sale order lines

2023-05-15 21:34 UTC, Yadier-Tecnativa commented
There seems to be an error in the CI with the installation of the sale_partner_selectable_option module.
Is there a way not to run this module especially for this PR?

2023-05-16 16:20 UTC, Yadier-Tecnativa commented
After many attempts to change the installation modules failed in the CI jobs, the error remains the same:
```ERROR: statement cancel due to lock timeout```
It seems something with the database implementation.

2023-06-05 11:29 UTC, sergio-teruel commented
ping @chienandalu

2023-06-05 13:39 UTC, sergio-teruel commented
Ready to be merged!!

2023-06-05 13:43 UTC, chienandalu approved these changes

2023-06-05 13:53 UTC, sergio-teruel commented
ping @juangomezzurita

2023-06-05 14:10 UTC, pedrobaeza commented on .pre-commit-config.yaml
> +  ^sale_automatic_workflow/|
This one should be removed, isn't it?

2023-06-06 07:43 UTC, sergio-teruel commented
Done!! waiting to CI

2023-06-06 11:20 UTC, pedrobaeza commented
/ocabot merge nobump

2023-06-06 11:38 UTC, merged