[FIX] sale_order_type: Fix in _compute_sale_type_id method
OCA/sale-workflow pull request #2594
Opened 2023-07-06 17:46 UTC by mem-adhoc

Ticket 63072

2023-07-06 20:04 UTC, pedrobaeza commented
Please indicate steps to reproduce the problem in a standard installation and a regression test would be interesting.

2023-07-24 08:31 UTC, rousseldenis commented
@mem-adhoc Could you answer @pedrobaeza comments and fix tests ? Thanks

2023-08-09 15:58 UTC, mem-adhoc commented
Hello @pedrobaeza, i'm still working in the pr, is not finished yet !

2023-08-16 17:43 UTC, pedrobaeza requested changes
Changing the computed again to old onchange is not correct. The fix should be done other way.

2023-08-30 08:29 UTC, rousseldenis commented
@mem-adhoc What's the status of this ?

2023-09-27 14:02 UTC, mem-adhoc commented
Hello @pedrobaeza, how are you? I hope you doing fine! 

The change is because the field was causing a conflict when creating an invoice. The type of sale was not set correctly while the invoice did not have a partner or even having one and selecting the different types of sales, it never changed. Even when having a type of sale set for a specific partner, it also caused conflicts if it was added to an invoice with another type of sale configured. 

The behavior of this field should not be a compute, because it should not be constantly calculating. It should have a default value, which would change depending on whether the partner selected has a set type of sale, or is in favor of what the client decides! 

Greetings.

2023-09-27 14:04 UTC, pedrobaeza commented
That's not correct. Computed writable fields are replacing onchanges. You just need to put the corresponding `if` that you consider, but without writing specific steps to reproduce the problem and fixing the tests, this change won't be accepted.

2023-10-17 11:41 UTC, mem-adhoc commented
Hello @pedrobaeza, how are you?

This is the video to show you how the code works normally without any changes. As you will see, not having any partner set works wrong. Having a partner set also works wrong since the type of sale is never shown on the screen. https://drive.google.com/file/d/1zFlI99AGK4lCdeBnPSYzY8kA06kKfbYT/view

If I put the if so that the type of sale is not overwritten if it is already set by default, it still works wrong when there is no partner since it finds the first type of sale that there is https://drive.google.com/file/d/1xbT3_bdvr9ur1OhwmrBmkrLx0Wn_O9za/view

2023-10-21 09:29 UTC, pedrobaeza commented
Well, please start first getting a green CI, as the fail means that not everything is done correctly:

```
 2023-09-04 17:00:13,049 259 ERROR odoo odoo.addons.sale_order_type.tests.test_sale_order_type: FAIL: TestSaleOrderType.test_invoice_without_partner
Traceback (most recent call last):
  File "/__w/sale-workflow/sale-workflow/sale_order_type/tests/test_sale_order_type.py", line 188, in test_invoice_without_partner
    self.assertEqual(invoice.sale_type_id, self.default_sale_type_id)
AssertionError: sale.order.type() != sale.order.type(1,)
```

2023-11-15 19:19 UTC, mem-adhoc commented
Hello @pedrobaeza, how are you? 

I already have the green CI from the tests. I corrected a unit test according to the new logic of this field.

Greetings.

2023-11-15 19:26 UTC, pedrobaeza commented
Sorry, your changes are not correct. You should keep the computed nature of the field. If there's a corner case, model it inside the compute method.

2025-02-21 14:05 UTC, rousseldenis commented
Closing this as very old and user is not still active. Please feel free to reopen it if needed.

2025-02-21 14:05 UTC, closed without merging