[15.0][MIG] pricelist_cache
OCA/sale-workflow pull request #2601
Opened 2023-07-12 18:44 UTC by juanpgarza

Standard migration

2023-07-24 08:19 UTC, rousseldenis commented
/ocabot migration pricelist_cache

2023-07-24 08:23 UTC, rousseldenis requested changes
@juanpgarza Could you fix tests ?

2023-07-24 11:46 UTC, juanpgarza commented
hi @rousseldenis 
I would but I don't know how. 
Could you help me a little or point me to a tutorial or webinar on the subject?

2024-04-08 18:17 UTC, valentincastravete commented
Hi @juanpgarza 
Could you re-run the tests so I can lend you a hand please?
Their logs have been deleted.
Thanks!

2024-04-16 19:57 UTC, valentincastravete commented
> Hi @juanpgarza Could you re-run the tests so I can lend you a hand please? Their logs have been deleted. Thanks!

Hi @rousseldenis Could you re-run the tests please? Thanks!

2024-04-17 06:57 UTC, rousseldenis commented
/ocabot rebase

2024-04-17 10:59 UTC, valentincastravete commented on pricelist_cache/models/product_pricelist.py
> +        compute="_compute_is_pricelist_cache_available", store=True
```suggestion
        compute="_compute_is_pricelist_cache_available",
        store=True,
        recursive=True,
```
_/opt/odoo/odoo/fields.py:746: UserWarning: Field product.pricelist.is_pricelist_cache_available should be declared with recursive=True_

2024-04-17 12:31 UTC, valentincastravete commented
Hi @juanpgarza 
Could you please update your repository with the last updates on the pricelist_cache module on v14 please?
To see it changes anything related to the tests.
Thanks!

2024-04-19 21:06 UTC, valentincastravete requested changes

2024-04-19 21:06 UTC, valentincastravete commented on pricelist_cache/tests/common.py
> +}
```suggestion
LIST_PRICES_MAPPING = {
    "pricelist_cache.list0": [
        {"id": 17, "price": 100.0},
        {"id": 18, "price": 15.8},
        {"id": 19, "price": 100.0},
        {"id": 20, "price": 47.0},
    ],
    "pricelist_cache.list1": [
        {"id": 17, "price": 75.0},
        {"id": 18, "price": 15.8},
        {"id": 19, "price": 100.0},
        {"id": 20, "price": 47.0},
    ],
    "pricelist_cache.list2": [
        {"id": 17, "price": 50.0},
        {"id": 18, "price": 15.8},
        {"id": 19, "price": 100.0},
        {"id": 20, "price": 47.0},
    ],
    "pricelist_cache.list3": [
        {"id": 17, "price": 25.0},
        {"id": 18, "price": 79.0},
        {"id": 19, "price": 100.0},
        {"id": 20, "price": 47.0},
    ],
    "pricelist_cache.list4": [
        {"id": 17, "price": 15.0},
        {"id": 18, "price": 50.0},
        {"id": 19, "price": 100.0},
        {"id": 20, "price": 47.0},
    ],
    "pricelist_cache.list5": [
        {"id": 17, "price": 45.0},
        {"id": 18, "price": 35.8},
        {"id": 19, "price": 120.0},
        {"id": 20, "price": 67.0},
    ],
}
```

2024-04-19 21:06 UTC, valentincastravete commented on pricelist_cache/tests/common.py
> +}
Hi @juanpgarza 
I've found the solution to the tests.
It's caused by the odoo/addons/product module demo data change of a product:

The one used here:
https://github.com/juanpgarza/sale-workflow/blob/15.0-mig-pricelist_cache/pricelist_cache/data/demo.xml#L121
With the ID 18;
![image](https://github.com/OCA/sale-workflow/assets/58530982/e1726435-bf52-4ec3-8f47-ed2e28ce4428)


V14.0:
https://github.com/odoo/odoo/blob/14.0/addons/product/data/product_demo.xml#L285
Price: 79.0

V15.0:
https://github.com/odoo/odoo/blob/15.0/addons/product/data/product_demo.xml#L285
Price: 15.8


After updating the price, the tests passes.

Regards

2024-04-23 11:21 UTC, valentincastravete commented on pricelist_cache/tests/common.py
> +}
@rousseldenis Could you apply this suggestion for him please? So it can be merged

2024-05-15 09:26 UTC, valentincastravete commented
@rousseldenis Hi, my PR has been merged, this can be closed.

2024-05-16 06:34 UTC, closed without merging