v9 Migration of sale_cancel_reason
OCA/sale-workflow pull request #261
Opened 2016-01-29 15:03 UTC by JayVora-SerpentCS

2016-01-29 15:07 UTC, pedrobaeza commented
Can you please squash the commits a bit?

2016-01-29 15:07 UTC, pedrobaeza commented on sale_cancel_reason/__openerp__.py
>  Sale Cancel Reason
Put description in a README.rst according conventions (https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst)

2016-01-29 15:08 UTC, pedrobaeza commented on sale_cancel_reason/views/sale_view.xml
>      <data noupdate="0">
You can remove this tag as this is the default value

2016-01-29 15:08 UTC, pedrobaeza commented on sale_cancel_reason/wizard/cancel_reason_view.xml
>      <data noupdate="0">
You can remove it

2016-01-29 15:24 UTC, tafaRU commented on sale_cancel_reason/__openerp__.py
> +            ', Serpent Consulting Services Pvt. Ltd.',
Please move it to Contributors section, see https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst as reference.

2016-01-29 15:25 UTC, tafaRU commented on sale_cancel_reason/__openerp__.py
> +    'images': [],
Please remove empty key

2016-01-29 15:25 UTC, tafaRU commented on sale_cancel_reason/__openerp__.py
> +    'demo': [],
Same as above

2016-01-29 15:27 UTC, pedrobaeza commented on sale_cancel_reason/__openerp__.py
> +            ', Serpent Consulting Services Pvt. Ltd.',
In this case, it's correct to be added here, as there's no contributor key on the manifest, and also contributors can expand more the module than the original author, but without extra comma (there are 2).

2016-01-29 15:30 UTC, tafaRU commented
Please also have a look at https://travis-ci.org/OCA/sale-workflow/builds/105690296 errors.
By the way, thank you for your contrib!

2016-01-29 15:32 UTC, tafaRU commented on sale_cancel_reason/__openerp__.py
> +            ', Serpent Consulting Services Pvt. Ltd.',
Okay. Well, good to know.

2016-07-29 07:31 UTC, JayVora-SerpentCS commented
Please check.

2016-07-29 08:35 UTC, pedrobaeza commented
You must import the commit history from the migration moment following this guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0 and squash commits to only relevant ones.

2016-07-29 15:08 UTC, JayVora-SerpentCS commented
Sure, will do! Sounds pretty good set of notes (y)

2016-08-04 06:15 UTC, atchuthan commented on sale_cancel_reason/README.rst
> +* You can cofigure cancel reason from Sale -> Configuration -> Sale Order Cancel Reason.
n/cofigure/configure

2016-08-04 06:18 UTC, atchuthan commented on sale_cancel_reason/data/sale_order_cancel_reason.xml
> +<data noupdate="1">
sorry if it seems like a silly question.  Does it not require <odoo> tag in 9.0?

2016-08-04 06:21 UTC, pedrobaeza commented on sale_cancel_reason/data/sale_order_cancel_reason.xml
> +<data noupdate="1">
You have to put <odoo>, not <data>.

2016-08-04 07:03 UTC, atchuthan commented
code reviewed :+1: 
few minor changes and rebase commits from 8.0 as per @pedrobaeza request

2016-08-04 07:09 UTC, pedrobaeza commented on sale_cancel_reason/wizard/cancel_reason_view.xml
> +<data noupdate="0">
`<odoo>`, not `<data>`

2016-08-04 07:09 UTC, pedrobaeza commented on sale_cancel_reason/views/sale_view.xml
> +<data noupdate="0">
`<odoo>`

2016-10-12 19:49 UTC, StefanRijnhart commented on sale_cancel_reason/models/sale.py
> -        ondelete="restrict")
By removing the ondelete behaviour the default 'set null' will apply. Reasons that were applied to sale orders can be removed, leaving the value empty. Is that what you want?

2016-10-12 19:54 UTC, StefanRijnhart commented on sale_cancel_reason/wizard/cancel_reason_view.xml
> +<data noupdate="0">
@JayVora-SerpentCS would you be able to fix this misunderstanding? Like @pedrobaeza says, the *data* tag is redundant in 9.0, so please replace with the *odoo* tag.

2016-10-12 19:55 UTC, StefanRijnhart commented
@JayVora-SerpentCS should be very easy to have this in a mergeable state, if you have a couple of minute. Nice description page!

2016-10-28 00:56 UTC, pedrobaeza commented
Any update of this?

2016-11-11 12:36 UTC, JayVora-SerpentCS commented
Will fins some tome and push

2016-12-24 18:15 UTC, pedrobaeza commented
Are you going to finally work on this?

2016-12-26 14:14 UTC, JayVora-SerpentCS commented
Sorry, lost it. doing in this week for sure!

2016-12-31 09:52 UTC, JayVora-SerpentCS commented on sale_cancel_reason/models/sale.py
> -        ondelete="restrict")
surely

2016-12-31 10:25 UTC, JayVora-SerpentCS commented
You may proceed please.

2017-01-10 14:55 UTC, JayVora-SerpentCS commented
@pedrobaeza I am unable to see what fails on runbot. Can you help please?

2017-01-10 18:19 UTC, StefanRijnhart commented
@JayVora-SerpentCS I think it's the warnings raised by sale_rental. Don't worry about it.

2017-01-10 18:20 UTC, StefanRijnhart commented on sale_cancel_reason/models/sale.py
> -        ondelete="restrict")
More common is not to allow this, but to allow reasons to be set to inactive so that they cannot be assigned anymore.

2017-01-11 13:37 UTC, JayVora-SerpentCS commented on sale_cancel_reason/models/sale.py
> -        ondelete="restrict")
Added an active field to manage this.
Thanks.

2017-01-17 06:28 UTC, JayVora-SerpentCS commented
Kindly check.

2017-01-17 07:51 UTC, pedrobaeza commented
Runbots errors are in fact warnings from other module (sale_rental):
```
2017-01-11 13:49:54,128 216 WARNING openerp_test openerp.models: method product.product._check_rental: @constrains parameter 'must_have_dates' is not writeable
2017-01-11 13:49:54,128 216 WARNING openerp_test openerp.models: method product.product._check_rental: @constrains parameter 'type' is not writeable
2017-01-11 13:49:54,128 216 WARNING openerp_test openerp.models: method product.product._check_rental: @constrains parameter 'uom_id' is not writeable
```

2017-03-18 16:43 UTC, pedrobaeza commented on sale_cancel_reason/README.rst
> +Sale Cancel Reason
Put the same lines above

2017-03-18 16:47 UTC, pedrobaeza requested changes
Some tests would be welcome.

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/README.rst
> +
Don't put this extra line

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/README.rst
> +
Remove extra line and replace `*` by `#.` for numbered list.

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/167/8.0
s/8.0/9.0

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/README.rst
> +For further information, please visit:
Remove this paragraph

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/README.rst
> +.. image:: http://odoo-community.org/logo.png
s/http/https in both places

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/__openerp__.py
> +            'Serpent Consulting Services Pvt. Ltd.',
Fix indentation

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/data/sale_order_cancel_reason.xml
> +</odoo>
Line at the end

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/models/sale.py
> +        ondelete='restrict')
Next time, don't make these stylistic changes that increases diffs.

2017-03-18 16:47 UTC, pedrobaeza commented on sale_cancel_reason/wizard/__init__.py
> +#    Copyright 2016 Serpent Consulting Services Pvt. Ltd.
Don't add your copyright on non touched files (and more if they are `__init__.py` files.

2017-03-30 14:38 UTC, JayVora-SerpentCS commented
Will do the changes asap.

2017-04-24 13:08 UTC, JayVora-SerpentCS commented on sale_cancel_reason/data/sale_order_cancel_reason.xml
> +</odoo>
This is done, I wonder why the diff shows it open.

2017-04-25 08:09 UTC, LoisRForgeFlow reviewed
Thanks for the work! Some comments in line.

2017-04-25 08:09 UTC, LoisRForgeFlow commented on sale_cancel_reason/README.rst
> + No external library is used.
I think you can remove unneeded sections. Also this is displayed as a quotation due to the initial space in the line.

2017-04-25 08:09 UTC, LoisRForgeFlow commented on sale_cancel_reason/README.rst
> +*#. You can configure cancel reason from Sale -> Configuration -> Sale Order Cancel Reason.
remove initial asterisks, this is not going to be displayed well.

2017-04-25 08:09 UTC, LoisRForgeFlow commented on sale_cancel_reason/__openerp__.py
> +    'complexity': 'normal',
This can be removed I think

2017-04-25 08:09 UTC, lreficent commented on sale_cancel_reason/__openerp__.py
> +    'test': ['test/sale_order_cancel.yml'],
Can you move the tests to python?

2017-04-25 08:09 UTC, lreficent commented on sale_cancel_reason/data/sale_order_cancel_reason.xml
> -    <data noupdate="1">
Why did you remove the original `noupdate="1"`?

2017-04-25 08:09 UTC, lreficent commented on sale_cancel_reason/static/description/index.html
> +</section>
Final extra line

2017-04-25 08:09 UTC, lreficent commented on sale_cancel_reason/static/description/index.html
> +                    1) Sale Order Configuretion.
Configuretion - > Configuration

2017-04-25 09:46 UTC, JayVora-SerpentCS commented on sale_cancel_reason/data/sale_order_cancel_reason.xml
> -    <data noupdate="1">
Accidental due to removal of <data>, its back now.

2017-05-09 07:21 UTC, JayVora-SerpentCS commented on sale_cancel_reason/__openerp__.py
> +    'test': ['test/sale_order_cancel.yml'],
Sure

2017-05-10 06:14 UTC, darshan-serpent commented on sale_cancel_reason/__openerp__.py
> +    'auto_install': False,
not necessary, and can you also please add OCA icon in static/description

2017-05-11 07:09 UTC, JayVora-SerpentCS commented on sale_cancel_reason/__openerp__.py
> +    'auto_install': False,
Its there -https://github.com/JayVora-SerpentCS/sale-workflow/blob/9.0/sale_cancel_reason/static/description/icon.png

2017-09-04 09:57 UTC, sudhir-serpentcs commented
@StefanRijnhart @lreficent @pedrobaeza Please review and provide feedback if any.

2017-09-05 10:57 UTC, LoisRForgeFlow approved these changes
Tested on runbot :+1:

2017-11-13 13:32 UTC, StefanRijnhart approved these changes

2017-11-13 13:39 UTC, serpentcs-dev1 approved these changes
Code review LGTM :+1:

2017-11-22 17:33 UTC, pedrobaeza approved these changes

2017-11-22 17:34 UTC, merged