16.0 mig sale order warn message
OCA/sale-workflow pull request #2610
Opened 2023-07-20 05:44 UTC by aiendry-aktivsoftware

### Standard migration to version 16.0

2023-07-20 08:34 UTC, rousseldenis commented
/ocabot migration sale_order_warn_message

2023-07-20 08:45 UTC, rousseldenis requested changes

2023-07-20 08:45 UTC, rousseldenis commented on sale_order_warn_message/readme/DESCRIPTION.rst
> +This module add a warning popup on sale to ensure warning is populated
```suggestion
This module adds a warning popup on sale to ensure warning is populated
```

2023-07-20 08:45 UTC, rousseldenis commented on sale_order_warn_message/readme/DESCRIPTION.rst
> +no only when partner is changed.
```suggestion
not only when partner is changed.
```

2023-07-20 08:45 UTC, rousseldenis commented on sale_order_warn_message/views/sale_order.xml
> +                        &amp;nbsp;
Missing a space here

![image](https://github.com/OCA/sale-workflow/assets/19529533/7da81e37-fbd7-4f1a-a209-eaec35010c90)

2023-07-20 08:45 UTC, rousseldenis commented on sale_order_warn_message/readme/DESCRIPTION.rst
> +no only when partner is changed.
The description should be enhanced as it is not a popup but a permanent alert warning on sale order form.

An image of the form should be great too (optional).

2023-07-20 08:45 UTC, rousseldenis commented
@aiendry-aktivsoftware Don't forget that a meaningful PR title will help reviewers. Thanks

2023-07-20 09:26 UTC, dhara-wibtec commented
@rousseldenis , I've made the changes you requested for please review for the same.
Thank You!

2023-08-30 07:48 UTC, rousseldenis approved these changes
Code review

2023-10-30 16:10 UTC, HaraldPanten commented
Hi @aiendry-aktivsoftware could you rebase, please? THX

2023-11-02 16:45 UTC, rousseldenis commented
/ocabot rebase

2023-11-02 16:46 UTC, rousseldenis commented
@HaraldPanten Done

2023-11-03 12:53 UTC, HaraldPanten commented
Closing as it has been superseded

2023-11-03 12:53 UTC, closed without merging