[14.0][ADD] sale_stock_prebook: Add process to prebook a sale order's stock
OCA/sale-workflow pull request #2624
Opened 2023-07-28 13:29 UTC by mt-software-de

before confirming it

2023-07-28 13:34 UTC, mt-software-de commented
cc @jbaudoux

2023-07-28 14:07 UTC, rousseldenis commented
@mt-software-de What's the difference with stock_reserve_sale ? 

https://github.com/OCA/stock-logistics-warehouse/pull/1788

2023-07-29 05:09 UTC, mt-software-de commented
> @mt-software-de What's the difference with stock_reserve_sale ? 
> 
> https://github.com/OCA/stock-logistics-warehouse/pull/1788

Please ready the comment of @jbaudoux https://github.com/OCA/stock-logistics-warehouse/pull/1696#issuecom 
This explains it very well.

2023-07-30 08:55 UTC, jbaudoux commented on sale_stock_prebook/README.rst
> +* MT Software
Can you keep original authors of the initial version:
* Camptocamp
* BCIM

2023-07-30 08:56 UTC, jbaudoux commented on sale_stock_prebook/__manifest__.py
> +    "author": "MT Software, Odoo Community Association (OCA)",
```suggestion
    "author": "MT Software, Camptocamp, BCIM, Odoo Community Association (OCA)",
```

2023-10-30 11:17 UTC, mt-software-de commented
https://github.com/OCA/wms/pull/769 is needed for this PR.

2023-10-30 11:31 UTC, jbaudoux approved these changes
LGTM

2023-10-30 11:31 UTC, jbaudoux commented
> [OCA/wms#769](https://github.com/OCA/wms/pull/769) is needed for this PR.

Can you update the description with this?

2023-12-02 02:30 UTC, rafaelbn approved these changes
Functionally tested 👍🏼 

In my opinion README with the USAGE section should be improved with all how to / step by step. In other case, less reviewer, less user adopting it. 😄 ❤️

2024-06-02 11:12 UTC, mt-software-de commented
This one is now ready to merge, i removed the dependency to stock_helper and included the very specific logic to stop the proc run, within the module itself.

2024-11-25 09:23 UTC, lmignon requested changes
It's possible to process the picking generated for the reservation. It should not be possible to set quantity done on the move line nor to validate the picking.

2024-11-25 09:30 UTC, jbaudoux commented
> It's possible to process the picking generated for the reservation. It should not be possible to set quantity done on the move line nor to validate the picking.

This line https://github.com/OCA/sale-workflow/pull/2624/files#diff-2a79dc3628d7cbd98f204791750fadc712f3e43c11341eabb2c722c7157eb258R12 should prevent it. How come you made the move ready ?

2025-02-03 10:15 UTC, rousseldenis commented
@mt-software-de @jbaudoux What's ths status of this ?

2025-02-03 10:54 UTC, mt-software-de commented
> @mt-software-de @jbaudoux What's ths status of this ?

Sorry i was not working on this. 
I still need to check why the test are failing. On my dev env they are green.

2025-02-05 19:42 UTC, mt-software-de commented
> @mt-software-de @jbaudoux What's ths status of this ?

I found the error. 
Its again a module which changes the default odoo behavior. `sale_cancel_confirm`.
I changed the github test flow. 
https://github.com/OCA/sale-workflow/pull/2624/commits/a78ff0079b84ae57e78d3c28f6c11f7bd13ea826

Besides that this one is ready to merge. 
This is already quite sometime in production

2025-02-05 19:43 UTC, mt-software-de commented
> > It's possible to process the picking generated for the reservation. It should not be possible to set quantity done on the move line nor to validate the picking.
> 
> This line https://github.com/OCA/sale-workflow/pull/2624/files#diff-2a79dc3628d7cbd98f204791750fadc712f3e43c11341eabb2c722c7157eb258R12 should prevent it. How come you made the move ready ?

ping @lmignon

2025-02-06 16:39 UTC, lmignon approved these changes

2025-02-06 16:41 UTC, lmignon commented
I've just made a request for a new repo to group together the addons relating to stock pre-booking. see https://github.com/OCA/repo-maintainer-conf/pull/73

2025-02-07 09:41 UTC, mt-software-de commented
@lmignon @yostashiro i added your suggestions.

@lmignon i added a separate commit, with your changes.

2025-02-21 14:15 UTC, rousseldenis approved these changes
Code review

2025-02-21 14:16 UTC, rousseldenis commented
@mt-software-de Ready ?

2025-02-21 14:37 UTC, mt-software-de commented
> @mt-software-de Ready ?

Yes but should we wait for the new repo?

2025-03-04 14:33 UTC, mt-software-de commented
Replaced by https://github.com/OCA/sale-prebook/pull/1

2025-03-04 14:33 UTC, closed without merging