[MIG][16.0] sale product country restriction
OCA/sale-workflow pull request #2658
Opened 2023-08-28 13:47 UTC by xavier-bouquiaux

Migration of this PR https://github.com/OCA/sale-workflow/pull/752

2023-08-29 06:18 UTC, acsonefho requested changes

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order.py
> +        return _("The country of the partner %s must be set") % partner
I think the render of the message will be `A country restriction of the partner res.partner,xxx must be set`.
Should be something like: `_("A country restriction of the partner %s must be set") % partner.display_name` ?

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order.py
> +        return _("A country restriction of the partner %s must be set") % partner
Same here

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order.py
> +        if self.env.user.company_id.enable_sale_country_restriction:
Should be `self.company_id.enable_sale_country_restriction` ?

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order.py
> +        return super(SaleOrder, self).action_confirm()
Please use python 3 syntax `return super().action_confirm()`

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order.py
> +        if not self.env.user.company_id.enable_sale_country_restriction:
Not correct.
```
company = self.company_id or self.env.company
if company.enable_sale_country_restriction:
```

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order.py
> +        if not self.env.user.company_id.enable_sale_country_restriction:
Same here

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order_line.py
> +        if not self.env.company.enable_sale_country_restriction:
Same here (almost correct, you should first use the company of the SO and if not set, the `self.env.company` is correct)

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/tests/common.py
> +        super(SaleCountryRestrictionCommon, self).setUp()
Python 3 syntax

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/tests/test_country_restriction.py
> +                "order_id": self.sale_order.id,
IMO you should use the new way with `Form(...)`

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/tests/test_country_restriction.py
> +            res = line._onchange_product_country_restriction()
And then you can remove that manually call to onchange

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/tests/test_country_restriction.py
> +            vals = line._convert_to_write(line._cache)
And this too

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/tests/test_country_restriction.py
> +        line = self.line_obj.new(
Same changes here.
Maybe you can create a function to avoid duplicates?

2023-08-29 06:18 UTC, acsonefho commented on sale_product_country_restriction/views/res_config_settings_view.xml
> +    <record id="view_sales_config" model="ir.ui.view">
Missing icon to let the user know that the settings is company dependent.

2023-08-29 14:19 UTC, rousseldenis commented
/ocabot migration sale_product_country_restriction

2023-08-29 14:20 UTC, rousseldenis commented
@xavier-bouquiaux Could you include link to the open dependency PR in this description ? You can also include it in test-requirements.txt for tests running and runboat for functional review. Thanks.

https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

2023-08-30 09:37 UTC, acsonefho requested changes

2023-08-30 09:37 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order.py
> +        if self.env.company.enable_sale_country_restriction:
I think you should first use the company set on the current sale (but self could be multi-recordset) instead of the main current company.
```
for rec in self:
    if rec.company_id.enable_sale_country_restriction:
        rec.check_country_restriction()
```

2023-08-30 09:37 UTC, acsonefho commented on sale_product_country_restriction/models/sale_order.py
> +        if not self.env.company.enable_sale_country_restriction:
Same here: you should use the company of the SO first (as it's `onchange`, it could be empty).

2023-08-30 13:43 UTC, acsonefho approved these changes

2025-06-01 12:33 UTC, closed without merging