[16.0][MIG] sale_order_product_assortment: Migration to version 16.0
OCA/sale-workflow pull request #2712
Opened 2023-10-06 12:34 UTC by carolinafernandez-tecnativa

- Standard migration to v16
- Add new field allowed_product_tmpl_ids as in v16 on sales orders shows product_template_id 
- Change Setup to SetupClass tests
- Add test for new field allowed_product_tmpl_ids
- Supersedes https://github.com/OCA/sale-workflow/pull/2356 due to inactivity/changes requested not attended

@Tecnativa

TT44355

@pedrobaeza @carlosdauden

2023-10-21 10:38 UTC, pedrobaeza commented
Please respect the commit history of the other PR, and just add on top your changes.

2023-11-14 13:50 UTC, carolinafernandez-tecnativa commented
> Please respect the commit history of the other PR, and just add on top your changes.

Could you please check it now? Thanks :)

2023-11-25 09:23 UTC, pedrobaeza commented
/ocabot migration sale_order_product_assortment

2023-11-25 09:23 UTC, pedrobaeza requested changes
The old migration commit is still not attributed to the previous contributor.

2023-11-25 09:23 UTC, pedrobaeza commented on sale_order_product_assortment/__manifest__.py
> +        "web_domain_field",
Don't use this one, but create a binary field and use it as the source for the domain.

2024-01-16 14:05 UTC, yvaucher commented
After the following commit:
https://github.com/OCA/product-attribute/commit/ac010741b1c8214c24bbcf7504242a263a36fe78

The Sale order view becomes really slow.

Plus, if we don't set an assortment to a customer it doesn't allow to select a product anymore on the sale order line.

2024-05-15 16:32 UTC, carolinafernandez-tecnativa commented
ping @pedrobaeza

2024-05-17 09:02 UTC, pedrobaeza commented
@carolinafernandez-tecnativa please check the comments from @yvaucher

2024-07-08 16:59 UTC, pedrobaeza commented
@carolinafernandez-tecnativa please redo the migration from current v15, as this one is not valid due to the changes that makes it very slow.

2024-07-09 13:55 UTC, carolinafernandez-tecnativa commented
> @carolinafernandez-tecnativa please redo the migration from current v15, as this one is not valid due to the changes that makes it very slow.

WIP, We need to merge this to redo.
https://github.com/OCA/product-attribute/pull/1682

2024-07-11 09:18 UTC, pedrobaeza commented
Please redo the migration from scratch from current 15.0, as I see old or non optimized stuff (for example, there's no `allowed_product_tmpl_ids` in that branch) and a mix with the migration attempt that only confuses more the diff review.

2024-07-11 14:51 UTC, closed without merging