[15.0][MIG] sale_order_secondary_unit: Add migration script to adapt secod uom to variants
OCA/sale-workflow pull request #2732
Opened 2023-10-20 12:09 UTC by sergio-teruel

cc @Tecnativa TT45597

ping @carlosdauden @CarlosRoca13

2023-10-20 12:23 UTC, carlosdauden approved these changes

2023-10-31 11:29 UTC, CarlosRoca13 approved these changes

2023-10-31 11:39 UTC, pedrobaeza requested changes

2023-10-31 11:39 UTC, pedrobaeza commented on sale_order_secondary_unit/migrations/15.0.2.0.0/post-migration.py
> +    templates = env["product.template"].search([("sale_secondary_uom_id", "!=", False)])
Can you please do this in SQL?
```
UPDATE product_product pp
SET sale_secondary_uom_id = pt.sale_secondary_uom_id
FROM product_template pt
WHERE pt.id = pp.product_tmpl_id
AND pt.sale_secondary_uom_id IS NOT NULL
```

2023-10-31 14:58 UTC, pedrobaeza approved these changes

2023-10-31 14:58 UTC, pedrobaeza commented
/ocabot merge nobump

2023-10-31 15:01 UTC, sergio-teruel commented
Done!!

2023-10-31 15:09 UTC, pedrobaeza commented
/ocabot merge nobump

2023-10-31 15:19 UTC, merged