16.0 mig sale restricted qty
OCA/sale-workflow pull request #2757
Opened 2023-10-31 14:32 UTC by sbiosca-s73

Migration module sale_restricted_qty to version 16.0

2023-11-07 11:37 UTC, rousseldenis commented
/ocabot migration sale_restricted_qty

2023-11-07 11:41 UTC, rousseldenis requested changes

2023-11-07 11:41 UTC, rousseldenis commented on sale_restricted_qty/models/sale.py
> +                % {"name": line.product_id.name, "qty": line.sale_min_qty}
You can use parameters of translation function to do that:
` _("Product %(name)s: Min Quantity %(qty)s.", name=line.product_id.name, qty=line.sale_min_qty)`

2023-11-07 11:41 UTC, rousseldenis commented on sale_restricted_qty/models/sale.py
> +                % {"name": line.product_id.name, "qty": line.sale_min_qty}
Same for others

2023-11-07 12:55 UTC, sbiosca-s73 commented
@rousseldenis changes done

2024-04-23 09:51 UTC, rafaelbn commented
Please @sbiosca-s73 you should review previously PRs before opening a new one 😄 

Please review https://github.com/OCA/sale-workflow/pull/2708

2024-11-29 17:21 UTC, sergiocorato commented
Please close this as the module is already migrated see https://github.com/OCA/sale-workflow/pull/2708

2025-05-09 06:51 UTC, closed without merging