[16.0][FIX] sell_only_by_packaging: When selecting a product_packaging_id, product_packaging_qty should not be a float value (triggering a ValidationError)
OCA/sale-workflow pull request #2808
Opened 2023-11-27 11:02 UTC by Ricardoalso

The actual state of the code (AS-IS) triggers a Validation error for each product_packaging_id selected if the number(s) before the decimals doesn't match
```
float_compare(
      line.product_packaging_qty,
      int(line.product_packaging_qty),
      precision_digits=2,
)
```
This means that the user can possibly face one ValidationError pop-up window for each line where he selects a product_packaging_id if the conditions are met.

ValidationError triggered by following check

```
@api.constrains(
        "product_id", "product_packaging_id", "product_packaging_qty", "product_uom_qty"
    )
    def _check_product_packaging_sell_only_by_packaging(self):
        for line in self:
            if not line.product_id.sell_only_by_packaging or not line.product_uom_qty:
                continue

            if (
                not line.product_packaging_id
                or float_compare(
                    line.product_packaging_qty,
                    int(line.product_packaging_qty),
                    precision_digits=2,
                )
                != 0
            ):
                raise ValidationError(
                    _(
                        "Product %s can only be sold with a packaging and a "
                        "packaging quantity."
                    )
                    % line.product_id.name
                )
```

This PR (TO-BE) implements a ceil of product_packaging_qty whenever product_packaging_id changes in order to avoid the ValidationError pop-up when choosing a product_packaging_id

2023-11-27 13:30 UTC, StephaneMangin commented
This kind of change requires a test. An maybe a review of the workflow in this particular case.

2023-11-27 14:30 UTC, santostelmo commented
The OCA module will be so happy with a small test 🙋to assert this behavior !

2023-11-27 14:56 UTC, santostelmo approved these changes

2023-11-27 14:57 UTC, santostelmo approved these changes

2024-02-19 07:23 UTC, simahawk requested changes
Wouldn't be better to propose a fix to odoo?
However, a use case explanation is needed.
One more thing: pls, do not include the odoo version in the commmit msg and leave the long explanation to its description.

2024-04-05 08:57 UTC, Ricardoalso commented
> Wouldn't be better to propose a fix to odoo? However, a use case explanation is needed. One more thing: pls, do not include the odoo version in the commmit msg and leave the long explanation to its description.

Thanks for your comment @simahawk 

I added a use case explanation  and amended the commit as requested and created this PR in odoo repo https://github.com/odoo/odoo/pull/160636

2025-06-05 12:13 UTC, santostelmo commented
> > Wouldn't be better to propose a fix to odoo? However, a use case explanation is needed. One more thing: pls, do not include the odoo version in the commmit msg and leave the long explanation to its description.
> 
> Thanks for your comment @simahawk
> 
> I added a use case explanation and amended the commit as requested. Furthermore, I created this PR in odoo repo [odoo/odoo#160636](https://github.com/odoo/odoo/pull/160636)

@Ricardoalso OPW in odoo was not accepted. 
Can we move this PR to ready ?

2025-06-05 12:18 UTC, Ricardoalso commented
> > > Wouldn't be better to propose a fix to odoo? However, a use case explanation is needed. One more thing: pls, do not include the odoo version in the commmit msg and leave the long explanation to its description.
> > 
> > 
> > Thanks for your comment @simahawk
> > I added a use case explanation and amended the commit as requested. Furthermore, I created this PR in odoo repo [odoo/odoo#160636](https://github.com/odoo/odoo/pull/160636)
> 
> @Ricardoalso OPW in odoo was not accepted. Can we move this PR to ready ?

Yes we can, thanks for the follow up @santostelmo

2026-03-27 10:13 UTC, rousseldenis commented
@Ricardoalso @simahawk What's the status of this as very old ? Can we close ?

I'm not sure about this change. Isn't it a problem of uom's configurations?

2026-04-07 07:42 UTC, Ricardoalso commented
Closing 

https://github.com/odoo/odoo/pull/160636#issuecomment-2674252695

> packagings are not intended to be sold in non-whole number increments (e.g. it doesn't make sense to sell 1/2 of a pack of 6, you would count it as selling 3 units). If you need to indicate the "package type" (e.g. carton for 6 units), then you can activate the "Package" setting (in Inventory) and put the products in a package + assign a stock.package.type to the package. This feature has also been heavily refactored in saas-18.1 as well so you will no longer have this problem in that version.

2026-04-07 07:42 UTC, closed without merging