[14.0][FIX] sale_mrp_bom: accept BoMs without variant
OCA/sale-workflow pull request #2947
Opened 2024-02-07 11:56 UTC by aleuffre

This commit fixes a bug where the module would not accept a BoM on a Sale Order Line if the product in question had multiple variants and the BoM did not specify a variant.

Now, if the variant is specified on the BoM, it must match the product on the Sale Order Line (like before), but if it's not specified, matching on the product template is enough.

2024-02-07 13:26 UTC, francesco-ooops approved these changes
Functional ok!

2024-02-15 11:16 UTC, aayartsev requested changes
Check please my suggestions.

2024-02-15 11:16 UTC, aayartsev commented on sale_mrp_bom/models/sale_order_line.py
> +                if bom_product == line.product_id:
i think this expression will be better: `bom_product and bom_product == line.product_id:`

2024-02-15 11:16 UTC, aayartsev commented on sale_mrp_bom/models/sale_order_line.py
> +            else:
i think you can delete this `else`

2024-02-20 09:59 UTC, aleuffre commented
thank you for your review @aayartsev , I simplified the code according to your suggestions.

2024-02-20 10:50 UTC, aayartsev approved these changes
Looks good.)

2024-02-20 15:46 UTC, francesco-ooops commented
@pedrobaeza is this good to go? Thanks!

2024-02-20 19:42 UTC, pedrobaeza commented
/ocabot merge patch

2024-02-20 21:07 UTC, geomer198 approved these changes
LGTM!

2024-02-23 14:09 UTC, francesco-ooops commented
@pedrobaeza can you relaunch merge command?

2024-02-23 14:15 UTC, pedrobaeza commented
/ocabot merge patch

2024-02-23 14:40 UTC, merged