[17.0][MIG] sale_manual_delivery: Migration to 17.0
OCA/sale-workflow pull request #2973
Opened 2024-02-22 14:19 UTC by astirpe

2024-02-28 08:56 UTC, youring commented
@astirpe would you cherry pick this one https://github.com/ForgeFlow/sale-workflow/pull/5
 ...to keep the CREATE DELIVERY button shown on partial delivered sale order. Thank you.

2024-02-28 13:14 UTC, astirpe commented
@youring done!

2024-02-28 15:21 UTC, youring commented
Functional! 
Tested locally, found two warnings on install

> 2024-02-28 15:13:55,177 105178 WARNING v17 odoo.addons.base.models.ir_model: Rule access_manual_delivery_all has no group, this is a deprecated feature. Every access-granting rule should specify a group.
> 2024-02-28 15:13:55,177 105178 WARNING v17 odoo.addons.base.models.ir_model: Rule access_manual_delivery_line_all has no group, this is a deprecated feature. Every access-granting rule should specify a group.

Maybe it's a good time to add default group.

2024-02-29 07:38 UTC, astirpe commented
@youring done!

2024-02-29 09:42 UTC, youring requested changes
Sorry i didn't notice that it was upgraded automatically by views_migration_17 in my local env. 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#tasks-to-do-in-the-migration

2024-02-29 09:42 UTC, youring commented on sale_manual_delivery/wizard/manual_delivery.xml
> +                            <field name="order_line_id" invisible="1" force_save="1" />
```suggestion
                            <field name="order_line_id" column_invisible="1" force_save="1" />
```

2024-02-29 12:41 UTC, astirpe commented on sale_manual_delivery/wizard/manual_delivery.xml
> +                            <field name="order_line_id" invisible="1" force_save="1" />
Done. Thanks!

2024-03-01 23:17 UTC, youring commented
LGTM. Functional.

2024-03-12 15:55 UTC, rousseldenis commented
/ocabot migration sale_manual_delivery

2024-03-12 15:57 UTC, rousseldenis approved these changes
Code reiview

2024-05-03 08:17 UTC, dreispt commented
/ocabot merge nobump

2024-05-03 08:25 UTC, merged