[MIG] sale_discount_display_amount: Migration to 17.0
OCA/sale-workflow pull request #3026
Opened 2024-03-18 10:59 UTC by FSchiepers

This version adds the possibility to choose whether the discount is calculated based on the non-taxed subtotal or the taxed total, see: https://github.com/OCA/sale-workflow/issues/2813

Correction from https://github.com/OCA/sale-workflow/pull/2987

2024-03-18 11:02 UTC, FSchiepers commented
/ocabot migration sale_discount_display_amount

2024-03-18 16:26 UTC, rousseldenis commented
/ocabot migration sale_discount_display_amount

2024-03-18 16:31 UTC, rousseldenis requested changes
Code review.

IMHO changes in the module should be done in a separate commit in order to separate the real migration and the improvements.

2024-03-18 16:31 UTC, rousseldenis commented on sale_discount_display_amount/__manifest__.py
> +    "installable": True,
@FSchiepers All these values are the default ones, not necessary

2024-03-18 16:31 UTC, rousseldenis commented on sale_discount_display_amount/hooks.py
> +logger = logging.getLogger(__name__)
This notation is widely used to indicate that should not be used externally. You should let it as is.

2024-04-15 11:18 UTC, rousseldenis commented
@FSchiepers Could you improve your commit messages :

![image](https://github.com/OCA/sale-workflow/assets/19529533/3653cf5e-e617-4039-ac16-4e7e17981a0b)


Something like `[IMP] sale_discount_display_amount: (...)`

Thanks

2024-04-16 06:42 UTC, FSchiepers commented on sale_discount_display_amount/hooks.py
[IMP]sale_discount_display_amount: : renamed Logger to _logger

2024-04-16 06:45 UTC, FSchiepers reviewed
[IMP]sale_discount_display_amount: : renamed Logger to _logger

2024-04-16 06:45 UTC, FSchiepers commented on sale_discount_display_amount/__manifest__.py
[IMP] sale_discount_display_amount: Removed all the standard parameters.

2024-04-16 06:47 UTC, FSchiepers reviewed
[IMP] sale_discount_display_amount: Removed all the standard parameters.

2024-04-30 08:25 UTC, FSchiepers commented
I added comments, can you review please?

2024-05-23 11:12 UTC, closed without merging

2024-05-29 11:59 UTC, FSchiepers commented
rebased to https://github.com/OCA/sale-workflow/pull/3160