[FIX] sale_elaboration: propagate note-only lines to stock moves
OCA/sale-workflow pull request #3029
Opened 2024-03-20 11:46 UTC by yajo

Before this patch, if a sale order line had no elaborations selected, but had elaboration notes, those notes didn't land in the created `stock.move` records when confirming the SO.

@moduon MT-5511

2024-03-20 12:10 UTC, Shide requested changes
Thanks! Great job!

**suggestion:** Please add this behavior to DESCRIPTION: "Elaboration notes does not appear on Delivery Slips. Only Elaborations with its codes."

If you use a note on elaboration but not an elaboration (m2m), this won't be shown in the delivery slip because only print CODES of the elaborations (m2m). Can be a bit confusing.

2024-03-20 19:03 UTC, fcvalgar approved these changes
Functional review,

LGTM thank you @yajo

2024-03-20 21:33 UTC, Shide approved these changes

2024-03-21 17:54 UTC, rafaelbn approved these changes
👍🏼

2024-03-25 09:27 UTC, yajo commented
/ocabot merge patch

2024-03-25 09:35 UTC, merged