[16.0][IMP] sale_order_product_picker: Support use of discounts
OCA/sale-workflow pull request #3037
Opened 2024-03-22 12:39 UTC by CarlosRoca13

cc @Tecnativa TT48323

ping @sergio-teruel @carlosdauden

2024-03-22 16:08 UTC, sergio-teruel requested changes

2024-03-22 16:08 UTC, sergio-teruel commented on sale_order_product_picker/models/sale_order_picker.py
> +        # so_line._product_id_change()
Is ok this commented line??

2024-03-25 07:29 UTC, CarlosRoca13 commented on sale_order_product_picker/models/sale_order_picker.py
> +        # so_line._product_id_change()
The method doesn't exist now, removed line

2024-03-25 08:00 UTC, chienandalu commented on sale_order_product_picker/static/src/x2many/x2many_field.esm.js
> +                lineList = this.props.record.model.root.data.order_line;
You aren't declaring it... doesn't this fail?

2024-03-25 08:00 UTC, chienandalu commented on sale_order_product_picker/static/src/x2many/x2many_field.esm.js
> +                lineList = this.props.record.model.root.data.order_line;
Same here..

2024-03-25 09:08 UTC, CarlosRoca13 commented
That var is defined in line 29. I added comments explaining why need to redefine the list.

2024-07-03 05:23 UTC, CarlosRoca13 commented
Added changes to make the button +1 faster. With these changes, what we do is to store the changes to be made while pressing the +1 button. Each time the button is pressed, the timer that will execute the writing of the lines is reset. 

This relieves the server of unnecessary calls, since everything will be written at the same time. And the user will not have the feeling of slowness when writing on 3G networks.

Here is a sample:
![Example picker16 0](https://github.com/OCA/sale-workflow/assets/35952655/c5362208-87eb-4a02-9136-49469d191435)

As you can see in the example, the time to write the pending lines is 1 sec, but it can be increased using the system parameter `sale_order_product_picker.delay` and the number of seconds to wait.

2024-07-03 05:30 UTC, CarlosRoca13 commented
@yajo I believe this should resolve this issue :smile: https://github.com/OCA/sale-workflow/issues/2842

2024-07-12 08:38 UTC, sergio-teruel commented
@CarlosRoca13 Can you put this PR as draft until september?

2024-12-02 14:51 UTC, CarlosRoca13 commented
This PR is ready for review

2024-12-03 10:59 UTC, yajo approved these changes
Thanks!

2024-12-03 11:15 UTC, sergio-teruel approved these changes

2024-12-03 11:16 UTC, pedrobaeza commented
/ocabot merge minor

2024-12-03 11:33 UTC, merged