[8.0][ISSUE][sale_quotation_number]Fixing Issues #303
OCA/sale-workflow pull request #304
Opened 2016-05-31 02:12 UTC by mikevhe18

Fixing Issues #303

2016-05-31 12:11 UTC, andhit-r commented
@mikevhe18 i tested the functionality:

Test 1
--------

1. I duplicate one quotation

Expected Behavior:

* Sales quotation duplicated

Result:

* Passed

Test 2
--------

1. I cancel one of the quotation
2. I click **Create New Copy Of Quotation**

Expected behavior:

* Odoo create new quotation revision

Result:

Warning message showed **Constraint Error: Order Reference and revision must be unique per Company.**

This issue involving interaction between sale_quotation_number and sale_order_revision. You should test the interaction of copy method on both modules.

2016-11-13 19:34 UTC, pedrobaeza commented on sale_quotation_number/model/sale_order.py
> +        return super(SaleOrder, self).copy(default)
Why do you remove the keyword argument?

2016-12-22 10:02 UTC, aheficent commented
I experienced the same issue

2017-01-23 09:45 UTC, AaronHForgeFlow approved these changes
:+1: Tested on local with https://github.com/OCA/sale-workflow/pull/323

2017-05-15 12:14 UTC, StefanRijnhart requested changes
:-1: I'm putting my money on https://github.com/OCA/sale-workflow/pull/473/files

2017-05-15 12:15 UTC, closed without merging