[15.0][IMP] sale_planner_calendar: Design improves and new buttons in calendar planner event
OCA/sale-workflow pull request #3073
Opened 2024-04-14 14:17 UTC by pilarvargas-tecnativa

cc @Tecnativa TT48632

2024-04-16 06:33 UTC, CarlosRoca13 approved these changes
Tested on runboat :+1:

2024-04-17 11:40 UTC, chienandalu requested changes
Some code review and light testing:

- Add a description of tasks done in the commit
- Also add in the readme the new relevant features and how to use them
- Testing I came across this error:
```
    url = partner_latitude + "%2C" + partner_longitude
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 658, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

2024-04-17 11:40 UTC, chienandalu commented on sale_planner_calendar/models/sale_planner_calendar_event.py
> +            if rec.partner_mobile:
```suggestion
        self.sanitized_partner_mobile = False
        for rec in self.filtered("partner_mobile"):
```

2024-04-17 11:40 UTC, chienandalu commented on sale_planner_calendar/models/sale_planner_calendar_event.py
> +    # To set whatsapp URIs
Explain why in the compute method
```suggestion
```

2024-04-17 11:40 UTC, chienandalu commented on sale_planner_calendar/models/sale_planner_calendar_event.py
> +    # Profile icon
The field name says so...
```suggestion
```

2024-04-17 11:40 UTC, chienandalu commented on sale_planner_calendar/models/sale_planner_calendar_event.py
> +    # Geolocation
Explain it in the compute method
```suggestion
```

2024-04-17 11:40 UTC, chienandalu commented on sale_planner_calendar/models/sale_planner_calendar_event.py
> +            rec.location_url = False
```suggestion
        self.location_url = False
        for rec in self:
```

2024-04-17 11:40 UTC, chienandalu commented on sale_planner_calendar/models/sale_planner_calendar_event.py
> +            url = ""
You don't need this variable, just write directly in the record field

2024-04-17 11:40 UTC, chienandalu commented on sale_planner_calendar/models/sale_planner_calendar_event.py
> +                url = partner_latitude + "%2C" + partner_longitude
```suggestion
                url = f"{partner_latitude}%2C{partner_longitude}"
```

2024-04-17 11:40 UTC, chienandalu commented on sale_planner_calendar/models/sale_planner_calendar_event.py
> +        )
Better use `expression.AND`

2024-04-18 17:04 UTC, pedrobaeza approved these changes
You can add a before/after screenshot also for reference.

2024-05-23 17:54 UTC, pedrobaeza commented
/ocabot merge major

2024-05-23 18:13 UTC, merged

2024-05-23 18:15 UTC, pedrobaeza commented
@pilarvargas-tecnativa please fw-port it to v16