[ADD] sale_order_line_effective_date
OCA/sale-workflow pull request #3129
Opened 2024-05-08 15:34 UTC by EmilioPascual

Add field effective date in sale order line. This field is a compute with completion date of the first delivery.

@yajo @Shide @rafaelbn @Gelojr please review

MT-6075 @moduon

2024-05-09 06:40 UTC, yajo requested changes

2024-05-09 06:40 UTC, yajo commented on sale_order_line_effective_date/models/sale_order_line.py
> +            dates_list = [date for date in moves.mapped("date") if date]
suggestion: filtering twice feels awkward

```suggestion
            moves = line.move_ids.filtered(
                lambda x: x.state == "done" and x.location_dest_id.usage == "customer" and x.date
            )
            dates_list = moves.mapped("date")
```

2024-05-09 06:40 UTC, yajo commented on sale_order_line_effective_date/readme/DESCRIPTION.md
> +This module extends the functionality of sale stock and add field effective date in sale order line, this field is completion date of the first delivery order.
```suggestion
This module extends the functionality of sale stock and adds the field "effective date" in sale order lines.
This field displays the completion date of the first delivery order.
```

2024-05-09 06:40 UTC, yajo commented on sale_order_line_effective_date/readme/USAGE.md
> +1. Create new quotation with storable product.
```suggestion
1. Create a new quotation with a storable product.
```

2024-05-09 06:40 UTC, yajo commented on sale_order_line_effective_date/readme/USAGE.md
> +To see field effective date you can install *sale_order_line_menu*
This would fit better in `INSTALL.md`

2024-06-04 09:41 UTC, Shide requested changes
*nitpick*: Simplification

2024-06-04 09:41 UTC, Shide commented on sale_order_line_effective_date/models/sale_order_line.py
> +            line.effective_date = min(dates_list, default=False)
Use [:1] to get an empty Recordset if there is no records in the Recordset and .date will give you False

```suggestion
            line.effective_date = line.move_ids.filtered_domain([
                ("state", "=", "done"),
                ("location_dest_id.usage", "=", "customer"),
                ("date", "!=", False),
            ]).sorted("date")[:1].date
```

2024-06-11 11:05 UTC, Shide commented
Added another field: Last Effective Date (last delivery date)

2024-06-11 11:55 UTC, yajo approved these changes

2024-06-11 11:56 UTC, yajo commented
@gelojr please review

2024-06-12 10:25 UTC, Shide approved these changes

2024-06-18 09:12 UTC, Gelojr approved these changes
LGTM Thanks @Shide

2024-06-20 08:01 UTC, rafaelbn commented
/ocabot merge patch

2024-06-20 11:32 UTC, merged