[17.0][MIG] product_supplierinfo_for_customer_sale: Migration to 17.0
OCA/sale-workflow pull request #3149
Opened 2024-05-24 01:29 UTC by xmglord

2024-05-24 04:03 UTC, xmglord commented
This is waiting for [this](https://github.com/OCA/product-attribute/pull/1617) to be merged.

cc: @luisg123v @desdelinux

2024-06-05 22:41 UTC, xmglord commented
@pedrobaeza this is ready for merge.

2024-06-06 07:04 UTC, pedrobaeza commented
/ocabot migration product_supplierinfo_for_customer_sale

Reviews are missing

2024-06-06 07:06 UTC, xmglord commented
> /ocabot migration product_supplierinfo_for_customer_sale
> 
> Reviews are missing

MB you're right. @luisg123v please review.

2024-06-06 16:47 UTC, desdelinux approved these changes

2024-06-06 19:02 UTC, luisg123v requested changes

2024-06-06 19:02 UTC, luisg123v commented on product_supplierinfo_for_customer_sale/README.rst
> +    :target: https://github.com/OCA/sale-workflow/tree/17.0/product_supplierinfo_for_customer_sale
Commit title:

execution → autofixes

2024-06-06 19:02 UTC, luisg123v commented on product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
> +        super().setUp()
Isn't this part of the precommit changes? Did you perform this change manually?

2024-06-06 19:02 UTC, luisg123v commented on product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
> +    def setUp(self):
`setUpClass`

Same in the other test file.

2024-06-07 01:35 UTC, xmglord commented on product_supplierinfo_for_customer_sale/tests/test_product_supplierinfo_for_customer_sale.py
> +    def setUp(self):
Done

2024-06-07 01:35 UTC, xmglord commented on product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
> +        super().setUp()
Nop I had to apply it by myself, it is indeed a lint but the autofix didn't change it.

2024-06-07 01:35 UTC, xmglord commented on product_supplierinfo_for_customer_sale/README.rst
> +    :target: https://github.com/OCA/sale-workflow/tree/17.0/product_supplierinfo_for_customer_sale
done

2024-06-08 18:15 UTC, luisg123v approved these changes
LGTM :+1: 

Hi @moylop260 or @pedrobaeza,

Could you review/merge, please?

CC @desdelinux

2024-06-14 17:38 UTC, luisg123v commented
@moylop260 or @pedrobaeza,

Friendly reminder, this is approved and waiting for merge.

2024-06-14 19:26 UTC, moylop260 commented
/ocabot merge nobump

2024-06-14 19:34 UTC, merged