[MIG] sale_triple_discount: Migration to 17.0
OCA/sale-workflow pull request #3157
Opened 2024-05-28 08:03 UTC by Boxnia

Standard migration to 17.0

2024-05-29 11:23 UTC, rousseldenis commented on test-requirements.txt
> +odoo-addon-account_invoice_triple_discount @ git+https://github.com/OCA/account-invoicing.git@refs/pull/1626/head#subdirectory=account_invoice_triple_discount
@Boxnia 
```suggestion
odoo-addon-account_invoice_triple_discount @ git+https://github.com/OCA/account-invoicing.git@refs/pull/1626/head#subdirectory=setup/account_invoice_triple_discount
```

2024-05-29 11:24 UTC, rousseldenis commented on test-requirements.txt
> +odoo-addon-account_invoice_triple_discount @ git+https://github.com/OCA/account-invoicing.git@refs/pull/1626/head#subdirectory=account_invoice_triple_discount
Ugh changed for v17. Ok

2024-05-29 13:54 UTC, Boxnia commented
@ rousseldenis I have changedthe test-requirement but the bug is the same.

Thanks

2024-08-08 08:13 UTC, traitrantrobz requested changes
I don't know the reason why i cannot edit the discount1-2-3 field on the order line. It gets reset after I edit it. Please deouble-check it. Thank you!

2024-08-29 16:05 UTC, grindtildeath commented
@Boxnia Thanks for the mig, I guess we'll want to bring https://github.com/OCA/sale-workflow/pull/3157 in v17.0 from the get go, although it's not merged in 16.0 yet. We discussed the same for account_invoice_triple_discount here: https://github.com/OCA/account-invoicing/pull/1626#issuecomment-2233039506

2024-11-12 12:07 UTC, dalonsod requested changes
See comments

2024-11-12 12:07 UTC, dalonsod commented on sale_triple_discount/models/sale_order_line.py
> +        self.invalidate_model(self._discount_fields(), self.ids)
@Boxnia @traitrantrobz regarding to issue commented at https://github.com/OCA/sale-workflow/pull/3157#pullrequestreview-2227169034 I've simply remove this line and it worked for me, could you check?
```suggestion
```

2024-11-12 12:07 UTC, dalonsod commented on sale_triple_discount/models/sale_order_line.py
> +        )
I don't know if it is now needed. Anyway, `invalidate_model` signature for v17 seems to be different than used (and `invalidate_recordset` should be used instead), could you check?

2024-11-12 16:50 UTC, dalonsod commented
Superseded by #3406

2025-01-23 16:21 UTC, closed without merging