[ADD][8.0] Sale procurement group by requested date
OCA/sale-workflow pull request #320
Opened 2016-08-01 11:58 UTC by aheficent

# Sale Procurement Group by Requested date

This module creates different procurements groups for different requested dates in a sale order line when the sale order is confirmed. It depends on sale_sourced_by_line so this module will group procurements also by the warehouse in the sale order_line.

### Installation

This module depends on the modules sale_procurement_group_by_line and
sale_sourced_by_line.

### Configuration

No special configuration is required.

### Usage

- Add a requested date for a sale order line.
- Confirmthe sale order

2016-10-12 16:17 UTC, StefanRijnhart requested changes
Thanks! Only two small requests in my review

2016-10-12 16:17 UTC, StefanRijnhart commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +        procurement groups
Can you add to the docstring how the priority is determined by the super?

2016-10-12 16:17 UTC, StefanRijnhart commented on sale_procurement_group_by_requested_date/README.rst
> +the warehosue in the sale order_line also.
typo 'warehouse'

2017-06-14 08:36 UTC, aheficent commented
@StefanRijnhart Apologize for the late review

2019-12-13 08:49 UTC, closed without merging