[17.0][MIG] sale_company_currency : Migration to 17.0
OCA/sale-workflow pull request #3230
Opened 2024-07-11 22:52 UTC by fgaviiria

2024-07-15 07:55 UTC, rousseldenis commented
/ocabot migration sale_company_currency

2024-07-15 07:57 UTC, rousseldenis commented
@fgaviiria Have you followed https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#how-to ?

As some other module changes appear here.

2024-07-18 23:06 UTC, fgaviiria commented
@rousseldenis hey  bro, I already made the changes

2024-07-19 06:19 UTC, rousseldenis approved these changes
Code review

2024-07-19 07:43 UTC, Deriman-Alonso approved these changes

2024-07-19 07:43 UTC, Deriman-Alonso commented on sale_company_currency/views/sale_order_view.xml
> +                <field name='company_currency_id' invisible="1" />
Hi, as the [wiki](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0) says, on a tree view the attribute invisible must be replaced by column_invisible, otherwise the column will be shown empty. Ty

2024-07-24 15:37 UTC, dreispt commented
Can you cherry-pick https://github.com/OCA/sale-workflow/pull/3240 please?

2025-05-01 08:28 UTC, twalter-c2c approved these changes
LGTM

2026-02-02 09:41 UTC, rousseldenis commented
@fgaviiria Could you take the pointed commit by @dreispt  ? Thanks

2026-03-03 10:49 UTC, alexey-pelykh requested changes
Thanks for working on this migration.

There's one issue that needs to be addressed before this can be merged: the bugfix from #3240 hasn't been cherry-picked into this branch. The compute method still divides by `currency_rate`:

```python
to_amount = order.amount_total / order.currency_rate
```

but on 16.0 this was already fixed to multiply instead:

```python
to_amount = order.amount_total * order.currency_rate
```

This was requested by @dreispt back in July 2024 and again by @rousseldenis in February. Without it the company currency amount will be wrong whenever the SO currency differs from the company currency.

The rest of the migration looks correct -- `column_invisible` is properly used for tree views and the manifest/dependencies are fine for 17.0.

2026-05-29 08:16 UTC, rousseldenis commented
Closing this as very old. Feel free to reopen it if needed.

2026-05-29 08:16 UTC, closed without merging