[16.0][ADD] sale_tier_validation_block_print
OCA/sale-workflow pull request #3253
Opened 2024-07-29 04:55 UTC by AungKoKoLin1997

This module blocks the printing of the sale order report if the order is not yet approved. It prevents both manual printing from the print action and printing when clicking `SEND BY EMAIL`. 

@qrtl QT3715

2024-08-01 08:53 UTC, yostashiro requested changes

2024-08-01 08:53 UTC, yostashiro commented on sale_tier_validation_block_print/reports/sale_report.py
> +                    _("This operation is blocked before the order is approved.")
We can make the message more explicit here.
```suggestion
                    _("Quotation printing is blocked until the order is approved.")
```

2024-08-01 08:53 UTC, yostashiro commented on sale_tier_validation_block_print/tests/test_sale_tier_validation_block_print.py
> +        so.request_validation()
No need to have a step to change the price, but we want to make sure that printing is still blocked after a validation request.
```suggestion
        so.request_validation()
        with self.assertRaises(ValidationError):
            report._get_report_values(docids=[so.id])
```

2024-08-05 03:32 UTC, yostashiro approved these changes
Code review.

2024-08-07 02:12 UTC, kanda999 approved these changes
Functional review

2024-08-07 02:28 UTC, yostashiro commented
Got this comment https://x.com/360ERP_Cas/status/1820921116279390285. Should we try to enhance sale_tier_validation instead?

CC: @BT-cserra @bizzappdev @StefanRijnhart @rousseldenis @pedrobaeza

2024-08-07 05:33 UTC, bosd commented
👍 To enhance sale_tier_validation

2024-08-07 06:08 UTC, bizzappdev commented
IMO, it will be best to integrate into an original module with a setting in config/system parameters for blocking reports.

2024-08-08 11:23 UTC, AungKoKoLin1997 commented
This PR is superseded by https://github.com/OCA/sale-workflow/pull/3269.

2024-08-08 11:23 UTC, closed without merging