[17.0] [ADD] sale_blanket_order_tier_validation
OCA/sale-workflow pull request #3277
Opened 2024-08-20 06:13 UTC by Nikul-OSI

2024-08-29 08:18 UTC, StefanRijnhart commented on sale_blanket_order_tier_validation/models/sale_blanket_order.py
> +            rec.write({"state": "open"})
FYI I did https://github.com/OCA/server-ux/pull/939 so that tier validations can be applied to computed state fields as in this model.

2024-09-16 08:40 UTC, rousseldenis commented
@Nikul-OSI Could you rebase ?

2024-09-23 05:18 UTC, Nikul-OSI commented
> Sponsor

Done

2024-09-23 05:26 UTC, Nikul-OSI commented
> @Nikul-OSI Could you rebase ?

Done

2024-09-23 06:28 UTC, StefanRijnhart commented on sale_blanket_order_tier_validation/models/sale_blanket_order.py
> +            rec.write({"state": "open"})
Would you consider reviewing that change and refactoring this module to work with it? You wouldn't have to jump through hoops like you do in the code above.

2024-09-26 09:35 UTC, StefanRijnhart commented on sale_blanket_order_tier_validation/models/sale_blanket_order.py
> +            rec.write({"state": "open"})
I did the refactoring in https://github.com/ursais/sale-workflow/pull/14. What do you think?

2026-03-03 10:46 UTC, alexey-pelykh requested changes
Thanks for working on this, tier validation for blanket orders is a useful addition.

However, since @StefanRijnhart's [base_tier_validation improvement](https://github.com/OCA/server-ux/pull/939) (support for computed state fields) was merged in October 2024, the full `_compute_state` override in this module should no longer be necessary. I'd strongly recommend refactoring to leverage that, as Stefan already suggested — and even prototyped in https://github.com/ursais/sale-workflow/pull/14. The current approach copies the entire upstream compute method, which is fragile and will silently break whenever `sale_blanket_order` updates its `_compute_state`.

Beyond that, there are a few concrete issues:

**Bug in `_compute_state`**: When `confirmed=True`, `validity_date > today`, and remaining qty is non-zero, no state gets assigned at all (the `else: order.state = "open"` was removed but nothing replaces it for that case). This leaves the state stale/undefined for active confirmed orders.

**`action_confirm` write ordering**: `rec.write({"state": "open"})` runs before `super().action_confirm()`, but since `state` is a computed field that depends on `confirmed`, the `super()` call setting `confirmed = True` will trigger recomputation, which — given the bug above — won't set state to `"open"` either.

**Docs reference wrong model**: `readme/CONFIGURE.md` says "Create as many tiers as you want for Purchase Order model" — should say Sale Blanket Order.

**`needs_review` filter domain**: References states `cancel` and `to approve` which don't exist on `sale.blanket.order` (valid states: draft, open, done, expired). This filter would match records it shouldn't.

**Missing copyright header** in `tests/__init__.py`.

The main ask: please rebase, adopt the computed state support from `base_tier_validation`, and drop the `_compute_state` override entirely. That should also resolve the state assignment bug and the `action_confirm` ordering issue naturally.

2026-05-29 08:49 UTC, rousseldenis commented
Closing this as very old. Please feel free to reopen it if needed.

2026-05-29 08:49 UTC, closed without merging