[17.0][FIX] sale_blanket_order: filter default taxes by company for all users
OCA/sale-workflow pull request #3288
Opened 2024-08-29 09:04 UTC by StefanRijnhart

Because all users can potentially access taxes from multiple companies.

Also add some minor usability improvements (cf. sale.order.line's tax_id).

2024-08-29 09:48 UTC, StefanRijnhart commented
Tests fixed in https://github.com/OCA/sale-workflow/pull/3290

2024-09-16 12:08 UTC, rousseldenis approved these changes
LGTM

2024-09-26 12:29 UTC, espo-tony approved these changes
:+1: LGTM

2024-09-27 11:42 UTC, CasVissers-360ERP approved these changes
Functional review

2024-10-07 14:03 UTC, StefanRijnhart commented
@OCA/crm-sales-marketing-maintainers ready to merge, I think.

2025-05-11 19:49 UTC, ivs-cetmix requested changes
Hi @StefanRijnhart , thank you for your contribution!

Could you please improve your commit message for better changes traceability?
Eg like this:

```
[FIX] sale_blanket_order: filter default taxes by company for all users

**Before this commit**

What was the flow before 

**After this commit**

How it works now

2025-08-20 14:14 UTC, MiquelRForgeFlow approved these changes

2025-08-26 09:19 UTC, ivs-cetmix approved these changes
@StefanRijnhart thank you for your contribution!

/ocabot merge patch

2025-08-26 09:27 UTC, merged

2025-08-26 11:31 UTC, StefanRijnhart commented
Note to self: commit already ended up in https://github.com/OCA/sale-blanket/pull/8, so no backport required.