17 port from 16 sale automatic workflow send invoice option
OCA/sale-workflow pull request #3361
Opened 2024-10-15 16:56 UTC by john-herholz-dt

Forward-porting:

- https://github.com/OCA/sale-workflow/pull/2642

2024-10-16 12:23 UTC, rousseldenis approved these changes

2024-10-16 14:26 UTC, sergijPf approved these changes

2025-05-11 19:55 UTC, ivs-cetmix requested changes
Hi @john-herholz-dt  thank you for your contribution!
Could you please do the following:

1. Squash the commits, rebase and resolve the conflicts.
2. Replace the commit tag with the one supported according to the [OCA Coding Guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message).
3. Adjust the commit message accordingly to the same guidelines.

2026-03-03 10:49 UTC, alexey-pelykh requested changes
Thanks for the forward-port, nice feature.

A few issues that need addressing before this can be merged:

1. **`action_done()` does not exist in Odoo 17** -- In `_do_sale_done`, the PR replaces the existing `sale.action_lock()` with `sale.action_done()`, and changes the docstring/return message from "lock" to "done". This is a leftover from the 16.0 original. In 17.0, `action_done()` was removed and `action_lock()` is the correct method. This change should be reverted -- keep `action_lock()` as on the current 17.0 branch.

2. **Orphaned picking fields** -- `validate_picking`, `picking_filter_domain`, and `picking_filter_id` are added to `sale_workflow_process.py` but there is no corresponding job logic in `automatic_workflow_job.py`, no data record, and no view element for them. These look like 16.0-era fields that leaked into this forward-port. They should be removed from this PR.

3. **Docstring copy-paste** in `_do_send_invoice`: says *"Validate an invoice"* instead of *"Send an invoice"*.

4. As already requested by @ivs-cetmix, the commits need to be squashed and rebased with a proper OCA commit tag.

The `send_invoice` feature itself (using `account.move.send` wizard with `force_synchronous`) looks correct for 17.0 and the tests provide good coverage.

2026-06-29 08:00 UTC, rousseldenis commented
/ocabot rebase

2026-06-29 08:00 UTC, rousseldenis commented
Closing this as very old. Feel free to reopen it if needed.

2026-06-29 08:00 UTC, closed without merging