[18.0][MIG] sales_team_security: Migration to 18.0
OCA/sale-workflow pull request #3368
Opened 2024-10-21 12:45 UTC by BertVGroenendael

2024-10-21 13:48 UTC, rousseldenis commented
/ocabot migration sales_team_security

2024-10-21 13:50 UTC, pedrobaeza commented
/ocabot migration sales_team_security

2024-11-13 14:48 UTC, dalonsod commented
Hello @BertVGroenendael could you add fix provided by #3407 ?

2024-11-18 13:28 UTC, woutswennen commented
Error form solved + added Fix https://github.com/OCA/sale-workflow/pull/3407

2024-11-21 14:42 UTC, matiasperalta1 approved these changes
LGTM

2024-11-21 14:42 UTC, matiasperalta1 commented
@pedrobaeza Is it ready to merge?

2024-11-21 15:03 UTC, pedrobaeza commented
- Squash migration commits.
- The commit message doesn't follow the expected format. Check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0

2024-11-25 13:16 UTC, matiasperalta1 commented
@BertVGroenendael Hi! Please, to proceed to merge this migration check the following items:
-Squash migration commits.
-The commit message doesn't follow the expected format. Check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0

2024-12-05 17:15 UTC, nicolascol commented
Hi @BertVGroenendael 
Could you see the comments please?

2025-02-04 15:32 UTC, lav-adhoc commented
@BertVGroenendael @pedrobaeza can someone marge this module, please? We need for other modules, thank you

2025-02-04 16:18 UTC, pedrobaeza commented
There are several migration commits from the same author, and there's also a weird README reformatting in one of them. You should also squash administrative commits.

2025-02-06 17:15 UTC, carlos-lopez-tecnativa requested changes
I found a potential issue (I tested it in V17, and it does not occur).

If a partner has child contacts and you assign a user_id to the partner, the child contacts have an empty field (I think the child contacts should inherit the same user as the parent partner). However, the issue occurs when you try to open the contact list—in the kanban view, it does not happen, but in the list view, it does.

1) Assign the user "admin" to Deco
![image](https://github.com/user-attachments/assets/077fde60-468c-413a-8059-d7903571c28e)
2) The demo user has the "Own documents only" group.
![image](https://github.com/user-attachments/assets/80fdcef6-a315-433d-be17-d49d1e400a00)
3) Go to Contacts and search for "Deco." It shows three contacts in the kanban view.
4) Switch to the list view and get an error.
![image](https://github.com/user-attachments/assets/5a5b5715-f13c-4088-badb-e26d3875b45c)

TT54318
@Tecnativa

2025-02-06 17:15 UTC, carlos-lopez-tecnativa commented on sales_team_security/models/res_partner.py
> +        index=True,
Why this field is now related?

2025-02-06 17:15 UTC, carlos-lopez-tecnativa commented on sales_team_security/models/res_partner.py
> +        res = super().get_view(view_id, view_type, **options)
The module `base_view_inheritance_extension` is now available. Could you update the code?

2025-02-06 17:15 UTC, carlos-lopez-tecnativa commented on sales_team_security/models/ir_rule.py
> +                        ("team_id", "=", False),
I think it can be simplified to:
```suggestion
                        ("team_id", "in", user.crm_team_ids.ids + [False]),
```

Please consider that a user can belong to more than one team. See
https://github.com/OCA/sale-workflow/pull/3429#discussion_r1907938880

2025-02-06 17:15 UTC, carlos-lopez-tecnativa commented on sales_team_security/models/ir_rule.py
> +                        ("team_id", "=", user.sale_team_id.id),
The same here
```suggestion
                        "|",
                        ('user_id', 'in', [user.id, False]),
                        ('team_id', 'in', user.crm_team_ids.ids + [False]),
```

2025-02-12 14:00 UTC, carlos-lopez-tecnativa commented
> I found a potential issue (I tested it in V17, and it does not occur).
> 
> If a partner has child contacts and you assign a `user_id` to the partner, the child contacts have an empty field (I think the child contacts should inherit the same user as the parent partner). However, the issue occurs when you try to open the contact list—in the kanban view, it does not happen, but in the list view, it does.
> 

ping @BertVGroenendael could you please check my previous comment

2025-02-26 15:12 UTC, carlos-lopez-tecnativa commented
ping @BertVGroenendael could you please check my previous comment

2025-03-06 11:39 UTC, carlos-lopez-tecnativa commented
Superseded by https://github.com/OCA/sale-workflow/pull/3614

2025-03-06 17:18 UTC, closed without merging