[15.0][ADD] account_invoice_sale_attachment
OCA/sale-workflow pull request #3392
Opened 2024-11-07 16:34 UTC by sbejaoui

This module allows the automatic attachment of related sale order documents when an invoice is sent.

2024-11-07 16:41 UTC, samirGuesmi approved these changes
LGTM

2024-11-07 16:48 UTC, qgroulard approved these changes
LGTM (code review)

2025-05-11 20:12 UTC, ivs-cetmix requested changes
Hi @sbejaoui, thank you for your contribution!

Please check the comments. Also please add a CONFIGURE.rst file with a single line "No configuration is required" to avoid possible misunderstanding.

I would also suggest the following improvements:

- Change the attachment field to m2m to allow to attach multiple files.
- Add screenshots to the documentation to improve the UX.
- Add the CONTEXT.rst file which would explain the idea behind this module. Eg 

 "Sometime you need to attach specific Sales Order documents to all customer invoices. For example payment instructions or a user manual."

2025-05-11 20:12 UTC, ivs-cetmix commented on account_invoice_sale_attachment/models/sale_order.py
> +            attachment = self.env["ir.attachment"].search(
You should fetch all attachments using a single query to improve the performance. Something like this:

```python

attachments = self.env["ir.attachment"].search(                [
                    ("res_id", "in", self.ids),
                    ("res_model", "=", self._name),
                    ("res_field", "=", "sale_document_attachment"),
                ]
            )
for attachment in attachments:
    order = self.browse(attachment["res_id"])
    if order and order.sale_document_filename:
        attachment.name = order.sale_document_filename
```

2025-05-30 09:13 UTC, rousseldenis commented
> Please check the comments. Also please add a CONFIGURE.rst file with a single line "No configuration is required" to avoid possible misunderstanding.

@ivs-cetmix CONFIGURE.rst and CONTEXT.rst are optional, see: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

They are not required to be merged.

2025-05-30 15:31 UTC, ivs-cetmix commented
> > Please check the comments. Also please add a CONFIGURE.rst file with a single line "No configuration is required" to avoid possible misunderstanding.
> 
> @ivs-cetmix CONFIGURE.rst and CONTEXT.rst are optional, see: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
> 
> They are not required to be merged. Please update your review

@rousseldenis  Yes, I agree. However let's add at least the CONTEXT because it improves the search experience and helps other people to locate the module.

@sbejaoui I have another idea after I checked the module once again that might improve the UX and also simplify the code as well. Please review and let me know what you think about it:

- User wants to ensure that some attachments are added automatically from the Sales Order to all invoices that are created and sent from this SO.
- User opens the Sales order and adds those files as attachments directly in chatter.
- User opens the "Other Info" tab of the sales order and selects attachments that he wants to be automatically added in the Invoice Attachments field. Similar to how it's done in the [mail_attach_exiasting_attachment](https://github.com/OCA/social/tree/16.0/mail_attach_existing_attachment) module.
![image](https://github.com/user-attachments/assets/9784eecf-468a-459c-bb40-7f5f1834858b)
- bonus: we might also consider integration with this [module](https://github.com/OCA/social/tree/16.0/mail_attach_existing_attachment_account). 


Pros:  
- just one field instead of two
- can attach multiple attachments
- uses the standard attachment mechanism

2025-05-30 15:54 UTC, rousseldenis commented
> @rousseldenis Yes, I agree. However let's add at least the CONTEXT because it improves the search experience and helps other people to locate the module

Just I wanted you to pay attention to blocking reviews on such things that can refrain contributions. Prefer normal comment.

That said, I agree 100% that the more content we put in modules, the best it is to help people finding stuffs.

2025-05-30 16:06 UTC, ivs-cetmix commented
> > @rousseldenis Yes, I agree. However let's add at least the CONTEXT because it improves the search experience and helps other people to locate the module
> 
> Just I wanted you to pay attention to blocking reviews on such things that can refrain contributions. Prefer normal comment.
> 
> That said, I agree 100% that the more content we put in modules, the best it is to help people finding stuffs.

Noted, thank you! 😉

2026-05-03 13:05 UTC, closed without merging