17.0][MIG] sale_pricelist_triple_discount: Migration to 17.0
OCA/sale-workflow pull request #3401
Opened 2024-11-11 14:22 UTC by david-s73

2024-11-14 09:48 UTC, rousseldenis commented
/ocabot migration sale_pricelist_triple_discount

2024-11-17 12:24 UTC, dalonsod commented
Hello @david-s73 thanks for the contribution!

Could you replace `sale_triple_discount` PR dependency by #3406 ?

2024-11-19 11:43 UTC, ioans73 commented
> Hello @david-s73 thanks for the contribution!
> 
> Could you replace `sale_triple_discount` PR dependency by #3406 ?

@dalonsod done!

2025-04-03 10:26 UTC, ioans73 approved these changes
Functional review

2025-11-04 16:34 UTC, dalonsod commented
@david-s73 @adrip-s73 your implementation of this migration is still based on a `sale_triple_discount` old PR (#3406), and actually closed.

I think the most accurate approach is the newer one #3929 , that is also based in a deep refactoring (coming from v16,) you check following the links, could you take a look?

cc @hildickethan

2025-11-04 16:44 UTC, adrip-s73 commented
@dalonsod We've noted that the pull request (https://github.com/OCA/sale-workflow/pull/3406) has been closed. In fact, the adaptation we've made is based on the new pull request. The last commit I made was to incorporate all these changes. We still need to modify the dependency and update it to the new pull request.

2025-11-04 16:48 UTC, dalonsod commented
Good! I saw old PR at `test-requirements.txt` and I only warned about it, good news if I was finally wrong

2025-11-04 17:00 UTC, hildickethan commented
https://github.com/OCA/sale-workflow/pull/3907/commits/3e13ae9d8b2dbf4a510c397e081be372ce9a1c19 this is what I added for the 16.0 refactoring to make this module work in that version, I remember everything seeming to work OK but it was mostly some quick functional checks and putting faith in the unit tests so it's possible there's some cases that need additional work. If you discover anything that isn't covered feel free to ping me

2025-11-05 12:37 UTC, adrip-s73 commented
@hildickethan We have already adapted the commit from version 16.0 and updated the requirements for the new pr https://github.com/OCA/sale-workflow/pull/3929

2025-11-05 14:01 UTC, hildickethan commented on sale_pricelist_triple_discount/model/sale.py
> +        res = super()._compute_discount()
that doesn't seem right

2025-11-05 14:01 UTC, hildickethan commented on sale_pricelist_triple_discount/test-requirements.txt
> +odoo-addon-sale_triple_discount @ git+https://github.com/OCA/sale-workflow.git@refs/pull/3929/head#subdirectory=setup/sale_triple_discount
```suggestion
odoo-addon-sale_triple_discount @ git+https://github.com/OCA/sale-workflow.git@refs/pull/3929/head#subdirectory=sale_triple_discount
```
tests fail cause in 17.0 setup/ isn't necessary

2025-11-11 07:28 UTC, adrip-s73 commented on sale_pricelist_triple_discount/model/sale.py
> +        res = super()._compute_discount()
done

2025-11-11 07:28 UTC, adrip-s73 commented on sale_pricelist_triple_discount/test-requirements.txt
> +odoo-addon-sale_triple_discount @ git+https://github.com/OCA/sale-workflow.git@refs/pull/3929/head#subdirectory=setup/sale_triple_discount
done

2026-03-03 10:52 UTC, alexey-pelykh requested changes
Thanks for the migration work on this module, and for addressing hildickethan's earlier feedback.

A few things I noticed on the current state:

1. **`__manifest__.py` -- broken `website` value**: The implicit string concatenation produces `"https://github.com/OCA/sale-workflow17.0/sale_pricelist_triple_discount"` (missing `/tree/`). Standard OCA 17.0 convention is just:
   ```python
   "website": "https://github.com/OCA/sale-workflow",
   ```

2. **CI is red**: Both `test with Odoo` and `test with OCB` are failing on the latest commit. This needs investigation -- possibly related to the dependency on #3929 or the test-requirements change.

3. **`model/` vs `models/`**: The package directory is `model/` (singular). OCA 17.0 convention is `models/` (plural). Since this is a migration, it would be a good time to align with the convention.

4. **Last commit `[DON'T MERGE]`**: The temporary commit for `test-requirements.txt` should be squashed into the migration commit before this is ready.

Items 1 and 2 are blocking; 3 and 4 should be addressed before merge.

2026-06-29 08:46 UTC, closed without merging

2026-06-29 08:46 UTC, rousseldenis commented
Closing this as very old. Feel free to reopen it if needed