[18.0][MIG] sale_commercial_partner: Migration to 18.0
OCA/sale-workflow pull request #3415
Opened 2024-11-20 08:16 UTC by BertVGroenendael

2024-12-02 08:58 UTC, LucasTran380381 commented
Pls squash commit

2024-12-02 11:15 UTC, StefanRijnhart commented on sale_commercial_partner/tests/test_sale_commercial_partner.py
> +    def setUp(self):
Thanks for adding the test! Can you refactor to use @classmethod setUpClass(cls)?

2024-12-03 02:56 UTC, LucasTran380381 requested changes

2024-12-03 02:56 UTC, LucasTran380381 commented on sale_commercial_partner/views/sale_order.xml
> +    </record>
recommend to removed ( not need to add invisible field)

2024-12-03 08:22 UTC, StefanRijnhart commented on sale_commercial_partner/views/sale_order.xml
> +    </record>
No, please keep it. We use it in inherits that include the field in domains and such.

2024-12-03 10:01 UTC, LucasTran380381 commented on sale_commercial_partner/views/sale_order.xml
> +    </record>
In odoo18,  domain field will automatically added invisible field that mean no need to declared invisible field to use it in domain

2024-12-03 10:47 UTC, StefanRijnhart commented on sale_commercial_partner/views/sale_order.xml
> +    </record>
Excellent, thanks for clarifying! I tested this successfully, using the field in `domain` and `invisible` attributes. Found the implementation in https://github.com/odoo/odoo/pull/137031. I'll add it to the OCA's 18.0 migration guidelines.

Just curious, do you know if this is documented anywhere?

2024-12-03 11:21 UTC, LucasTran380381 commented on sale_commercial_partner/views/sale_order.xml
> +    </record>
No documentation, recommend dev using odoo-module-migrator and follow guidelines.

2024-12-05 07:41 UTC, rousseldenis commented
/ocabot migration sale_commercial_partner

2024-12-05 07:41 UTC, rousseldenis commented
@BertVGroenendael Could you attend @StefanRijnhart comment ?

2024-12-16 04:32 UTC, LucasTran380381 commented
Since this PR has been inactive for 2 weeks, I've started working on related PRs based on this approach

2024-12-18 11:15 UTC, StefanRijnhart commented
Closing in favor of https://github.com/OCA/sale-workflow/pull/3504

2024-12-18 11:15 UTC, closed without merging