[18.0][MIG] sale_tier_validation: Migration to 18.0
OCA/sale-workflow pull request #3417
Opened 2024-11-20 09:59 UTC by BertVGroenendael

2024-11-28 15:16 UTC, sheragar reviewed
Funtional Review: The workflow for sal_tier_validation is functioning correctly. 

However, the "Block Printing of Unvalidated Quotations" feature, located in Sales > Configuration > Settings, is currently unavailable. This feature restricts the ability to print a quotation until it has been validated.

2025-02-04 19:10 UTC, celm1990 requested changes
Please rebase the branch and remove the last commit, as PR https://github.com/OCA/server-ux/pull/992 has been merged, thanks

2025-02-04 19:10 UTC, celm1990 commented on test-requirements.txt
> +odoo-addon-base_tier_validation @ git+https://github.com/OCA/server-ux.git@refs/pull/966/head#subdirectory=base_tier_validation
Merged into https://github.com/OCA/server-ux/pull/992

2025-02-12 03:40 UTC, celm1990 commented on test-requirements.txt
> +odoo-addon-base_tier_validation @ git+https://github.com/OCA/server-ux.git@refs/pull/966/head#subdirectory=base_tier_validation
ping @BertVGroenendael

2025-02-12 18:46 UTC, StefanRijnhart requested changes
Indeed, as @sheragar mentions, please include https://github.com/OCA/sale-workflow/pull/3269 as it wasn't ported to 17.0 yet.

2025-02-25 08:33 UTC, Pani-k-folk commented
Hello, @BertVGroenendael  @StefanRijnhart 

 I have modified the test script and included the option to block sale order printing. Please help review it. 
 
PR :  https://github.com/DynAppsNV/sale-workflow/pull/1

Thank you.

2025-02-25 08:39 UTC, rousseldenis commented
@BertVGroenendael Thanks for this. Could you make appear module version change in migration commit instead of pre-commit one ?

Could you attend comments ?

2025-02-25 08:39 UTC, rousseldenis commented
/ocabot migration sale_tier_validation

2025-02-25 14:35 UTC, acsonefho approved these changes

2025-02-26 14:30 UTC, carlos-lopez-tecnativa commented
Sorry, but the user seems inactive. I created a new PR including https://github.com/OCA/sale-workflow/pull/3269
Superseded by https://github.com/OCA/sale-workflow/pull/3601

2025-02-26 14:42 UTC, closed without merging