[17.0][MIG] sales_team_security_crm: Migration to 17.0
OCA/sale-workflow pull request #3429
Opened 2024-11-25 19:08 UTC by lef-adhoc

2024-12-17 19:22 UTC, cvinh approved these changes
LGTM

2025-01-07 17:07 UTC, carlos-lopez-tecnativa requested changes
LGTM just a minor change

TT52441

@Tecnativa

2025-01-07 17:07 UTC, carlos-lopez-tecnativa commented on sales_team_security_crm/security/security.xml
> +        >['|', '|', ('user_id', '=', user.id), ('user_id', '=', False), '|', ('team_id', '=', user.sale_team_id.id),
I think this can be simplified to: What do you think?

```suggestion
        >['|', ('user_id', 'in', [user.id, False]), ('team_id', 'in', [user.sale_team_id.id, False]),
```

2025-01-07 17:07 UTC, carlos-lopez-tecnativa commented on sales_team_security_crm/security/security.xml
> +        >['|', '|', ('user_id', '=', user.id), ('user_id', '=', False), '|', ('team_id', '=', user.sale_team_id.id),
the same here

2025-01-08 22:36 UTC, cvinh requested changes

2025-01-08 22:36 UTC, cvinh commented on sales_team_security_crm/security/security.xml
> +        >['|', '|', ('user_id', '=', user.id), ('user_id', '=', False), '|', ('team_id', '=', user.sale_team_id.id),
Moreover, you must take into account the multi team that has been introduced in odoo v15. In that case, user.sale_team_id can be false if a user is in several teams (ie https://github.com/odoo/odoo/blob/b7abee1f64d6812d66c5ac61d1d8f841310c81d7/addons/sales_team/models/res_users.py#L32)
IMHO the correct rule should be  
['|', '|', ('user_id', 'in', [user.id, False]), ('team_id', 'in', [user.sale_team_id.id]), ('team_id', 'in', [user.crm_team_ids.ids])]

2025-01-08 22:36 UTC, cvinh commented on sales_team_security_crm/security/security.xml
> +        >['|', '|', ('user_id', '=', user.id), ('user_id', '=', False), '|', ('team_id', '=', user.sale_team_id.id),
same here
['|', '|', ('user_id', 'in', [user.id, False]), ('team_id', 'in', [user.sale_team_id.id]), ('team_id', 'in', [user.crm_team_ids.ids])]

2025-01-08 22:36 UTC, cvinh commented on sales_team_security_crm/security/security.xml
> +        <field name="domain_force">[('id', '=', user.sale_team_id.id)]</field>
and here
['|', ('id', '=', user.sale_team_id.id), ('id', 'in', [user.crm_team_ids.ids])]

2025-01-09 06:01 UTC, cvinh commented on sales_team_security_crm/security/security.xml
> +        >['|', '|', ('user_id', '=', user.id), ('user_id', '=', False), '|', ('team_id', '=', user.sale_team_id.id),
in our case, we did not want the users in Team Only group to access to leads without a user_id so we finally did
['|', '|', ('user_id', '=', user.id), ('team_id', '=', user.sale_team_id.id), ('team_id', 'in', user.crm_team_ids.ids)]

2025-01-09 08:30 UTC, pedrobaeza commented on sales_team_security_crm/security/security.xml
> +        >['|', '|', ('user_id', '=', user.id), ('user_id', '=', False), '|', ('team_id', '=', user.sale_team_id.id),
The original module should include leads without user.

2025-01-09 08:43 UTC, cvinh commented on sales_team_security_crm/security/security.xml
> +        >['|', '|', ('user_id', '=', user.id), ('user_id', '=', False), '|', ('team_id', '=', user.sale_team_id.id),
> The original module should include leads without user.

You are right considering that odoo standard has the same policy with crm (my document only includes lead without user)
Anyway, the rule can be customized after on.
But natively, please include crm_team_ids because if not, the rule does not work out of the box in multi-team configuration

2025-01-09 11:51 UTC, lef-adhoc commented on sales_team_security_crm/security/security.xml
> +        <field name="domain_force">[('id', '=', user.sale_team_id.id)]</field>
Wouldn't [('id', 'in', user.crm_team_ids.ids)] be enough?

2025-01-09 12:26 UTC, lef-adhoc commented
@pedrobaeza @cvinh 
How do you see it?
Do you know why the tests failed?

2025-01-09 16:40 UTC, lef-adhoc commented
@cvinh the tests fail with the domains you gave me, could you check it?

2025-01-09 17:41 UTC, cvinh commented
> @cvinh the tests fail with the domains you gave me, could you check it?

Humm there should be something to do in sales_team_security

2025-01-09 17:56 UTC, cvinh commented on sales_team_security_crm/tests/test_sales_team_security_crm.py
> +
Tests with the case multi-team should be added and see why this one fails

2025-01-09 17:57 UTC, cvinh commented
> @cvinh the tests fail with the domains you gave me, could you check it?

Can you commit again to see where it fails ?

2025-01-09 18:11 UTC, lef-adhoc commented
@cvinh The failure occurs in the following line https://github.com/adhoc-dev/sale-workflow/blob/4cd5e8211dceceece3b54121c9b0e6c7c7420e63/sales_team_security/tests/common.py#L88

2025-01-10 11:54 UTC, lef-adhoc commented
@cvinh I think that's it, I also added a multi-team test, what do you think?

2025-01-10 17:10 UTC, cvinh reviewed
I think if a user is in one team only, the crm_team_ids are empty
If I'm wrong then it's ok as you did

2025-01-10 17:10 UTC, cvinh commented on sales_team_security_crm/security/security.xml
> +        <field name="domain_force">[('id', 'in', user.crm_team_ids.ids)]</field>
```suggestion
        <field name="domain_force">['|', ('id', '=', 'user.team_id.id'), ('id', 'in', user.crm_team_ids.ids)]</field>
```

2025-01-15 14:31 UTC, lef-adhoc commented on sales_team_security_crm/security/security.xml
> +        <field name="domain_force">[('id', 'in', user.crm_team_ids.ids)]</field>
When there is only one team, crm_team_ids is not empty; it contains that single team

2025-01-17 19:45 UTC, lef-adhoc commented
@cvinh 
In this pr #3430 I have changed the domain to adapt it to multi team and added tests, what do you think ?

2025-01-28 16:24 UTC, carlos-lopez-tecnativa approved these changes
LGTM

2025-01-28 18:32 UTC, pedrobaeza commented
/ocabot migration sales_team_security_crm

2025-01-28 18:33 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2025-01-28 18:47 UTC, merged