9.0 sale order variant mgmt
OCA/sale-workflow pull request #343
Opened 2016-09-29 17:10 UTC by pedrobaeza

WIP until https://github.com/OCA/web/pull/427 is merged.

There are 2 pendings PRs from Odoo to make this completely worked. See known issues section.

===============================================
Handle easily multiple variants on Sales Orders
===============================================

This module allows to add/modify of all the variants of a product in a direct
screen without the need of handling them one by one

Configuration
=============

* Configure your user to have any permission from "Sales" group.
* Create a product with 2 attributes and several values.

Usage
=====

* Go to Sales > Sales > Quotations
* Create a new quotation or edit an existing one.
* Press "Add variants" button located in the upper right corner of the
  "Order Lines" tab.
* A new screen will appear allowing you to select the products that have
  variants.
* Once you select the product, a 2D matrix will appear with the first
  attribute values as columns and the second one as rows.
* If there are already order lines for the product variants, the current
  quantity will be pre-filled in the matrix.
* Change the quantities for the variant you want and click on "Transfer to
  order"
* Order lines for the variants will be created/removed to comply with the
  input you have done.

As extra feature for saving steps, there's also a button on each existing line
that corresponds to a variant that opens the dialog directly with the product
selected.

Known issues / Roadmap
======================

* The inline button for modifying quantities for an existing line won't
  work correctly until these 2 PRs are merged in Odoo:

  * https://github.com/odoo/odoo/pull/13558
  * https://github.com/odoo/odoo/pull/13635

  The corresponding OCB versions are in:

  * https://github.com/OCA/OCB/pull/547
  * https://github.com/OCA/OCB/pull/548

2016-09-30 12:50 UTC, pedrobaeza commented
@hbrunn, this is the module where the 2D matrix widget is used.

2016-09-30 12:50 UTC, pedrobaeza commented
cc @Tecnativa

2016-10-04 07:24 UTC, atchuthan approved these changes
Tested in Runbot :+1:

2016-10-04 08:03 UTC, atchuthan requested changes
On clicking the matrix button available in SO line, it produces a JS related error

**Odoo Client Error**
Uncaught TypeError: Cannot read property 'constructor' of undefined
http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/509-c58131e/web.assets_backend.js:3057
Traceback:
TypeError: Cannot read property 'constructor' of undefined
    at wrap_context (http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/509-c58131e/web.assets_backend.js:3057:7)
    at http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/509-c58131e/web.assets_backend.js:3061:127
    at iterator (http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/506-0b1c7ad/web.assets_common.js:14:183)
    at Function.<anonymous> (http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/506-0b1c7ad/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce](http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/506-0b1c7ad/web.assets_common.js:69:526)
    at eval_contexts (http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/509-c58131e/web.assets_backend.js:3059:136)
    at http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/509-c58131e/web.assets_backend.js:3061:253
    at iterator (http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/506-0b1c7ad/web.assets_common.js:14:183)
    at Function.<anonymous> (http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/506-0b1c7ad/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce](http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/506-0b1c7ad/web.assets_common.js:69:526)
    at eval_contexts (http://3155469-343-6ec67f.runbot2.odoo-community.org/web/content/509-c58131e/web.assets_backend.js:3059:136)

2016-10-04 08:06 UTC, pedrobaeza commented
@atchuthan, that's due to the related odoo bugs. Please see the README and the first comment in this PR.

2016-10-04 08:28 UTC, atchuthan commented
@pedrobaeza sorry, I missed the README and thanks for pointing out.

2016-10-12 15:59 UTC, StefanRijnhart approved these changes
Looks very useful!

2016-10-12 15:59 UTC, StefanRijnhart commented on sale_order_variant_mgmt/models/sale_order.py
> +    product_tmpl_id_sale_order_variant_mgmt = fields.Many2one(
Can you explain? The sale order line's product_tmpl_id is a related field on the line's product's template id, just like this one. Logic wise, it seems safe to assume the field is not customized further. What is the problem then with using this existing field?

2016-10-12 16:35 UTC, pedrobaeza commented on sale_order_variant_mgmt/models/sale_order.py
> +    product_tmpl_id_sale_order_variant_mgmt = fields.Many2one(
It's a long history: this field is used in product configurator modules that have a common abstract model using product_tmpl_id field as a regular field. sale_stock_screws up this, so I need to fix it through the glue module https://github.com/odoomrp/odoomrp-wip/tree/8.0/sale_stock_product_variants. I don't want to need another glue module, and as this is only a wildcard field, it doesn't matter the name.

2016-10-12 18:39 UTC, StefanRijnhart commented on sale_order_variant_mgmt/models/sale_order.py
> +    product_tmpl_id_sale_order_variant_mgmt = fields.Many2one(
Thanks for the clarification!

2016-10-12 18:39 UTC, merged