[18.0] [MIG] sale_order_line_menu: Migration to 18.0
OCA/sale-workflow pull request #3470
Opened 2024-12-07 14:39 UTC by Borruso

Migration from 17.0 to 18.0

Issue: https://github.com/OCA/sale-workflow/issues/3344

2024-12-09 16:06 UTC, Naraka commented
If you try to create a new order line within the form of an existing order line, it throws an error.

![Captura desde 2024-12-09 17-05-02](https://github.com/user-attachments/assets/54f3fe57-7293-459f-8e3f-5216402210ae)

2024-12-10 12:38 UTC, rousseldenis commented
/ocabot migration sale_order_line_menu

2024-12-11 12:19 UTC, sheragar approved these changes
LGTM. Funtional Review 👍

2024-12-12 14:59 UTC, Borruso commented
> If you try to create a new order line within the form of an existing order line, it throws an error.
> 
> ![Captura desde 2024-12-09 17-05-02](https://private-user-images.githubusercontent.com/162504457/393907612-54f3fe57-7293-459f-8e3f-5216402210ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTU4NDEsIm5iZiI6MTczNDAxNTU0MSwicGF0aCI6Ii8xNjI1MDQ0NTcvMzkzOTA3NjEyLTU0ZjNmZTU3LTcyOTMtNDU5Zi04ZTNmLTUyMTY0MDIyMTBhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxNDU5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjBhYzc5NjM1ODE0NGI2ZDNiMGU4MWMxYzRiODdiODM5OTZiM2JjOGQ1ZGFjOTk5NmQ5N2VlOWEwN2JhMGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4gDcltM2UBBD8DnMO4WLFGgDEB1svGSv6oZeqtilny4)

Can you check again?

2024-12-13 10:27 UTC, Naraka approved these changes
LGTM, tested in runboat

2024-12-18 06:56 UTC, Shide approved these changes
Code LGTM

2025-01-07 12:20 UTC, PieterPaulussen requested changes

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    <record id="sale_order_line_view_form_no_create" model="ir.ui.view">
```suggestion
    <record id="sale_order_line_view_form_readonly" model="ir.ui.view">
```
Should this not be kept the same name as the view it is inheriting from? As long as there is no XML naming collision, there's no real reason to change the name and conform to the OCA guidelines?

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    <record id="sale_order_line_list" model="ir.ui.view">
```suggestion
    <record id="view_order_line_tree" model="ir.ui.view">
```
Same as comment on line 5.

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="name">sale.order.line.list</field>
```suggestion
```
Can be omitted.

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="priority">17</field>
```suggestion
```
The priority should be removed as the inheritance will ensure proper loading order. It should only be specified when replacing content in the view.

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    <record id="sale_order_line_search" model="ir.ui.view">
```suggestion
    <record id="view_sales_order_line_filter" model="ir.ui.view">
```
Same comment as line 5.

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="name">sale.order.line.search</field>
```suggestion
```
Can be omitted.

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="priority">999</field>
```suggestion
        <field name="priority">101</field>
```
Should suffice

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +                <filter name="flt_date_order" string="Order Date" date="date_order" />
```suggestion
                <filter
                    name="filter_state_draft"
                    string="Quotation"
                    domain="[('state','=','draft')]"
                />
                <filter
                    name="filter_state_sent"
                    string="Quotation Sent"
                    domain="[('state','=','sent')]"
                />
                <filter
                    name="filter_state_sale"
                    string="Sales Order"
                    domain="[('state','=','sale')]"
                />
                <filter
                    name="filter_state_done"
                    string="Locked"
                    domain="[('state','=','done')]"
                />
                <filter
                    name="filter_state_cancel"
                    string="Cancelled"
                    domain="[('state','=','cancel')]"
                />
                <separator />
                <filter
                    name="filter_invoice_status_no"
                    string="Nothing to Invoice"
                    domain="[('invoice_status','=','no')]"
                />
                <filter
                    name="filter_invoice_status_upselling"
                    string="Upselling Opportunity"
                    domain="[('invoice_status','=','upselling')]"
                />
                <filter
                    name="filter_invoice_status_to_invoice"
                    string="To Invoice"
                    domain="[('invoice_status','=','to invoice')]"
                />
                <filter
                    name="filter_invoice_status_invoiced"
                    string="Fully Invoiced"
                    domain="[('invoice_status','=','invoiced')]"
                />
                <separator />
                <filter name="filter_date_order" string="Order Date" date="date_order" />
```
Abbreviations are never a really good idea since they make the code less readable.

2025-01-07 12:20 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    </record>
Can't this be compressed into 1 record? (Or is it some weird new v18 style thing?)

2025-01-09 09:27 UTC, Shide approved these changes

2025-01-10 09:23 UTC, Borruso commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    <record id="sale_order_line_view_form_no_create" model="ir.ui.view">
it's a copy of view `sale_order_line_view_form_readonly` with `mode: priority` but adding attribute `create: false`

2025-01-10 09:30 UTC, Borruso commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="priority">17</field>
it's tha same to v17

2025-01-10 09:31 UTC, Borruso commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    <record id="sale_order_line_search" model="ir.ui.view">
it's same to v17

2025-01-10 09:33 UTC, Borruso commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    </record>
it's pre-commit that change style

2025-01-10 09:34 UTC, Borruso commented on sale_order_line_menu/views/sale_order_line_views.xml
> +                <filter name="flt_date_order" string="Order Date" date="date_order" />
it's same to v17
you maybe change that after migration

2025-01-13 08:32 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="priority">17</field>
Whether or not its the same to V17 doesn't mean this minor change should not be implemented.

2025-01-13 08:38 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    <record id="sale_order_line_view_form_no_create" model="ir.ui.view">
I understand, but still, my comment stands. Your changes do not merit going against the naming convention.

2025-01-13 08:38 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="name">sale.order.line.list</field>
Why did you mark this as resolved when you did not implement it?

2025-01-13 08:38 UTC, PieterPaulussen commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="name">sale.order.line.search</field>
Feedback not implemented.

2025-01-13 08:47 UTC, Borruso commented on sale_order_line_menu/views/sale_order_line_views.xml
> +        <field name="priority">17</field>
yes but we can do after migration
what do you think?

2025-01-13 08:49 UTC, Borruso commented on sale_order_line_menu/views/sale_order_line_views.xml
> +    <record id="sale_order_line_view_form_no_create" model="ir.ui.view">
ok, i will change

2025-01-13 09:38 UTC, PieterPaulussen approved these changes
Thanks for the changes regarding my feedback. There are indeed other issues that need to be addressed in a different PR. But this will suffice for now. THanks.

2025-01-29 14:00 UTC, joepsanders commented
@PieterPaulussen is this PR ready for merging? What other issues need to be addressed? Could you point that PR? Thanks!

2025-01-29 14:02 UTC, PieterPaulussen commented
@joepsanders The PR has 4 approvals, including mine. I thinks it's safe to merge.

2025-01-29 14:14 UTC, pedrobaeza commented
Technically, a PSC should review it, no matter the number of approvals, but I see some respected contributors that have approved already, so merging:

/ocabot merge nobump

2025-01-29 14:20 UTC, merged