[18.0][MIG] partner_sale_pivot: Migration to 18.0
OCA/sale-workflow pull request #3485
Opened 2024-12-13 05:41 UTC by HeliconiaSolutions

2025-02-14 12:52 UTC, juancarlosonate-tecnativa approved these changes
LGTM, functional and code review

@Tecnativa @pedrobaeza TT54209

2025-02-14 12:52 UTC, juancarlosonate-tecnativa commented on partner_sale_pivot/views/sale_report_views.xml
> +    -->
maybe this should be removed

2025-02-17 05:21 UTC, HeliconiaSolutions commented on partner_sale_pivot/views/sale_report_views.xml
> +    -->
@juancarlosonate-tecnativa, please review.it's done.

2025-04-10 05:10 UTC, BhaveshHeliconia commented
Hey @OCA/crm-sales-marketing-maintainers  would be great if someone could have a look at this module.

2025-04-15 06:34 UTC, BhaveshHeliconia commented
Hey @OCA/crm-sales-marketing-maintainers would be great if someone could have a look at this module.

2025-06-02 15:48 UTC, DantePereyra requested changes
I think `README.rst`, `index.html`, and all the modifications introduced by `pre-commit `should be included in  dedicated commit  `[IMP] partner_sale_pivot: pre-commit auto fixes`. Meanwhile, the actual migration logic should go in a separate commit titled `[MIG] partner_sale_pivot: Migration to 18.0`.

2025-06-02 15:48 UTC, DantePereyra commented on partner_sale_pivot/views/sale_report_views.xml
> +        <field name="view_mode">pivot</field>
See migration notes (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0)
- `Whenever possible, define the field path on ir.actions.act_window records for a nicer URL.`

2025-06-03 04:53 UTC, BhaveshHeliconia commented
@DantePereyra : Please review again. Thanks.

2025-06-03 14:57 UTC, DantePereyra commented
LGTM. Could you try making a few small improvements to the test? It's currently not meeting the requirements on Codecov.

2025-06-05 10:21 UTC, BhaveshHeliconia commented
@DantePereyra,Thank you for the suggestion. Since this PR only involves a view definition aligned with Odoo's core structure and doesn't include any business logic or model changes, no test was added

2025-06-27 11:19 UTC, DantePereyra approved these changes

2025-06-27 13:07 UTC, marcelsavegnago approved these changes

2025-07-07 09:45 UTC, victoralmau approved these changes

2025-07-07 10:05 UTC, pedrobaeza commented
/ocabot migration partner_sale_pivot
/ocabot merge nobump

2025-07-07 10:18 UTC, merged