[18.0][MIG] sale_order_archive: Migration to 18.0
OCA/sale-workflow pull request #3487
Opened 2024-12-13 06:55 UTC by HeliconiaSolutions

2025-02-03 11:47 UTC, StefanRijnhart requested changes
Tested this module locally and while not a migration issue, there is a slightly dangerous flaw in this module: only done or cancelled orders can be archived, but once a cancelled order is archived, it can be reset to state draft. The order is still cancelled at that point. Can you make it so that cancelled orders cannot be reset to draft (hide button)?

2025-02-03 11:47 UTC, StefanRijnhart commented on sale_order_archive/models/sale_order.py
> +    active = fields.Boolean(default=True)
```suggestion
    active = fields.Boolean(copy=False, default=True)
```

2025-02-03 13:00 UTC, HeliconiaSolutions commented on sale_order_archive/models/sale_order.py
> +    active = fields.Boolean(default=True)
@StefanRijnhart , Thnaks for the suggestions! it's fixed can you review it?

2025-02-03 13:28 UTC, StefanRijnhart approved these changes
Thanks for the improvements!

2025-02-20 10:56 UTC, JessBrandl reviewed
Tested in Runboat and worked as intended, commented some minor issues

2025-02-20 10:56 UTC, JessBrandl commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
Potential performance improvement possible here according to the documentation: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0

> You can replace the call to translate a string ( _ ) with self.env._ for getting some performance improvement in some cases. See https://github.com/odoo/odoo/pull/174844.

2025-02-20 10:56 UTC, JessBrandl commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
Minor spelling mistake Canceled -> Cancelled

2025-02-20 10:56 UTC, JessBrandl commented on sale_order_archive/tests/test_sale_order_archive.py
> +        regex = r"Only 'Locked' or 'Canceled' orders can be archived"
Same as above: Minor spelling mistake Canceled -> Cancelled

2025-02-20 11:56 UTC, HeliconiaSolutions commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
@JessBrandl, Thanks for the suggestions!Please review.

2025-02-20 12:01 UTC, StefanRijnhart commented on sale_order_archive/tests/test_sale_order_archive.py
> +        regex = r"Only 'Locked' or 'Canceled' orders can be archived"
You need to pick a fight with @jbaudoux cause he's been asking to replace Cancelled by Canceled. FYI it's both correct, it's just that Canceled is more common in American English, and Cancelled is more common in British English.

2025-02-20 12:36 UTC, jbaudoux commented on sale_order_archive/tests/test_sale_order_archive.py
> +        regex = r"Only 'Locked' or 'Canceled' orders can be archived"
Indeed, we must use en_US terms. So it is `Canceled`

2025-02-20 12:37 UTC, jbaudoux commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
`Canceled` was right

2025-02-20 12:38 UTC, JessBrandl commented on sale_order_archive/tests/test_sale_order_archive.py
> +        regex = r"Only 'Locked' or 'Canceled' orders can be archived"
I see, I cross-compared it to the status seen on the quotations overview page, there it is written as "Cancelled". But as far as I can tell it is not consistent within Odoo overall. 
<img width="1203" alt="Cancelled" src="https://github.com/user-attachments/assets/3aa00542-4b9c-41b1-b2e1-896396fc93cf" />

2025-02-20 12:41 UTC, jbaudoux requested changes
Please do not do non migration changes in the migration commit.

Please revert to `Canceled`

2025-02-20 12:54 UTC, StefanRijnhart commented on sale_order_archive/tests/test_sale_order_archive.py
> +        regex = r"Only 'Locked' or 'Canceled' orders can be archived"
Yep, you'd expect Odoo to have en_US as its basis but actually it is leaning towards Cancelled.
```
~/odoo/18.0/odoo$ grep -i cancelled --exclude-dir=i18n * -r 2>/dev/null|wc -l 
761
~/odoo/18.0/odoo$ grep -i canceled --exclude-dir=i18n * -r 2>/dev/null|wc -l 
343
```
Maybe the point is that both options are not wrong, and we should not be asking for these trivial corrections during code review?

2025-02-20 13:00 UTC, StefanRijnhart commented
@jbaudoux matter of opinion. It seems fine to me to include trivial changes like spelling changes in the migration commit.

2025-02-20 17:33 UTC, CRogos commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
I agree with @jbaudoux . The odoo default should be en_US, and the GB should be in the en_GB.po translation file. (even though it is currently not always clean/consistent.)

2025-02-20 20:06 UTC, StefanRijnhart commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
Judging from the selection values on a database with all community modules installed, Odoo might actually have tried to standardize on `Cancelled`. Again, I would prefer if we just left this to the whim of each developer, but If we're going to be consistent across OCA modules, there is something to say to be in line with Odoo as well.
![image](https://github.com/user-attachments/assets/52e80595-a357-4e84-b2c8-1af6907bcabf)

2025-02-21 09:30 UTC, CRogos commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
I think cancel is really an edge case and I agree that there is no clear standard in Odoo when searching the code.

![image](https://github.com/user-attachments/assets/35d7de35-20f3-4c6f-b112-2ca3980a52b2)
![image](https://github.com/user-attachments/assets/cd593641-2191-4c73-be0d-624d9acea284)

Neverthless when you install a database, the selected language is also clear en-US:
![image](https://github.com/user-attachments/assets/ed5c438b-343d-410f-a56f-46b56325e6a4)

Therefore best practice should be using en-US and not en-GB in my opinion.

2025-02-21 09:46 UTC, StefanRijnhart commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
There is a difference in code occurrences and UI occurrences, which is why I think selection value labels give a better indication than code search.

2025-02-21 09:53 UTC, CRogos commented
@HeliconiaSolutions here are also some commits (I've marked all) which should be squashed: 
![image](https://github.com/user-attachments/assets/694c363f-fb70-49e2-88a8-0ad728a832b9)

oca-ci, oca-git-bot, weblate, ...

2025-02-21 10:11 UTC, StefanRijnhart commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
If we really want to make this productive, maybe you could try to get someone from Odoo to make a statement on the matter. Until then, we could refrain from asking contributors to make the change in OCA modules.

2025-02-21 11:44 UTC, CRogos commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
I'll open a ticket at Odoo, but I am not very optimistic.

2025-02-21 11:45 UTC, CRogos commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
@pedrobaeza how should we handle this in OCA? Is there a (strict) best practice regarding en_US/en_GB?

2025-02-21 12:14 UTC, StefanRijnhart commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
@CRogos To make it more concrete, you could try to quickly make a PR with all occurrences of Cancelled replaced by Canceled and see what the response is.

2025-02-21 12:48 UTC, pedrobaeza commented on sale_order_archive/models/sale_order.py
> +            raise UserError(_("Only 'Locked' or 'Canceled' orders can be archived"))
There's no strict guideline of this in OCA, as this is an edge case that didn't happen before. My take on this is indeed to go to "English (US)" form, as the header language variant is that one. We already have it in "Color", "Behavior", etc instead of "Colour" / "Behaviour". I think this specific problem is because Odoo developers are not so aware on this regional differences, and they put that in a similar way as a typo, and the corresponding dictionaries in their IDE don't warn them.

2025-02-21 13:56 UTC, jbaudoux approved these changes

2025-02-21 16:27 UTC, CRogos approved these changes

2025-02-26 06:26 UTC, StefanRijnhart commented
/ocabot migration sale_order_archive
/ocabot merge nobump

2025-02-26 06:33 UTC, merged