[18.0][MIG] sale_product_set_sale_by_packaging: Migration to 18.0
OCA/sale-workflow pull request #3494
Opened 2024-12-16 02:24 UTC by trisdoan

### Note
- depends on
    - 

### Changes in 18.0
- `can_be_sold` is now replaced by standard Odoo field: `sales`, which was introduced from 15.0 in https://github.com/odoo/odoo/pull/68654/commits/a2b207cdfe235d4a38ef332c47860e5b8a989d94
- `group_discount_per_so_line` was moved to module sale in here https://github.com/odoo/odoo/pull/153811/commits/82eb2b511683bd532de23af2434d36a3992b8d68
- Make `sell_only_by_packaging` **writable** in object ProductSetLine to bypass oca-ci test
    - Without this, CI is sad due to [this warning](https://github.com/odoo/odoo/blob/e33dd915c941befd579c9558ec7a1bf9858c0814/odoo/orm/models.py#L829) 
    - The field is solely used in constraint, and nowhere in view, which should be fine to make it writable
- `sale_by_packaging` was stopped to migrate since 15.0, `sell_only_by_packaging` was introduced to replace, in `https://github.com/OCA/sale-workflow/pull/2623`, which is migrated to 18.0 in

2024-12-30 23:11 UTC, jbaudoux reviewed
Shouldn't this module be renamed to `sale_product_set_sell_only_by_packaging` ?

And in regards of my comment https://github.com/OCA/sale-workflow/pull/3474#pullrequestreview-2525966895 maybe it should just be `product_set_sell_only_by_packaging` as I don't see any sales feature in this module

2024-12-30 23:11 UTC, jbaudoux commented on sale_product_set_sale_by_packaging/__manifest__.py
> +    "category": "Warehouse Management",
```suggestion
    "category": "Sales",
```

2024-12-30 23:11 UTC, jbaudoux commented on sale_product_set_sale_by_packaging/__manifest__.py
> +    Glue module between `sale_by_packaging` and `sale_product_set_packaging_qty`.
```suggestion
    Glue module between `sell_only_by_packaging` and `sale_product_set_packaging_qty`.
```

2024-12-30 23:11 UTC, jbaudoux commented on sale_product_set_sale_by_packaging/__manifest__.py
> +    "name": "Sale Product Set Sale by packaging",
```suggestion
    "name": "Sales Product set Sell only by packaging",
```

2024-12-31 03:29 UTC, trisdoan commented
> Shouldn't this module be renamed to `sale_product_set_sell_only_by_packaging` ?
> 
> And in regards of my comment [#3474 (review)](https://github.com/OCA/sale-workflow/pull/3474#pullrequestreview-2525966895) maybe it should just be `product_set_sell_only_by_packaging` as I don't see any sales feature in this module

Hello @jbaudoux, agreed, I renamed the module, thank you so much

2024-12-31 03:39 UTC, trisdoan commented
DRAFT: impact filenames + translation

2025-03-06 16:43 UTC, sebalix commented
Hello @trisdoan , I think there is an issue with the history contained in this PR? It includes also the code of `sale_force_invoiced` and `sale_order_type`. Can you fix it please?

2025-03-13 02:32 UTC, trisdoan commented
Hello @sebalix, I fixed it, please help to review :pray:

2025-03-25 13:45 UTC, twalter-c2c commented on product_set_sell_only_by_packaging/tests/test_product_set_packaging.py
> +from odoo.tests.common import TransactionCase
Wouldn't it be better to use the `BaseCommon` as the base test class?

2025-03-25 13:51 UTC, twalter-c2c commented on product_set_sell_only_by_packaging/i18n/es.po
> +# 	* sale_product_set_sale_by_packaging
I can see that the module name has been updated in the translation files, except this line. It should be updated as well, right?

2025-03-25 13:53 UTC, twalter-c2c reviewed
LG in general, small remarks to check.

2025-03-25 13:54 UTC, henrybackman approved these changes

2025-03-31 19:02 UTC, ivantodorovich requested changes

2025-03-31 19:02 UTC, ivantodorovich commented on product_set_sell_only_by_packaging/models/product_set_line.py
> +        related="product_id.sell_only_by_packaging", readonly=False
Are you sure about this `readonly=False` attribute here?

It will end up updating the product. It doesn't seem to be right, is it?

2025-04-10 08:06 UTC, trisdoan commented on product_set_sell_only_by_packaging/models/product_set_line.py
> +        related="product_id.sell_only_by_packaging", readonly=False
Yes you are right.

Instead, I updated the parameter of decorator constrains as below, which seems it's working
```
@api.constrains("product_id", "product_packaging_id")
    def _check_sell_only_by_packaging(self):
        ...
```

2025-04-10 08:11 UTC, twalter-c2c approved these changes

2025-04-11 14:03 UTC, simahawk commented
/ocabot merge nobump

2025-04-11 14:12 UTC, merged