[ADD] sale_order_type: change of analytical account by project
OCA/sale-workflow pull request #3500
Opened 2024-12-17 14:10 UTC by matiasperalta1

2024-12-19 07:41 UTC, nicolascol approved these changes
LGTM

2024-12-19 07:49 UTC, nicolascol commented
Hi @rvalyi !
Can you merge this PR?
We added the "project_id" because of the new analytic approach in v18.
[Odoo PR with new approach](https://github.com/odoo/odoo/pull/169868/)

2024-12-20 09:30 UTC, rousseldenis commented
@matiasperalta1 Could you rename your commit and this description as this is more correct: `[IMP] sale_order_type: Use project instead of analytic account on types`.

But, with this change, existing installs will loose data. It should contain migration scripts if possible.

2024-12-20 09:35 UTC, rousseldenis requested changes
But, IMHO, this is not correct as analytic account still exists.

This is a change of behavior as an analytic account is not a project. That's why you've added a new dependency from sale_project.

If you want to assign a project to the type, you should do a new module that allow that.

2024-12-20 16:03 UTC, nicolascol commented
Hi @rousseldenis 
The "analytic_account_id" field doesn't exist in sale.order v18, Odoo replaced it with "project_id". [More info](https://github.com/odoo/odoo/pull/169868/)
This PR was made to adapt sale_order_type to v18. In sale_order_type v17 an "analytic_account_id" could be configured. [In the v18 migration PR](https://github.com/OCA/sale-workflow/pull/3352) we were evaluating this change to adapt it but that PR was merged and that is why we are now making this new PR.

2025-02-03 09:36 UTC, StefanRijnhart reviewed
Can you add a migration script to assign the project with the `account_id` matching the original `analytic_account_id` values on the order types?

2025-02-03 09:36 UTC, StefanRijnhart commented on sale_order_type/views/sale_order_type_view.xml
> +                                groups="project.group_project_user,analytic.group_analytic_accounting"
Analogous to https://github.com/odoo/odoo/blob/18.0/addons/sale_project/views/sale_order_views.xml#L33, `project.group_project_user` seems enough here. Can you also take `context="{'default_allow_billable': True}"` here as well?

2025-02-03 09:48 UTC, StefanRijnhart commented on sale_order_type/models/sale_order_type.py
> +        help="Select to define the analytics account (new approach in v18)",
We don't need to add a changelog here.
```suggestion
        help="Select to define the analytics account",
```

Maybe add `check_company=True` here.

2025-10-20 16:55 UTC, StefanRijnhart commented on sale_order_type/views/sale_order_type_view.xml
> +                                groups="project.group_project_user,analytic.group_analytic_accounting"
@matiasperalta1 You resolved this comment (I prefer you leave it to the reviewer to resolve), but `groups` is still inconsistent with the project_id field on the sale order view.

2025-10-20 16:57 UTC, StefanRijnhart commented on sale_order_type/models/sale_order_type.py
> +        help="Select to define the analytics account (new approach in v18)",
Any type of company check between order type and project (like `check_company` on the old analytic account field)  still seems mising.

2025-11-20 10:49 UTC, rousseldenis commented
@matiasperalta1 Could you fix tests ?

2025-12-16 13:23 UTC, jjscarafia commented
@rousseldenis @StefanRijnhart @matiasperalta1 
As I understand:
1. the analytic_account_id is not used anymore, could be removed

2. if we want to add some new functionality related to "analytics" maybe we should add :
2a. add an "analytic_distribution" field (I believe this would be cleaner)
2b. or extends analytic distribution models to be able to map with types 

3. If there is need to set "project_id" by a sale order type (not linked to analytics need), I agree that a new module would be needed

What do you think of going  with "1" and "2a"?

2026-06-14 13:58 UTC, closed without merging