[MIG] sale_commercial_partner: Migration to 18.0
OCA/sale-workflow pull request #3504
Opened 2024-12-18 10:59 UTC by LucasTran380381

base on: `https://github.com/OCA/sale-workflow/pull/3415`

2024-12-18 11:14 UTC, StefanRijnhart approved these changes
Thanks!

2024-12-18 11:15 UTC, StefanRijnhart commented
/ocabot migration sale_commercial_partner

2024-12-18 11:15 UTC, StefanRijnhart commented
/ocabot migration sale_commercial_partner

2025-01-01 12:48 UTC, alexis-via requested changes
Please don't remove the inherit of sale.view_order_form that adds the field commercial_partner_id as invisible in the view. It's very convenient when you want to add (in another module) a field that has a domain that uses commercial_partner_id.

2025-01-01 13:45 UTC, StefanRijnhart commented
@alexis-via That's what I thought, but then @LucasTran380381 [pointed out](https://github.com/OCA/sale-workflow/pull/3415#discussion_r1867411779) correctly that Odoo will automatically add fields that are only used in domains and other attributes (as per https://github.com/odoo/odoo/pull/137031)

2025-01-01 23:53 UTC, alexis-via approved these changes

2025-01-01 23:54 UTC, alexis-via commented
/ocabot merge nobump

2025-01-01 23:59 UTC, merged