[10.0][Add][WIP] sale_manual_delivery
OCA/sale-workflow pull request #404
Opened 2017-02-09 12:42 UTC by leemannd

2017-02-09 12:48 UTC, yvaucher commented on sale_manual_delivery/wizard/line.py
> +class ManualProcurement(models.TransientModel):
ManualLine

2017-02-10 14:08 UTC, elicoidal requested changes
Light review about format as the module is on WIP process

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/README.md
> +Sale Manual Delivery
@leemannd   Thanks for your contribution to the OCA. 
Let me introduce to you some basic information about contribution in OCA and I will review other points in more comments inside the code.
In general, please follow the principles: 
* Contribution guidelines: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md
* Please follow the OCA README template:
https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
* We recommend to include a screenshot as well to help new comers (nice to have)
* Please use simple headers in all py files following OCA templates
https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/README.md
> +Sale Manual Delivery
in particular here: you need to add a line as document title

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/README.md
> +The Goal of this module is to allow the manual creation of delivery slips. If activated,
s/Goal/goal

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/README.md
> +=====
remove the 2 empty sections

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/README.md
> +If you spotted it first, help us smashing it by providing a detailed and welcomed feedback
Update according newest template

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/README.md
> +To contribute to this module, please visit http://odoo-community.org.
https

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/__manifest__.py
> +# -*- coding: utf-8 -*-
please add short headers

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/__manifest__.py
> +    'sequence': 150,
is it necessary?

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/__manifest__.py
> +    'demo': [
remove empty key

2017-02-10 14:08 UTC, elicoidal commented on sale_manual_delivery/models/procurement.py
> +    carrier_id = fields.Many2one(
this looks irrelevant in the current context (module for manual picking, no carrier id)

2017-02-10 16:48 UTC, leemannd commented on sale_manual_delivery/models/procurement.py
> +    carrier_id = fields.Many2one(
@elicoidal Thanks for the feedbacks. One of the goals of this manual delivery, is to separate the delivery from the sale. The sale order is made once in the beginning of the project. Then parts are shipped later and be specified with another carrier.

2017-02-11 00:34 UTC, elicoidal commented on sale_manual_delivery/models/procurement.py
> +    carrier_id = fields.Many2one(
@leemannd Then maybe you can add it to the module README to understand it better?

2017-02-16 11:29 UTC, jgrandguillaume commented
Hi,

I've functionally reviewed this module and made some improvements on the general usage, tests and flow. It has now a smooth way of dealing with manual delivery creation. It inform the user of the already created delivery and controls that he makes no mistakes (e.g. ship more than ordered).

On my side, I'm :+1: 

Regards,

Joël

2017-02-16 11:29 UTC, jgrandguillaume approved these changes
Functional review ok

2017-04-06 20:21 UTC, jbeficent commented
@leemannd very nice and useful. Would be great to have it also in purchases. Only when the supplier confirms what is incoming will users create the appropiate incoming shipments , to match whst the supplier confirms as being shipped.

2017-04-07 07:18 UTC, leemannd commented
@elicoidal It has been updated

2017-04-09 01:54 UTC, elicoidal approved these changes

2017-04-09 01:54 UTC, elicoidal commented on sale_manual_delivery/README.rst
> +a sale order won't direcly impact directly the stock. It will not make a reservation on the stock.
directly is duplicated

2017-04-20 08:49 UTC, AaronHForgeFlow reviewed
Edited: dismissed comment

2017-04-20 08:49 UTC, aheficent commented on sale_manual_delivery/README.rst
> +
I miss the usage section here

2017-04-20 08:49 UTC, aheficent commented on sale_manual_delivery/wizard/manual_proc_view.xml
> +              name='Create Manual Delivery'
I'm not sure if this is good. I'm getting a singleton error when I select more than one SO in the list view and then I click on the action.

2017-04-20 12:45 UTC, leemannd commented on sale_manual_delivery/wizard/manual_proc_view.xml
> +              name='Create Manual Delivery'
@aheficent Hello, Thank you for your feedback.
The wizard was intended to be launched from the SO and not from many. Currently I don't have the time to make improvements to this PR, but you can submit your idea. I'll be happy to review and include your commits into this PR.

2017-05-30 14:04 UTC, aheficent commented on sale_manual_delivery/wizard/manual_proc_view.xml
> +              name='Create Manual Delivery'
Hello @leemannd sorry for the late reply. I'll create a PR to your branch then.

2018-01-11 14:58 UTC, yvaucher commented
2 errors in tests:

```
FAIL: test_00_sale_manual_delivery (odoo.addons.sale_manual_delivery.tests.test_manual_delivery.TestSaleStock)
` Test SO's manual delivery
Traceback (most recent call last):
`   File "/home/travis/build/OCA/sale-workflow/sale_manual_delivery/tests/test_manual_delivery.py", line 53, in test_00_sale_manual_delivery
`     should be created after "manual delivery" wizard call')
` AssertionError: stock.picking() is not true : Sale Manual Delivery: picking             should be created after "manual delivery" wizard call
FAIL: test_02_sale_various_manual_delivery (odoo.addons.sale_manual_delivery.tests.test_manual_delivery.TestSaleStock)
` Test SO's various manual delivery
Traceback (most recent call last):
`   File "/home/travis/build/OCA/sale-workflow/sale_manual_delivery/tests/test_manual_delivery.py", line 165, in test_02_sale_various_manual_delivery
`     should be created after "manual delivery" wizard call')
` AssertionError: stock.picking() is not true : Sale Manual Delivery: picking             should be created after "manual delivery" wizard call
FAILED
Module sale_manual_delivery: 2 failures, 0 errors
```

2019-09-16 11:28 UTC, aheficent commented
I just tested this module again and I think it works ok. Some minor issues found but can be easily fixed:

- Got error when trying to create the delivery for more than one SO. A warning message to the user telling that the operation is not allowed should be ok for me.

- If I cancel the SO and then I set it back to draft and then confirm the SO again. Then, when I create the deliveries those are not linked to the sale order, but they are actually created.

- The commented CI thing

@leemannd  I think it is worth it to move forward with this Pull Request. I will try to fix it if are good with that.

Regards.

2019-09-20 13:17 UTC, leemannd commented
@aheficent Thanks for the review and time taken. I had currently no time allowed to work on it :(
IMO we should close this in favor of your PR

2019-09-26 21:23 UTC, closed without merging