10.0 mig sale exception
OCA/sale-workflow pull request #409
Opened 2017-02-14 13:31 UTC by mourad-ehm

I proposed an issue to split this module on 2 modules (see #408).

2017-03-13 13:44 UTC, mourad-ehm commented
77This PR depends on this one #775.

2017-03-14 13:34 UTC, mourad-ehm commented
The commit  362d2e4 must be removed before merging this PR.

2017-03-14 18:39 UTC, florian-dacosta commented
Travis is still red.
Also, you should update the README file (description is a bit outdated, version number is wrong...)
Also some 'openerp' should be replaced by 'odoo' both in python file for import and in xml files

2017-03-22 11:30 UTC, bealdav commented on sale_exception/__manifest__.py
>   'author': "Akretion, Sodexis, Odoo Community Association (OCA)",
Add Camptocamp

2017-03-22 13:41 UTC, mourad-ehm commented
Hi @angelmoya could you review this PR. Thanks

2017-03-22 14:40 UTC, angelmoya reviewed
Only few comments, I will check it runbot.

2017-03-22 14:40 UTC, angelmoya commented on sale_exception/README.rst
> +10.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
Best to use short version, check template on mantainer tools

2017-03-22 14:40 UTC, angelmoya commented on sale_exception/__manifest__.py
> + 'version': '10.0.2.0.0',
why 10.0.2.0.0 and not 10.0.1.0.0?

2017-03-22 14:51 UTC, mourad-ehm commented on sale_exception/__manifest__.py
> + 'version': '10.0.2.0.0',
10.0.2.0.0  because the orgin sale_exception was  splited into 2 modules

2017-03-22 15:00 UTC, bealdav commented
:+1:

2017-03-22 16:26 UTC, sebastienbeau requested changes

2017-03-22 16:26 UTC, sebastienbeau commented on .travis.yml
> +  - git clone https://github.com/akretion/server-tools.git ${HOME}/server-tools-base_exception -b 10.0-add-base_exception
As the main PR is merge can you remove it https://github.com/OCA/server-tools/pull/775

2017-03-22 16:26 UTC, sebastienbeau commented on oca_dependencies.txt
> +server-tools-ak https://github.com/akretion/server-tools.git 10.0-add-base_exception
same here

2017-03-23 09:02 UTC, mourad-ehm commented on oca_dependencies.txt
> +server-tools-ak https://github.com/akretion/server-tools.git 10.0-add-base_exception
OK

2017-03-27 10:27 UTC, mourad-ehm commented
Hi @sebastienbeau , I maked the change. Could you have a look please ?

2017-04-07 10:27 UTC, sebastienbeau approved these changes

2017-04-07 10:29 UTC, sylvainc commented
LGTM (code review) :+1:

2017-04-07 10:34 UTC, merged

2017-04-07 10:58 UTC, pedrobaeza commented
Next time, please squash all the "OCA Transbot commit" according to this guide https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2017-04-10 07:04 UTC, mourad-ehm commented
I w'll do it.