[MIG 10] sale team invoice partner
OCA/sale-workflow pull request #426
Opened 2017-03-08 14:47 UTC by EBII

2017-04-06 13:55 UTC, mourad-ehm commented
This module can be replaced by the module module sale_covenant https://github.com/OCA/sale-workflow/pull/432.

2017-05-30 08:38 UTC, rafaelbn commented
Hi @EBII , we are reviewing PRs from de OCA Sprint code, could please review this PR? Runbot is in red

2017-05-31 10:20 UTC, antoniocanovas approved these changes
Ok funcionality.
Congratulations, it's a good idea for some requirements !!

2017-05-31 10:24 UTC, rafaelbn approved these changes
Tested functionaly 👍

2017-05-31 10:59 UTC, yajo requested changes
Some remarks.

2017-05-31 10:59 UTC, Yajo commented on sale_team_invoice_partner/README.rst
> +The value of this field will be used when you create a new Sale Order with this sales team.
Missing usage instructions.

2017-05-31 10:59 UTC, Yajo commented on sale_team_invoice_partner/config/sale_config.yml
> +  !python {model: sale.config.settings}: |
Oh noes! 😱 Yaml tests? Please use Python unit tests if possible.

2017-05-31 10:59 UTC, Yajo commented on sale_team_invoice_partner/demo/sale.xml
> +        <record model="res.partner" id="base.akretion_customer">
Why do you write to a `base` namespace?

2017-05-31 10:59 UTC, Yajo commented on sale_team_invoice_partner/sale.py
> +#   Copyright (C) 2015 Akretion (http://www.akretion.com).
2015, really? 🤔

2017-05-31 10:59 UTC, Yajo commented on sale_team_invoice_partner/sale.py
> +                })
DRY: Put this logic in a method called by both `create` and `update`.

OTOH, wouldn't it make sense to add all this on a `onchange` and/or as a default value instead?

2017-05-31 10:59 UTC, Yajo commented on sale_team_invoice_partner/sale.py
> +                self.team_id.team_partner_invoice_id
Drop this method. It is a related field, so this is not needed.

2017-05-31 10:59 UTC, Yajo commented on sale_team_invoice_partner/sale_view.xml
> +                    <attribute name="attrs">{'readonly':[('section_partner_invoice_id','!=', False)]}</attribute>
Do you really want to forbid changing the partner?
Did you mean `team` instead of `section`?

2017-05-31 10:59 UTC, Yajo commented on sale_team_invoice_partner/sales_team.py
> +    team_partner_invoice_id = fields.Many2one(
We are already in the team, so no need for the `team_` prefix.

2020-04-28 06:53 UTC, rousseldenis commented
@EBII Could you attend comments ? Or this will be closed due to inactivity?

2020-06-24 20:25 UTC, rousseldenis commented
Closing this as no activity. Feel free to reopen it. Please take car of your PR's.

2020-06-24 20:25 UTC, closed without merging