[10.0][ADD] sale_three_discounts module
OCA/sale-workflow pull request #437
Opened 2017-03-27 15:58 UTC by tafaRU

This PR is still WIP according to its label.

2017-03-27 16:00 UTC, pedrobaeza commented
Please avoid plurals. What about sale_triple_discount?

Isn't any product_pricelist_triple_discount?

2017-03-27 16:26 UTC, tafaRU commented
@pedrobaeza I think it's better 'sale_triple_discount' than 'product_pricelist_triple_discount' as the module doesn't involve pricelist.

2017-03-27 22:41 UTC, elicoidal requested changes
I miss UT. some questions and minor changes

2017-03-27 22:41 UTC, elicoidal commented on sale_triple_discount/README.rst
> +* ADHOC SA
If this is the author, it is already in the manifest and no need to repeat here the name

2017-03-27 22:41 UTC, elicoidal commented on sale_triple_discount/models/account_invoice_line.py
> +            line.discount = 100.0 - (discount_factor * 100.0)
you allow negative discounts: is it desired?

2017-03-27 22:41 UTC, elicoidal commented on sale_triple_discount/models/sale_order_line.py
> +        states={'draft': [('readonly', False)], 'sent': [('readonly', False)]}
why control here and not in invoice lines?

2017-03-27 22:41 UTC, elicoidal commented on sale_triple_discount/models/sale_order_line.py
> +            line.discount = 100.0 - (discount_factor * 100.0)
same remark as above

2017-03-27 22:41 UTC, elicoidal commented on sale_triple_discount/views/sale_order_view.xml
> +        <field name="name">sale.order.three_discounts.form.inh</field>
'inh' stands for?

2017-03-27 22:42 UTC, elicoidal commented on sale_triple_discount/views/account_invoice_view.xml
> +        <field name="name">account.invoice.three_discounts.form</field>
adapt the name to the newer module name

2017-03-27 22:43 UTC, elicoidal commented on sale_triple_discount/i18n/es.po
> +#. module: sale_three_discounts
you will have to adapt

2017-03-28 07:31 UTC, pedrobaeza commented
What I mean is that I would expect also a module called `product_pricelist_triple_discount` with the possibility to set the 3 discounts in pricelists.

2017-03-28 08:00 UTC, tafaRU commented on sale_triple_discount/models/account_invoice_line.py
> +            line.discount = 100.0 - (discount_factor * 100.0)
@elicoidal, you mean discount[123]?

2017-03-28 08:30 UTC, tafaRU commented on sale_triple_discount/models/sale_order_line.py
> +        states={'draft': [('readonly', False)], 'sent': [('readonly', False)]}
@elicoidal, because invoice fields are already editable only in state draft.

2017-03-28 08:32 UTC, tafaRU commented on sale_triple_discount/models/account_invoice_line.py
> +            line.discount = 100.0 - (discount_factor * 100.0)
@elicoidal, we prefer to keep it as they are anyway.

2017-03-28 08:34 UTC, tafaRU commented
@elicoidal, your comments should have been addressed. Thanks!

2017-03-28 09:41 UTC, elicoidal commented on sale_triple_discount/models/account_invoice_line.py
> +            line.discount = 100.0 - (discount_factor * 100.0)
ok (this is the standard Odoo behavior as well)

2017-03-28 09:42 UTC, elicoidal commented on sale_triple_discount/models/sale_order_line.py
> +        states={'draft': [('readonly', False)], 'sent': [('readonly', False)]}
ok: thanks for clarifying

2017-03-28 09:42 UTC, elicoidal approved these changes

2017-04-04 21:35 UTC, jjscarafia commented
@tafaRU Please check this [modification](https://github.com/ingadhoc/sale/pull/71) that fix a compatibility for discounts on purchase invoices.
We are also thinking on a purchase_triple_discount module that extends to purchase orders and purchase invoices.

2017-04-07 12:42 UTC, eLBati requested changes
tested on tunbot:
 - open a new sale order
 - add a line
 - try to change discount 1
discount 1 is always set back to 0
If I set the default value on partner, the value is kept

2017-04-08 16:31 UTC, tafaRU commented
@eLBati, fixed, thanks!

2017-04-08 16:50 UTC, tafaRU commented
@jjscarafia,

thanks for pointing it out, I think the changes related to https://github.com/ingadhoc/sale/pull/71 are more appropriate in a module such as purchase_triple_discount, though.

2017-04-10 07:15 UTC, eLBati commented
@tafaRU try the following steps:
 - Add a new sale order line
 - Select '[CARD] Graphics Card' product
 - Set 10 in 'discount 1 (%)'
 - Go to 'unit price' field and set '100'

'Discount 1 (%)' is 10 and 'Discount (%)' is 0

I see 2 ways: if the user is suppsed to re input discounts , the 3 discounts fields must be set to 0.
Otherwise, better, 'discount (%)' should be recomputed according to new values

2017-04-11 10:44 UTC, tafaRU commented
@eLBati, fixed again, please check it!

2017-04-11 11:06 UTC, jjscarafia commented
@tafaRU I've not address the changes proposed here https://github.com/ingadhoc/sale/pull/71/files in a purchase_... module because I would add dependency for purchase module.I think thas modification is needed in this PR because if not you won't be able to record a supplier invoice with discounts (no matter you use purchase module or not).

And yes, we would like also to work in a module "purchase_triple_discount" that allows to define 3 discounts on purchase order and supplier invoices.

2017-04-11 13:04 UTC, tafaRU commented
@jjscarafia, ok, thanks for the clarification!
I also see https://github.com/ingadhoc/sale/commit/b86aaac76f4c465019f184b453ca31640d2a6da8 why you chose to log instead to raise an error?
Could you please make a PR against my branch containing all changes you would include?

2017-04-19 09:04 UTC, eLBati commented
@tafaRU please also fix tests

2017-05-30 08:27 UTC, rafaelbn commented
Hi @tafaRU , we are reviewing, please take a look here, travis fails and @guewen comment is pending! Thanks

2017-06-23 14:54 UTC, tafaRU commented
@rafaelbn, @eLBati: I'm working on fixing the tests.

2017-06-26 07:59 UTC, tafaRU commented
@eLBati, @rafaelbn: after https://github.com/OCA/sale-workflow/pull/437/commits/b42040e081c5ba6eba92243623be494ba59dcaf3 Travis looks green. Can we merge it?

2017-06-26 15:00 UTC, eLBati approved these changes

2017-06-26 15:56 UTC, tafaRU commented
@rafaelbn, could you please merge it?

2017-06-27 13:40 UTC, MiquelRForgeFlow approved these changes
LGTM :+1:

2017-06-27 14:32 UTC, jjscarafia requested changes
To avoid some error we have change the approach on the original module so discount field is not computed, instead we write it with ochange and constraint decorator, please check [here](https://github.com/ingadhoc/sale/blob/9.0/sale_three_discounts/models/account_invoice.py)

To replicate the error:
1) create new invoice
2) add a line with unit price 100, discount 50% and tax 15%
3) Save, the discount is not applied to the tax (tax is 15 and should be 7,5) (check image attached).

The approach on the link solve this issue and some issues we also have before


![seleccion_064](https://user-images.githubusercontent.com/3016656/27593000-67a71fc0-5b2c-11e7-9646-4dd7a450343c.png)

2017-06-27 14:35 UTC, jjscarafia commented
@tafaRU please check my comment, sorry for the late feedback, we have make this change a few weeks ago and it is on production and working fine.
We haven't done that change on [sale orders](https://github.com/ingadhoc/sale/blob/9.0/sale_three_discounts/models/sale.py#L26) but we would and should

2017-07-01 19:14 UTC, rafaelbn commented
@tafaRU could you please review https://github.com/OCA/sale-workflow/pull/437#pullrequestreview-46567065 from @jjscarafia ? Thanks

2017-07-17 15:58 UTC, chienandalu approved these changes
Functional and code review. Just two minor comments.

2017-07-17 15:58 UTC, chienandalu commented on sale_triple_discount/models/account_invoice_line.py
> +import openerp.addons.decimal_precision as dp
Why not import `odoo.addons.decimal_precision as dp`?

2017-07-17 15:58 UTC, chienandalu commented on sale_triple_discount/models/sale_order_line.py
> +import openerp.addons.decimal_precision as dp
Why not import `odoo.addons.decimal_precision as dp`?

2017-07-17 16:26 UTC, pedrobaeza requested changes
:-1: in this form. Invoice discounts should go in a module in OCA/account-invoicing called __account_invoice_triple_discount__, as if we want to reuse this for purchase we must depend on sale, which is a nonsense.

2017-07-17 16:26 UTC, pedrobaeza commented on sale_triple_discount/models/account_invoice_line.py
> +    discount1 = fields.Float(
Don't redefine this. Use normal discount instead.

2017-07-17 16:26 UTC, pedrobaeza commented on sale_triple_discount/models/account_invoice_line.py
> +    discount = fields.Float(
Don't change this to computed

2017-07-17 16:26 UTC, pedrobaeza commented on sale_triple_discount/models/res_partner.py
> +    default_discount1 = fields.Float('Default Discount 1 (%)')
This is another feature. Don't should be in this module.

2017-08-29 09:54 UTC, tafaRU commented
@pedrobaeza, I understand your reasons, expecially in the light of https://github.com/OCA/account-invoicing/tree/10.0/account_invoice_triple_discount, but considering we have already installed this module in some production database of our customers, we prefer to keep it as is to avoid further effort.

I would close this then.

2017-08-29 10:22 UTC, pedrobaeza commented
OK, as you wish, but I think we can make compatible both. What are your critical points?

2017-09-07 10:15 UTC, pedrobaeza commented
Closing according https://github.com/OCA/sale-workflow/pull/437#issuecomment-325614967 in favor of #525. We have respected the commits there any way.

2017-09-07 10:15 UTC, closed without merging

2017-09-08 12:35 UTC, tafaRU commented
> We have respected the commits there any way.

Thank you so much! You are real gentlemen :bowtie:

2017-09-08 12:49 UTC, pedrobaeza commented
:smiley: