[10.0][MIG] port sale_invoice_auto_deliver to 10.0
OCA/sale-workflow pull request #469
Opened 2017-05-12 11:17 UTC by Cedric-Pigeon

Migration unmerged PR https://github.com/OCA/sale-workflow/pull/280 on 8.0 to 10.0

2017-05-30 14:07 UTC, antoniocanovas commented
Testing in #ocacodesprint
Everything works fine but the "done quantity" which is not updated after invoicing:
 
<img width="856" alt="captura de pantalla 2017-05-30 a las 16 02 51" src="https://cloud.githubusercontent.com/assets/8323017/26587239/0ffdd268-4552-11e7-9beb-f148cd136ec9.png">

2017-05-31 08:41 UTC, Cedric-Pigeon commented
@rafaelbn @antoniocanovas bug fixed and I extended tests.

2017-06-09 12:47 UTC, Cedric-Pigeon commented
@rafaelbn Could you please remove the need fixing  as I fixed the bug

2018-12-03 16:41 UTC, lmignon approved these changes
@OCA/crm-sales-marketing-maintainers Is it possible to merge this one. It's in production from months...

2018-12-03 16:45 UTC, pedrobaeza commented
Isn't this overlapping somehow with `sale_automatic_workflow`?

2018-12-03 20:46 UTC, Cedric-Pigeon commented
@pedrobaeza Not really. This addons adds an option to confirm the deliver order in the same time you generate the invoice. It is not automatic, it is on demand through the standard invoicing wizard

2018-12-03 21:07 UTC, pedrobaeza commented
But the same effect can be got with the other module, acting on sales order confirmation. The only difference is that you trigger everything together. Has to be in a different moment in time?

2018-12-03 21:11 UTC, Cedric-Pigeon commented
Yes but the use case is different. They prepare the goods and we the customer comes to pick it up  they gave it to him. They generate the invoice to get payment and confirm the stock ongoing in a while.
i agree the endpoint is the same but the way to go is different

2018-12-03 21:13 UTC, pedrobaeza commented
OK, then let's go ahead with this. Do you want to keep both commits?

2018-12-04 05:39 UTC, Cedric-Pigeon commented
@pedrobaeza I squashed last commit. Thanks

2018-12-04 08:58 UTC, pedrobaeza requested changes
Sorry for this late review, but when I was going to merge, I see an incorrect README. Can you please fix it for merging?

2018-12-04 08:58 UTC, pedrobaeza commented on sale_invoice_auto_deliver/README.rst
> +* Go to ...
There are no usage instructions. Remove this section if empty or move part of the main description that are usage instructions.

2018-12-04 08:58 UTC, pedrobaeza commented on sale_invoice_auto_deliver/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/167/8.0
Incorrect link. Maybe you should switch to new README by fragments system.

2018-12-04 08:58 UTC, pedrobaeza commented on sale_invoice_auto_deliver/README.rst
> +To install this module, you need to:
These instructions are useless, so better to remove them.

2018-12-04 09:09 UTC, Cedric-Pigeon commented
@pedrobaeza You are absolutely right. I just reworked this part and switched to fragments system

2018-12-04 16:02 UTC, pedrobaeza commented
One last thing to make Travis happy:
```
sale_invoice_auto_deliver/readme/USAGE.rst:6: [E7901(rst-syntax-error), ]  Definition list ends without a blank line; unexpected unindent.
 ```

2018-12-04 23:24 UTC, pedrobaeza approved these changes

2018-12-04 23:24 UTC, merged