FIX sale_order_type in multi company env
OCA/sale-workflow pull request #487
Opened 2017-06-01 14:22 UTC by eLBati

In a multi company env, when partners are shared between companies, default order type configured on partner should be variable according to the current company,
just like receivalbe and payable accounts.

2017-06-05 12:00 UTC, andhit-r requested changes
Code review looks good. Waiting for green travis.

2017-06-06 11:40 UTC, rafaelbn commented
Hi @eLBati could you review travis? it says ` test_flake8                 FAIL`

2017-06-06 11:45 UTC, rafaelbn approved these changes
Just please resolve travis , thanks!

2017-06-06 17:10 UTC, eLBati commented
@andhit-r @rafaelbn fixed, thanks.

2017-06-09 13:17 UTC, rafaelbn commented
Hi @andhit-r , this is ready to merge please, thanks!

2017-06-10 18:04 UTC, andhit-r approved these changes
LGTM

2017-06-12 16:51 UTC, merged