[ADD] sale_procurement_group_by_requested_date v9
OCA/sale-workflow pull request #495
Opened 2017-06-15 07:04 UTC by darshan-serpent

Sale Procurement Group by Requested date
========================================

- This module creates different procurements groups for different requested
dates in a sale order line when the sale order is confirmed.
- It depends on sale_sourced_by_line so this module will group procurements also
by the warehouse in the sale order line.

2017-06-15 07:05 UTC, darshan-serpent commented
@aheficent Could you please review?

2017-06-15 08:04 UTC, AaronHForgeFlow reviewed
Functional test + code are good to me. Travis is failing because of test_sale_exception in sale_exception. @darshan-serpent Can you check?

2017-06-15 08:07 UTC, darshan-serpent commented
@aheficent Sure will take a look at the reason of travis annoyance

2017-06-15 09:46 UTC, darshan-serpent commented
Resolved travis and squashed the commits!

2017-06-15 10:23 UTC, AaronHForgeFlow approved these changes
:+1: Functional review

2017-06-16 08:15 UTC, LoisRForgeFlow requested changes
Code review - some comments inline

2017-06-16 08:15 UTC, lreficent commented on sale_procurement_group_by_requested_date/README.rst
> +* Confirm the sale order
I tend to prefer numbered lists here.

2017-06-16 08:15 UTC, lreficent commented on sale_procurement_group_by_requested_date/__openerp__.py
> +    "author": "Eficent Business and IT Consulting Services S.L., "
Just `Eficent` would be enough

2017-06-16 08:15 UTC, lreficent commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +                                        group_id=False, context=None):
Adapt to new api please

2017-06-16 08:15 UTC, lreficent commented on sale_procurement_group_by_requested_date/tests/test_sale_procurement_group_by_requested_date.py
> +        SOL = self.env['sale.order.line']
these two variables should be in lowercase.

2017-06-16 11:05 UTC, darshan-serpent commented on sale_procurement_group_by_requested_date/__openerp__.py
> +    "author": "Eficent Business and IT Consulting Services S.L., "
Isn't it better to have the full name?! 

As it is not even going beyond the limited characters for the author key

2017-06-16 11:16 UTC, lreficent commented on sale_procurement_group_by_requested_date/__openerp__.py
> +    "author": "Eficent Business and IT Consulting Services S.L., "
For the headers it's fine but this is shown in the form view of apps in odoo, and due to large length of our company name sometimes OCA is not shown properly and we really want to show OCA as author in the module description.

2017-06-16 11:17 UTC, lreficent commented on sale_procurement_group_by_requested_date/__openerp__.py
> +    "author": "Eficent Business and IT Consulting Services S.L., "
with OCA I mean "Odoo Community Association (OCA)" which is always the last author in the list.

2017-06-16 11:20 UTC, lreficent commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +        if self.requested_date:
previously it was `line.requested_date:` I think that was refering to `sale.order.line` while `self` here is `sale.order`. Also, are you sure about removing `order` and `line` from the imputs? they might be needed in the super call.

2017-06-16 11:26 UTC, darshan-serpent commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +        if self.requested_date:
The method earlier was as per the older version

Now, self is referring to the sale order lines and the parameters used are as per [newer version](https://github.com/odoo/odoo/blob/9.0/addons/sale/sale.py#L565).

2017-06-16 11:30 UTC, aheficent commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +        if self.requested_date:
@darshan-serpent you placed that method in the class SaleOrder, right?

2017-06-16 11:45 UTC, darshan-serpent commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +        if self.requested_date:
Yes moved the method to the right place :)

2017-06-19 06:24 UTC, darshan-serpent commented
All green!! I think now it is good to go, so could you please check it once again??

@aheficent @lreficent

2017-06-19 08:16 UTC, LoisRForgeFlow approved these changes
Code review of changes from my last review - LGTM :+1:

2017-06-19 08:46 UTC, AaronHForgeFlow approved these changes
It works smoothly :+1:

2017-06-22 10:23 UTC, MiquelRForgeFlow approved these changes
LGTM :+1:

2017-06-22 10:39 UTC, merged