9.0 sale oder line sequence
OCA/sale-workflow pull request #499
Opened 2017-06-23 10:30 UTC by darshan-serpent

Sale Order Line with Sequence
=============================

Adds sequence to display in Sales Order line.

2017-06-23 10:30 UTC, darshan-serpent commented
@aheficent Could you please review this?

2017-06-23 11:30 UTC, AaronHForgeFlow requested changes

2017-06-23 11:30 UTC, aheficent commented on sale_order_line_sequence/README.rst
> +
Can you also explain you can change see and change the sequence in the sale order line? This is a new feature.

2017-06-23 11:30 UTC, aheficent commented on sale_order_line_sequence/model/sale_order.py
> +                               store=True)
This field is not showing in the sale order line, in runbot

2017-06-23 11:30 UTC, aheficent commented on sale_order_line_sequence/model/sale_order.py
> +                              default=9999)
I can change the sequence of a confirmed sale order. I think this should not be allowed. And if that were allowed the sequence in the picking and in the invoice should change accordingly.

2017-06-23 11:30 UTC, aheficent commented on sale_order_line_sequence/__openerp__.py
> +        "stock_picking_line_sequence",
I don't see any code to transfer the sequence to the invoice and the pickings. This module is not using the dependencies to` account_invoice_line_sequence` and `stock_picking_line_sequence`

2017-06-23 11:31 UTC, aheficent commented
Also, can you please add the [ADD] to this Pull Request? So everyone know this is a new module in OCA.

Thanks

2017-06-23 12:56 UTC, darshan-serpent commented on sale_order_line_sequence/model/sale_order.py
> +                               store=True)
@aheficent It does in local, I guess that's because the runbot is red.

2017-06-23 12:59 UTC, darshan-serpent commented on sale_order_line_sequence/__openerp__.py
> +        "stock_picking_line_sequence",
The code to propagate the sequence to invoice and the stock are done in account_invoice_line_sequence and stock_picking_line_sequence respectively.

2017-06-23 13:21 UTC, aheficent commented on sale_order_line_sequence/__openerp__.py
> +        "stock_picking_line_sequence",
Can you show me?  I just checked and I did not see anything similar. The sequence in those modules does not come from the sales order.

2017-06-23 13:37 UTC, darshan-serpent commented on sale_order_line_sequence/__openerp__.py
> +        "stock_picking_line_sequence",
The sequence to invoice is passed from the base [sale module iteself](https://github.com/odoo/odoo/blob/9.0/addons/sale/sale.py#L723)

And for [stock move here](https://github.com/odoo/odoo/blob/9.0/addons/sale_stock/sale_stock.py#L271).

2017-06-23 13:42 UTC, aheficent commented on sale_order_line_sequence/__openerp__.py
> +        "stock_picking_line_sequence",
So the dependencies to `account_invoice_line_sequence` and `stock_picking_line_sequence` are not needed, right?

2017-12-20 09:40 UTC, AaronHForgeFlow approved these changes
:+1: It works fine now. Please squash two last commits

2017-12-20 11:28 UTC, darshan-serpent commented
@aheficent I have squashed the commits!

2017-12-20 13:33 UTC, LoisRForgeFlow approved these changes
Tested on runbot + code review :+1:

2018-06-28 14:26 UTC, MiquelRForgeFlow approved these changes

2018-06-28 14:28 UTC, merged