[9.0][sale_product_set] Fix incompatibility with sale_margin
OCA/sale-workflow pull request #513
Opened 2017-07-25 16:43 UTC by jbeficent

When module `sale_product_set` is installed together with `sale_margin` the following error occurs when you try to add a set to a sales order.

  File "/opt/ao-odoo-buildout/parts/sale-workflow9/sale_product_set/wizard/product_set_add.py", line 34, in add_set
    max_sequence=max_sequence))
  File "/opt/ao-odoo-buildout/parts/odoo9/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/ao-odoo-buildout/parts/odoo9/addons/sale_margin/sale_margin.py", line 47, in create
    product_uom_id = self.env['product.uom'].browse(vals['product_uom'])
KeyError: 'product_uom'

2017-07-25 16:44 UTC, jbeficent commented
cc @lreficent @mreficent

2017-07-25 16:56 UTC, LoisRForgeFlow approved these changes
LGTM

2017-07-25 17:09 UTC, pedrobaeza commented
Maybe this is going to be more compatible if you call the product_id field onchange and get back the values. You can see an example for account.invoice.line in https://github.com/OCA/commission/blob/24dc77f966c25e9e59c996b1e1a807f5cad52eb2/sale_commission/models/settlement.py#L92

2017-08-18 15:16 UTC, mreficent commented
@pedrobaeza, and where that `_onchange_product_id` should be called in this PR? 🙃

2017-08-18 15:25 UTC, pedrobaeza commented
On `prepare_sale_order_line_data`. You set the product_id with `new`, call onchange, and get back the dict values.

2017-08-18 17:32 UTC, pedrobaeza requested changes
Change module version

2017-08-21 08:11 UTC, pedrobaeza approved these changes

2017-08-28 09:04 UTC, MiquelRForgeFlow approved these changes

2017-08-28 09:08 UTC, merged