[10.0] [ADD] sale_procurement_group_by_requested_date
OCA/sale-workflow pull request #541
Opened 2017-10-06 11:07 UTC by nikul-serpentcs

Sale Procurement Group by Requested date
========================================

This module creates different procurements groups for different requested dates in a sale order line when the sale order is confirmed. It depends on sale_sourced_by_line so this module will group procurements 
also by the warehouse in the sale order line.

2017-10-06 11:08 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-10-10 10:12 UTC, AaronHForgeFlow requested changes

2017-10-10 10:12 UTC, aheficent commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +                vals['name'] = '/'.join([vals['name'], line.warehouse_id.name,
Failing when no warehouse assigned to the line.

2017-10-11 05:10 UTC, nikul-serpentcs commented
@aheficent I did improve code, Could you please review.

2017-10-11 08:10 UTC, aheficent commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +                vals['name'] = '/'.join([vals['name'], line.warehouse_id.name,
I'd also put the following:
```
           elif line.requested_date and not line.warehouse_id:
                vals['name'] = '/'.join([vals['name'], req_date])
```

2017-10-11 08:12 UTC, aheficent commented on sale_procurement_group_by_requested_date/models/sale_order.py
> +                                         req_date])
I'd also put the following:
```
           elif line.requested_date and not line.warehouse_id:
                vals['name'] = '/'.join([vals['name'], req_date])
```

2017-10-11 14:48 UTC, AaronHForgeFlow requested changes
Not working. Created one sale order with two line with different requested date. Only one delivery created.

2017-10-26 10:28 UTC, AaronHForgeFlow reviewed
If sale_sourced_by_line may be discontinued https://github.com/OCA/sale-workflow/issues/529 then this module should not depend on that. Don't you agree @jbeficent ?

2017-10-27 09:04 UTC, nikul-serpentcs commented
@aheficent I did improve code, Could you please review.

2017-10-27 13:56 UTC, AaronHForgeFlow approved these changes
:+1: It works now :tada:

2018-03-19 10:10 UTC, aheficent commented
Travis was failing because of other module. That was fixed so rebasing this PR should be enough to greenify it @nikul-serpentcs

2018-04-05 11:12 UTC, aheficent commented
Hi @nikul-serpentcs  can you rebase this PR? I am getting conflicts when merging this branch

2018-04-05 11:21 UTC, nikul-serpentcs commented
> Hi @nikul-serpentcs can you rebase this PR? I am getting conflicts when merging this branch

Hi, @aheficent I did rebase PR, could you please take a look?

2018-04-05 12:20 UTC, AaronHForgeFlow commented
thanks @nikul-serpentcs

2018-04-13 11:00 UTC, aheficent commented
IMHO this should not depend on `sale_sourced_by_line` What if I just one to split procurement groups by requested date but not to select warehouses on sale_order_lines? I think it is just fine to remove the dependency, because the group key works independently.

2018-07-09 11:19 UTC, aheficent commented
Hi @nikul-serpentcs I'll attend this PR here: https://github.com/OCA/sale-workflow/pull/668/ Can you close this one? Thanks

2018-07-10 13:58 UTC, closed without merging