[10.0] [ADD] product_customer_code_sale
OCA/sale-workflow pull request #542
Opened 2017-10-09 12:15 UTC by nikul-serpentcs

Product Customer Code For sale
==============================
Based on product_supplierinfo_for_customer, this module loads in every sale order the
customer code defined in the product.

2017-10-09 12:19 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-10-11 08:18 UTC, AaronHForgeFlow reviewed
Please add the product-attribute repo in the oca_dependencies.txt file.

I'd also change the title of this PR, this is a migration not adding a new module.

2017-10-11 08:46 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-10-11 09:31 UTC, AaronHForgeFlow reviewed
Tested on local and works properly.

2017-10-11 09:31 UTC, aheficent commented on product_customer_code_sale/models/sale.py
> +        for line in self:
You can improve performance by filtering here:

`for line in self.filtered(lambda sol: sol.product_id.supplier_ids):`

2017-10-11 09:39 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-10-11 09:39 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-10-11 10:46 UTC, aheficent commented on product_customer_code_sale/models/sale.py
> +            if product.supplier_ids:
I think this check is not needed as you're filtering the lines

2017-10-11 11:32 UTC, AaronHForgeFlow reviewed
I tested on local and it looks good. Just come minor comment.

2017-10-11 11:32 UTC, aheficent commented on product_customer_code_sale/README.rst
> +
I think the Usage section with the "Try me on runbot" button is a must:
https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2017-10-13 09:27 UTC, AaronHForgeFlow approved these changes
:+1: It works. LGTM now

2017-10-16 08:27 UTC, LoisRForgeFlow approved these changes
Code LGTM. Could you please squash the commits of the migration into one before merge?

2017-11-21 16:39 UTC, AaronHForgeFlow requested changes

2017-11-21 16:39 UTC, aheficent commented on product_customer_code_sale/models/sale.py
> +            code_id = product_supplierinfo_obj.search([
This search is bad. The customer and supplierinfo of type 'customer' should be included as criteria.

2017-11-23 09:53 UTC, nikul-serpentcs commented
@aheficent Improved search method, Could you please review.

2017-11-23 10:01 UTC, aheficent commented on product_customer_code_sale/models/sale.py
> +                ('type', '=', 'customer'),
This is good. However I miss also the filter for the customer. `('name', '=', line.order_id.partner_id),` would do the thing I think

2017-11-23 10:13 UTC, nikul-serpentcs commented
@aheficent Added filter for a customer, Could you please review.

2017-11-23 11:22 UTC, AaronHForgeFlow approved these changes
:+1: Now it works as expected. Thanks

2018-04-04 15:01 UTC, closed without merging

2018-04-13 22:36 UTC, rafaelbn commented
Why this PR has been closed and not merged?

2018-04-16 07:34 UTC, aheficent commented
@rafaelbn because the module had to be renamed (product customer code is deprecated in favor of product_supplierinfo_for_customer) and the author of this PR will not continue with this.

2018-04-26 23:28 UTC, rafaelbn commented
OK thanks @aheficent !