[11.0][ADD] sales_disable_inventory_check
OCA/sale-workflow pull request #580
Opened 2017-12-11 08:20 UTC by phucngta

This module disables show warning "Not enough inventory" when there isn't enough product in stock

2017-12-12 08:05 UTC, gdgellatly reviewed
Hi,

1 minor typo, 2 opinions, but LGTM.

Also, complete the summary field in __manifest__.py and substitute {project_repo} in the README and delete the Usage block

2017-12-12 08:05 UTC, gdgellatly commented on sales_disable_inventory_check/models/sale_order_line.py
> +        res = super(SaleOrderLine,
shame we have to call super, that is an expensive function call just to discard the result.

2017-12-12 08:05 UTC, gdgellatly commented on sales_disable_inventory_check/tests/test_disable_inventory_check.py
> +                         "There's should not be a warning!!!")
spelling. There should not be a warning.  

The tests are probably OK as is, however, as we are testing an onchange new is probably better than create.

2018-03-27 01:49 UTC, jcdrubay requested changes
After taking into account last tiny changes you should request maintainers to take a look ;)

"@OCA/core-maintainers : could you please help to review?"

2018-03-27 01:49 UTC, jcdrubay commented on sales_disable_inventory_check/README.rst
> +The development of this module has been financially supported by:
We  should remove Komit from this

2018-03-27 01:49 UTC, jcdrubay commented on sales_disable_inventory_check/__manifest__.py
> +    "author": "Phuc.nt, "
For author, can you put your name and company on the same line "Nguyen Tan Phuc (komit-consulting.com)"

2018-03-27 10:59 UTC, jcdrubay approved these changes

2018-03-27 11:00 UTC, jcdrubay commented
Dear @OCA/core-maintainers : could you please help to review? Thanks

2018-03-27 11:02 UTC, pedrobaeza requested changes
Module name should be singular.

2018-03-28 01:53 UTC, phucngta commented
@pedrobaeza i have changed module name to singular.

2018-04-02 10:04 UTC, StefanRijnhart commented
I think this module could be a lot more useful if you could make this a company dependent property setting, so that you can disable the warning either globally or per product and/or per company.

2018-06-22 04:05 UTC, jcdrubay commented
@StefanRijnhart How about we make it company dependent on the product category with a default value, then overidable on the product template.

Something very similar to what is done for "Income Account": 
`'income': self.property_account_income_id or self.categ_id.property_account_income_categ_id,`

We would need:

 - A new property field "property_is_check_stock" on Product Template and on Product Category
 - A default property like the property with xml record `property_account_income_categ_id`

2019-03-04 22:02 UTC, GSLabIt commented
Any eta for this?

2019-03-04 22:44 UTC, StefanRijnhart commented
Well, looks like this has stalled completely and hopefully not because I never confirmed @jcdrubay's suggestion because that's pretty much the idea.

2019-03-04 22:45 UTC, jcdrubay commented
We will finalize with latest suggestion from my comment: on Jun 22, 2018

2019-03-04 23:57 UTC, NL66278 commented
I miss any explanation why somebody would want this, and in what circumstances. Checking for availability of a product when you try to sell it seems like a good idea, not?

2019-03-05 00:23 UTC, jcdrubay commented
A car dealer would rarely sell cars that are in stock because there are so many models and variants ... they know they don't have the stock because they have only few cars in stock: the 6 cars in display.

In this kind of situation, and other less extreme, the warning message is annoying and useless.

2019-03-05 05:21 UTC, jbeficent commented
Cc @hveficent

2019-03-05 08:34 UTC, NL66278 commented
@jcdrubay would the solution than not be to not define the car as a stockable product?

2019-03-05 08:36 UTC, pedrobaeza commented
@NL66278 In B2B businesses that works with delayed deliveries, it's also very annoying to have each time the out of stock warning, but you need them to be stockable, not consumable, so +1 for this module.

2019-03-05 09:05 UTC, NL66278 approved these changes
LGTM

2019-03-05 09:06 UTC, NL66278 commented
@pedrobaeza Thanks for the explanation.

2019-03-05 10:21 UTC, HviorForgeFlow approved these changes
Also this warning doesn't show quantities correctly in specific locations. Great feature. :+1:

2019-03-07 10:24 UTC, LoisRForgeFlow approved these changes
LGTM

2019-03-07 10:24 UTC, lreficent commented
@pedrobaeza Can you update your review?

2019-03-07 10:34 UTC, pedrobaeza approved these changes

2019-03-07 10:34 UTC, merged

2019-03-07 11:02 UTC, StefanRijnhart commented
Did you guys miss that this would be refactored into making this a property on products and categories?

2019-03-07 11:38 UTC, pedrobaeza commented
Well, it's a good to have, but on our cases it's not needed. We can at least add it to the roadmap, or if you want to directly make the PR adding the feature, it's welcome.

2019-03-07 11:47 UTC, StefanRijnhart commented
OK!

2019-03-07 12:02 UTC, AaronHForgeFlow reviewed
:tada:

2019-03-07 13:22 UTC, jcdrubay commented
Thanks for the merge :) the improved version is on the way !

2019-03-08 03:32 UTC, hieulucky111 commented
New Implement was done in PR https://github.com/OCA/sale-workflow/pull/805