[10.0][MIG] sale_fixed_discount
OCA/sale-workflow pull request #589
Opened 2018-01-12 09:57 UTC by lreficent

Migration based on https://github.com/OCA/sale-workflow/pull/522.

* [ ] : Depends on https://github.com/OCA/account-invoicing/pull/353

Sale Fixed Discount
===================

This module extends the functionality of Sales to allow you to apply fixed
amount discount at sales order line level.

The module also extends the sales order report to show fixed discount.

Configuration
=============

To configure this module, you need to:

#. Go to *Sale > Configuration >Settings*.
#. In the *Discount* option select *Allow discounts on sales order lines*.

Usage
=====

To use this module, you need to:

#. Go to *Sales*.
#. Create a Sales Order and specify the type of discount and fixed/percent
   discount in a line.

2018-06-13 08:06 UTC, MiquelRForgeFlow approved these changes
LGTM

2018-06-13 08:06 UTC, mreficent commented on sale_fixed_discount/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
png

2018-06-13 08:06 UTC, mreficent commented on sale_fixed_discount/README.rst
> +* Odoo Community Association: `Icon <https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg>`_.
Icon https://odoo-community.org/logo.png`_.

2018-06-13 08:45 UTC, lreficent commented on sale_fixed_discount/README.rst
> +* Odoo Community Association: `Icon <https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg>`_.
done

2018-10-01 14:54 UTC, JayVora-SerpentCS requested changes

2018-10-01 14:54 UTC, JayVora-SerpentCS commented on sale_fixed_discount/__manifest__.py
> +    "website": "https://odoo-community.org/",
https://github.com/OCA/sale-workflow

2018-10-02 09:13 UTC, lreficent commented on sale_fixed_discount/__manifest__.py
> +    "website": "https://odoo-community.org/",
done.

2018-10-02 09:13 UTC, lreficent commented
@JayVora-SerpentCS Could you please update your review?

2018-10-02 09:23 UTC, JayVora-SerpentCS approved these changes

2018-10-02 15:31 UTC, lreficent commented
Ready to merge I think.

2018-10-08 08:26 UTC, merged