11.0 imp sale product set variant
OCA/sale-workflow pull request #611
Opened 2018-02-20 13:42 UTC by mpanarin

Made prodcut_variants use many2many_tags widget in product set variant as it is more usable than tree view.
If there is only one variant for the product, it will be auto-filled in wizard

2018-02-20 14:15 UTC, guewen requested changes

2018-02-20 14:15 UTC, guewen commented on sale_product_set_variant/wizard/product_set_add.py
> +                          "for product {}".format(
The translations `_()` should close right after the closing `"`, here you are translating the text *after* the interpolation.

2018-02-22 14:35 UTC, yvaucher approved these changes

2018-03-02 09:40 UTC, guewen approved these changes

2018-03-02 09:40 UTC, merged