11.0 mig sale_triple_discount
OCA/sale-workflow pull request #627
Opened 2018-04-05 07:58 UTC by xavierjimenez

Migration of sale_triple_discount module to version 11.0

2018-04-05 08:03 UTC, pedrobaeza commented
You have added a .DS_store file

2018-04-06 19:24 UTC, misern2 requested changes
You should update the security groups on the account_invoice views for the new fields.

Check core code for the discount field: 

https://github.com/odoo/odoo/blob/00ef138ce038d4f8e5a9b7ad2f23ab483e282ebb/addons/sale/views/sale_views.xml#L718-L738

2018-04-13 22:21 UTC, rafaelbn commented
Thanks @xavierjimenez ! Please rebase as https://github.com/OCA/account-invoicing/pull/370 has been merge and then we could test this one! :smile:

2018-04-13 22:24 UTC, pedrobaeza commented
No need to rebase, as it's in another repository. Just to restart CIs.

2018-04-18 13:35 UTC, xavierjimenez commented
I'm not sure how to do that, do I have to open a new PR?

2018-04-18 15:52 UTC, pedrobaeza commented
I have restarted both.

2018-04-26 22:53 UTC, rafaelbn commented
There are missing dependencies

```
2018-04-18 16:06:05,315 5431 WARNING openerp_test odoo.modules.loading: Transient module states were reset
2018-04-18 16:06:05,315 5431 ERROR openerp_test odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
File "/home/travis/OCB-11.0/odoo/modules/registry.py", line 85, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/travis/OCB-11.0/odoo/modules/loading.py", line 308, in load_modules
modules.button_install()
File "<decorator-gen-39>", line 2, in button_install
File "/home/travis/OCB-11.0/odoo/addons/base/module/module.py", line 71, in check_and_log
return method(self, *args, **kwargs)
File "/home/travis/OCB-11.0/odoo/addons/base/module/module.py", line 397, in button_install
modules._state_update('to install', ['uninstalled'])
File "/home/travis/OCB-11.0/odoo/addons/base/module/module.py", line 362, in _state_update
raise UserError(_("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
odoo.exceptions.UserError: ("You try to install module 'sale_triple_discount' that depends on module 'account_invoice_triple_discount'.\nBut the latter module is not available in your system.", '')
2018-04-18 16:06:05,316 5431 CRITICAL openerp_test odoo.service.server: Failed to initialize database `openerp_test`.
Traceback (most recent call last):
File "/home/travis/OCB-11.0/odoo/service/server.py", line 925, in preload_registries
registry = Registry.new(dbname, update_module=update_module)
File "/home/travis/OCB-11.0/odoo/modules/registry.py", line 85, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/travis/OCB-11.0/odoo/modules/loading.py", line 308, in load_modules
modules.button_install()
File "<decorator-gen-39>", line 2, in button_install
File "/home/travis/OCB-11.0/odoo/addons/base/module/module.py", line 71, in check_and_log
return method(self, *args, **kwargs)
File "/home/travis/OCB-11.0/odoo/addons/base/module/module.py", line 397, in button_install
modules._state_update('to install', ['uninstalled'])
File "/home/travis/OCB-11.0/odoo/addons/base/module/module.py", line 362, in _state_update
raise UserError(_("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
odoo.exceptions.UserError: ("You try to install module 'sale_triple_discount' that depends on module 'account_invoice_triple_discount'.\nBut the latter module is not available in your system.", '')
```

2018-07-06 11:14 UTC, murtuzasaleh commented
@xavierjimenez  I am starting working on it.
cc @pedrobaeza

2018-07-06 13:51 UTC, xavierjimenez commented
@murtuzasaleh I think the module is working fine, there's a dependency issue with another module (account_invoice_triple_discount) but that module is already merged so I'm not sure how I can solve that.

2018-07-06 13:52 UTC, pedrobaeza commented
Is the repository put in oca_dependencies.txt in root folder?

2018-07-06 14:47 UTC, pedrobaeza commented
@xavierjimenez can you check what I have said?

2018-07-06 14:53 UTC, xavierjimenez commented
I just checked it out and it's not, can I add it?

2018-07-06 14:55 UTC, pedrobaeza commented
Yes, of course. That's the idea when you add a new module (migrated or totally new) that depends on modules on other repositories. Doing so, you will get the module available and Travis/runbot will be OK.

2018-07-06 15:33 UTC, pedrobaeza commented
All green! @murtuzasaleh  @JayVora-SerpentCS can you please review this one now that the problem has gone?

2018-07-07 09:09 UTC, JayVora-SerpentCS requested changes

2018-07-07 09:09 UTC, JayVora-SerpentCS commented on sale_triple_discount/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/167/10.0
11.0 plz

2018-07-07 09:09 UTC, JayVora-SerpentCS commented on sale_triple_discount/__manifest__.py
> +              'Odoo Community Association (OCA)',
Authorname should be added when you added a feature my friend. If not, add your name to contributors in readme.

2018-07-07 09:09 UTC, JayVora-SerpentCS commented on sale_triple_discount/__manifest__.py
> +    'website': 'https://odoo-community.org',
website  -> https://github.com/OCA/sale-workflow

2018-07-09 05:29 UTC, murtuzasaleh commented on sale_triple_discount/__manifest__.py
> +        'sale',
Add dependency sale_management instead of a sale module.

2018-07-09 06:45 UTC, xavierjimenez commented
Changes done! I'll make the squash with the previous commits when it's ready to merge.

2018-08-01 18:39 UTC, rafaelbn commented
Hi @murtuzasaleh @JayVora-SerpentCS @misern2 this PR is all green and attended comment.

@xavierjimenez just take a look in:

- [FIX] https://github.com/OCA/sale-workflow/pull/544 (this could happens also in v11)
- [IMP] https://github.com/OCA/sale-workflow/pull/671

Thanks a lot for your :green_apple: work! :+1: 

cc @chienandalu

2018-08-01 18:57 UTC, rafaelbn commented
Hi @xavierjimenez I've tested it and my doubt is about report. Does it have any sense for you?

Take a look:

![ex1](https://user-images.githubusercontent.com/8736623/43542501-79fe5a3a-95cd-11e8-859c-5add7ec0a3e8.png)

---

![ex2](https://user-images.githubusercontent.com/8736623/43542511-7f05df58-95cd-11e8-89a4-a4b798b38b10.png)

2018-08-01 19:25 UTC, rafaelbn reviewed
I'm not blocking but IMHO report (PDF of SO) must be improved

2018-08-02 07:52 UTC, xavierjimenez commented
Hi @rafaelbn, thanks for the review!

I agree, the report needs a change so I'll try to add the others discounts on the report if they are set.

2018-08-03 07:16 UTC, pedrobaeza commented
@xavierjimenez I have just discovered the field `price_reduce`: https://github.com/odoo/odoo/blob/11.0/addons/sale/models/sale.py#L783, that contains the price with the discount. I'm not sure if this field is used everywhere, but maybe changing the computing of it can be enough.

Can you please try?

2019-03-14 04:43 UTC, rafaelbn commented
Hello @xavierjimenez @misern2 !

Are you using this module in production enviroment?

Take care for fixes in v10 that apply in this PR

- FIX https://github.com/OCA/sale-workflow/pull/544
- Rework https://github.com/OCA/sale-workflow/pull/671
- FIX https://github.com/OCA/sale-workflow/pull/740

We could try to push this PR reviewing fixes of v10, rebasing this PR and checking again.

Thanks

2021-12-23 16:16 UTC, rousseldenis commented
Closing this as very old and no answer from author. Please feel free to reopen it if needed.

2021-12-23 16:16 UTC, closed without merging