11.0 mig sale order lot selection
OCA/sale-workflow pull request #628
Opened 2018-04-06 10:24 UTC by OpenCode

2018-07-27 08:06 UTC, ilmir-k approved these changes
:+1:

2018-07-29 08:23 UTC, MeetKD requested changes

2018-07-29 08:23 UTC, MeetKD commented on sale_order_lot_selection/__manifest__.py
> +    'website': 'http://www.agilebg.com',
website should be https://github.com/OCA/sale-workflow

2018-07-29 08:23 UTC, MeetKD commented on sale_order_lot_selection/__manifest__.py
> +    'author': "Odoo Community Association (OCA), Agile Business Group",
Mention agile before OCA.

2018-07-29 08:23 UTC, MeetKD commented on sale_order_lot_selection/tests/test_sale_order_lot_selection.py
> +        with self.assertRaises(Warning):
You can remove the print stats and commented code if its not usable.

2018-07-29 08:23 UTC, MeetKD commented on sale_order_lot_selection/model/__init__.py
> +
I guess encoding part is not needed anymore and you can add separate license file and remove it from all py files.

2018-08-15 13:38 UTC, max3903 commented
@OpenCode Please review and merge https://github.com/OpenCode/sale-workflow/pull/2 from @mgosai

2018-10-10 11:36 UTC, yelizariev commented
@mgosai you may need to create new PR to OCA as there is no response from @OpenCode

2018-10-10 14:24 UTC, mgosai commented
Super seeded by #714

2018-10-10 14:53 UTC, tafaRU commented
I close this then. Thank you!

2018-10-10 14:53 UTC, closed without merging