[10.0][sale_cancel_reason]Added description field
OCA/sale-workflow pull request #645
Opened 2018-05-10 14:52 UTC by paolomonniLP

Added a text field for the description of the cancellation of the order.

2018-05-10 15:05 UTC, pedrobaeza requested changes
What is the use case for 2 strings for the reason?

2018-05-10 15:05 UTC, pedrobaeza commented on sale_cancel_reason/wizard/cancel_reason.py
> +    description = fields.Text(string='Description', size=12)
You put a text field but then limited to 12 characters. Isn't this a nonsense?

2018-05-10 15:23 UTC, paolomonniLP commented
This field is used to describe in detail the reason for canceling the order.

2018-05-10 15:25 UTC, pedrobaeza commented
Uhm, I think you don't need too much explanations about cancel reasons (they are internal), but I let other reviewers to decide.

2018-05-23 14:51 UTC, JayVora-SerpentCS commented
Agree with @pedrobaeza .Simple M2O is enough. Always minimise fields. If the reason is different, it should be mentioned in a comment may be. Or choose OTHER as a reason on sale.order.cancel.reason

2018-05-23 14:53 UTC, JayVora-SerpentCS commented on sale_cancel_reason/model/sale.py
> +    cancel_reason_id = fields.Many2one('sale.order.cancel.reason', string="Reason for cancellation", readonly=True,
You made travis go red forcefully:) Was right earlier.

2018-10-01 14:39 UTC, JayVora-SerpentCS commented
ping @paolomonniLP

2021-12-15 07:59 UTC, rousseldenis commented
Closing this as very old and comments not attended. Please feel free to reopen if needed.

2021-12-15 07:59 UTC, closed without merging