[11.0] [MIG] sale_validity
OCA/sale-workflow pull request #666
Opened 2018-07-06 10:32 UTC by murtuzasaleh

Default Quotation Validity
==========================

* With this module, you will be able to configure a default validity delay on quotations.

Migration of module Default Quotation Validity v10 to v11.

2018-09-05 06:09 UTC, nikul-serpentcs commented on sale_validity/__manifest__.py
> +    'website': 'http://www.camptocamp.com',
@murtuzasaleh Change URL as per https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L10

2018-10-01 07:23 UTC, nikul-serpentcs approved these changes
Code Review LGTM

2018-10-01 08:31 UTC, pedrobaeza commented
Can you squash a bit commit history avoiding that merge commits?

2018-10-01 10:23 UTC, murtuzasaleh commented
> Can you squash a bit commit history avoiding that merge commits?

@pedrobaeza  squashed

2018-10-01 14:38 UTC, JayVora-SerpentCS approved these changes
LGTM

2018-10-02 09:40 UTC, pedrobaeza commented
Can you please check conflicts? Why are you modifying that file?

2018-10-03 06:18 UTC, murtuzasaleh commented
> Can you please check conflicts? Why are you modifying that file?

@pedrobaeza Done, Here I rebase PR then conflicts error occurs,  so I solved it.

2018-10-04 10:04 UTC, nikul-serpentcs commented
@pedrobaeza @JayVora-SerpentCS Could you please review it and move Forward.

2018-10-08 08:07 UTC, lreficent commented
@murtuzasaleh could you please fix conflicts?

2018-10-08 08:52 UTC, nikul-serpentcs commented
@lreficent could you please review it?

2018-10-09 09:48 UTC, lreficent commented
@murtuzasaleh that's not the way to solve the conflict (all those "Merge..." commits) you should do a rebase on top of OCA's 11.0 branch.

2018-10-15 08:01 UTC, murtuzasaleh commented
@lreficent Conflicts solved! Could you please review it?

2018-11-08 15:03 UTC, HviorForgeFlow requested changes
Would be nice to use new [readme format](https://github.com/OCA/maintainer-tools/tree/master/template/module/readme)

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/__init__.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/__manifest__.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/models/__init__.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/models/company.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/models/res_config_settings.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/models/sale_config_settings.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/models/sale_order.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/tests/__init__.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, HviorForgeFlow commented on sale_validity/tests/test_sale_validity.py
> +# -*- coding: utf-8 -*-
Remove encode

2018-11-08 15:03 UTC, hveficent commented on sale_validity/views/sale_config_settings.xml
> +<?xml version="1.0"?>
That view can be removed.

2018-11-13 14:49 UTC, JayVora-SerpentCS commented
@murtuzasaleh ping

2018-11-16 08:50 UTC, LoisRForgeFlow approved these changes
Functional review ok :+1:

2018-11-16 08:51 UTC, lreficent commented
@hveficent could you update your review?

2018-11-16 08:52 UTC, HviorForgeFlow approved these changes
:+1:

2018-11-16 09:05 UTC, pedrobaeza requested changes
Odoo core already contains an expiration date:

![seleccion_012](https://user-images.githubusercontent.com/7165771/48611603-ed3eb780-e986-11e8-8f67-aeef84314477.png)

so you should reuse that field instead of creating a new one. And thus the module should be renamed to other thing like `sale_order_default_expiration`

2019-01-07 08:27 UTC, pedrobaeza approved these changes
I looked incorrectly to this and it's not creating a new field. I merge.

2019-01-07 08:49 UTC, merged