[11.0] [MIG] sale_start_end_dates
OCA/sale-workflow pull request #669
Opened 2018-07-10 13:24 UTC by murtuzasaleh

Sale Start End Dates
====================

- This module adds the fields *start date* and *end date* on sale order
lines. Upon invoice creation, the value of the start/end dates of the
sale order line is copied to the start/end dates of invoice lines. This
module is a technical module: it is designed to be used with other
modules such as the *sale_rental* module.

Migration of module Sale Start End Dates v10 to v11.

2018-07-10 13:45 UTC, JayVora-SerpentCS requested changes

2018-07-10 13:45 UTC, JayVora-SerpentCS commented on sale_start_end_dates/__manifest__.py
> +    'website': 'http://www.akretion.com',
https://github.com/OCA/sale-workflow

2018-07-10 13:45 UTC, JayVora-SerpentCS commented on sale_start_end_dates/models/sale.py
> +    @api.one
api.multi

2018-07-10 13:45 UTC, JayVora-SerpentCS commented on sale_start_end_dates/models/sale.py
> +    @api.constrains('start_date', 'end_date', 'number_of_days')
use multi

2018-07-24 06:27 UTC, JayVora-SerpentCS approved these changes

2018-09-05 06:16 UTC, nikul-serpentcs commented on sale_start_end_dates/models/sale.py
> +from odoo import models, fields, api, _
@murtuzasaleh Use alphabetic naming convention.

2018-10-01 07:12 UTC, nikul-serpentcs approved these changes
LGTM

2018-10-01 07:12 UTC, nikul-serpentcs commented on sale_start_end_dates/models/sale.py
> +        if self.must_have_dates:
@murtuzasaleh here check `if self.must_have_dates and self.start_date and self.end_date`

2018-10-01 09:07 UTC, YogeshMahera-SerpentCS approved these changes
LGTM

2018-10-01 09:47 UTC, merged