[10.0][ADD] New module: sale_product_country_filter
OCA/sale-workflow pull request #672
Opened 2018-07-16 08:28 UTC by andreparames

This is a new proposed module which restricts the sale of certain products to chosen countries, to comply with legal restrictions and such.

2018-07-16 09:48 UTC, pedrobaeza requested changes
Isn't better to add a domain over product many2one for preventing the forbidden products to be listed?

2018-07-16 09:48 UTC, pedrobaeza commented on sale_product_country_filter/readme/HISTORY.rst
> +10.0.0.0.1 (2018-07-16)
10.0.0.0

2018-07-16 11:01 UTC, andreparames commented
A domain might be a good addition, but my fear is that it might compromise the performance, since it involves a rather complex query with a lot of data to scan (since it filters no just on `product_product` and `product_template`, but also on the full hierarchy of categories, since any can block the sale), which will re-run on every key press when searching for the product.

2018-07-16 11:05 UTC, pedrobaeza commented
No, the domain is only evaluated once, not each time you type one letter on the many2one AFAIK. Any way, you can use as an alternative a static computed many2many for loading the allowed products, and then use that one as source of the domain, so the performance doesn't impact.

2018-07-16 14:07 UTC, Cedric-Pigeon commented
The problem with the domain on many2one is that in case of partner_id change, the check on products won't be triggered again

2018-07-16 14:10 UTC, Cedric-Pigeon requested changes

2018-07-16 14:10 UTC, Cedric-Pigeon commented on sale_product_country_filter/models/sale_order.py
> +        if (
The code could perhaps be added in a common method called by both onchange

2018-07-16 14:52 UTC, pedrobaeza commented
You can change the domain on the onchange, or make the compute dependent of that field.

2018-07-18 16:17 UTC, andreparames commented
> Any way, you can use as an alternative a static computed many2many for loading the allowed products, and then use that one as source of the domain, so the performance doesn't impact.

But wouldn't that require loading into that field every product ID except the ones which are embargoed to the specific country of the partner? That may be thousands, or more.

OTOH, I tried figuring out how to apply a domain on the field (without using a helper m2m), but I'm struggling to adapt the [categories query](https://github.com/OCA/sale-workflow/pull/672/files#diff-5d6d974f6bcc8ed2fa23dfbdd8b51b0eR102) into it, since the domain is a query for products.

2019-09-22 17:33 UTC, rafaelbn commented
Hi @Cedric-Pigeon @rousseldenis you pushed 2 commits to this PR, could please review? Thanks

2022-02-27 12:21 UTC, closed without merging