11.0 fix sale order product recommendation
OCA/sale-workflow pull request #698
Opened 2018-09-20 11:10 UTC by chienandalu

This PR includes two commits:

- A fix for the wizard that was failing to load lines from the recommendations that weren't loaded from the SO itself.
- An improvement to be able to use the wizard even if the SO is confirmed (the same restrictions that
exist editing the order manually apply)

cc @Tecnativa

2018-09-20 14:26 UTC, pedrobaeza requested changes
Add tests for the new flow

2018-09-20 19:45 UTC, pedrobaeza commented
Travis is failing

2018-09-20 19:45 UTC, pedrobaeza commented
```
sale_order_product_recommendation/tests/test_recommendation.py:116:13: E122 continuation line missing indentation or outdented
sale_order_product_recommendation/tests/test_recommendation.py:117:9: E122 continuation line missing indentation or outdented
sale_order_product_recommendation/tests/test_recommendation.py:131:13: E122 continuation line missing indentation or outdented
sale_order_product_recommendation/tests/test_recommendation.py:132:9: E122 continuation line missing indentation or outdented
```

2018-10-09 14:33 UTC, carlosdauden approved these changes

2018-10-09 15:21 UTC, rafaelbn approved these changes
Thanks!

2018-10-09 15:46 UTC, sergio-teruel approved these changes

2018-10-09 15:47 UTC, merged