12.0 mig sale order line input
OCA/sale-workflow pull request #706
Opened 2018-10-02 09:33 UTC by mpanarin

migration to v 12.0

2018-12-19 14:12 UTC, rven commented on sale_order_line_input/views/sale_order_line_view.xml
> +      <tree string="Sales Orders Lines"
Deprecated <tree> xml attribute "string" (xml-deprecated-tree-attribute)
```suggestion
      <tree
```

2018-12-19 14:12 UTC, rven commented on sale_order_line_input/readme/USAGE.rst
> +#. Create new line related with existant order
```suggestion
#. Create new line related with existing order
```

2018-12-19 14:28 UTC, rven requested changes

2018-12-19 14:28 UTC, rven commented on sale_order_line_input/views/sale_order_line_view.xml
> +    <field name="name">sale.order.line.input.tree.</field>
```suggestion
    <field name="name">sale.order.line.input.tree</field>
```

2018-12-19 14:28 UTC, rven commented on sale_order_line_input/views/sale_order_line_view.xml
> +        <button name="action_sale_order_form" type="object" icon="fa-external-link" class="oe_stat_button"/>
```suggestion
        <button name="action_sale_order_form" string="Open Sale Order" type="object" icon="fa-external-link" class="oe_stat_button"/>
```

2018-12-19 14:28 UTC, rven commented on sale_order_line_input/views/sale_order_line_view.xml
> +               groups="product.group_uom" options='{"no_open": True}'/>
```suggestion
               groups="uom.group_uom" options='{"no_open": True}'/>
```

2018-12-19 14:28 UTC, rven commented on sale_order_line_input/views/sale_order_line_view.xml
> +        <field name="product_uom" groups="product.group_uom"/>
```suggestion
        <field name="product_uom" groups="uom.group_uom"/>
```

2018-12-19 14:28 UTC, rven commented on sale_order_line_input/views/sale_order_line_view.xml
> +        <filter name="uom_filter" string="UoM" context="{'group_by': 'product_uom'}" groups="product.group_uom"/>
```suggestion
        <filter name="uom_filter" string="UoM" context="{'group_by': 'product_uom'}" groups="uom.group_uom"/>
```

2018-12-19 14:28 UTC, rven commented on sale_order_line_input/views/sale_order_line_view.xml
> +        <field name="price_subtotal" sum="Total" widget="monetary" groups="sale.group_show_price_subtotal"/>
```suggestion
        <field name="price_subtotal" sum="Total" widget="monetary" groups="account.group_show_line_subtotals_tax_excluded"/>
```

2018-12-19 14:28 UTC, rven commented on sale_order_line_input/views/sale_order_line_view.xml
> +        <field name="price_total" widget="monetary" groups="sale.group_show_price_total"/>
```suggestion
        <field name="price_total" widget="monetary" groups="account.group_show_line_subtotals_tax_included"/>
```

2018-12-19 14:40 UTC, rven commented
The changes to get it to work can be found here
https://github.com/mpanarin/sale-workflow/pull/1

2019-06-19 10:43 UTC, oihane approved these changes
LGTM :+1:

2019-06-19 10:47 UTC, anajuaristi commented
LGTM :+1:

2019-06-21 11:19 UTC, Tardo approved these changes
LGTM :+1: code review

2019-06-21 13:03 UTC, pedrobaeza commented
/ocabot merge

2019-06-21 13:41 UTC, closed without merging