[12.0][MIG] Migrated sale_stock_picking_note to v12
OCA/sale-workflow pull request #757
Opened 2018-12-04 13:10 UTC by sudhir-erpharbor

Please review and give feedback.

2018-12-04 16:00 UTC, chienandalu requested changes
Thanks! Tested ok in runbot. Some changes needed though:

2018-12-04 16:00 UTC, chienandalu commented on sale_stock_picking_note/README.rst
> -
You have to respect this blank line so the group is tabulated properly

2018-12-04 16:00 UTC, chienandalu commented on sale_stock_picking_note/README.rst
> +* Sudhir Arya <sudhir@erpharbor.com>
Add a blank line before this one so you aren't grouped in Tecnativa

2018-12-04 16:00 UTC, chienandalu commented on sale_stock_picking_note/views/stock_picking_view.xml
> +                <group string="Notes" name="notes">
Yo can get rid of this view since the field was recently added in a separate tab

![image](https://user-images.githubusercontent.com/5040182/49454617-cafdc400-f7e5-11e8-9fae-09710422fc5b.png)

2018-12-04 16:00 UTC, chienandalu commented on sale_stock_picking_note/README.rst
> +#. The note will be available under the *Additional Info* tab.
Change this instruction as it's in a tab given by the standard.

2018-12-06 12:21 UTC, sudhir-erpharbor commented on sale_stock_picking_note/README.rst
> -
Done.

2018-12-06 12:22 UTC, sudhir-erpharbor commented on sale_stock_picking_note/README.rst
> +* Sudhir Arya <sudhir@erpharbor.com>
Done.

2018-12-06 12:22 UTC, sudhir-erpharbor commented on sale_stock_picking_note/views/stock_picking_view.xml
> +                <group string="Notes" name="notes">
Done.

2018-12-06 12:22 UTC, sudhir-erpharbor commented on sale_stock_picking_note/README.rst
> +#. The note will be available under the *Additional Info* tab.
Done!! Any more improvements / suggestions?

2018-12-10 12:41 UTC, chienandalu requested changes

2018-12-10 12:41 UTC, chienandalu commented on sale_stock_picking_note/README.rst
> +#. The note will be available under the *Additional Info* tab.
It's still wrong. The note is available in the "Note" tab

2018-12-10 12:41 UTC, chienandalu commented on sale_stock_picking_note/README.rst
> +* Sudhir Arya <sudhir@erpharbor.com>
Still wrong. It should be:

```
* Tecnativa <https://www.tecnativa.com>
  * Carlos Dauden
  * David Vidal

* Sudhir Arya <sudhir@erpharbor.com>
```

2018-12-10 17:17 UTC, angelmoya commented
Hi @sudhir-erpharbor , all comments done by @chienandalu must be done on separate files (authors.rst, usage.rst....) and I think that info in readme.rst could be delete because it will be generated

2018-12-11 09:10 UTC, rousseldenis commented
> Hi @sudhir-erpharbor , all comments done by @chienandalu must be done on separate files (authors.rst, usage.rst....) and I think that info in readme.rst could be delete because it will be generated

https://github.com/OCA/maintainer-tools#readme-generator

2018-12-12 11:25 UTC, sudhir-erpharbor commented on sale_stock_picking_note/README.rst
> +#. The note will be available under the *Additional Info* tab.
Done.

2019-08-30 06:22 UTC, rafaelbn commented
Please @sudhir-erpharbor , please @chienandalu read my review here:

https://github.com/OCA/sale-workflow/pull/843#pullrequestreview-281844334

Thanks
Regards

2019-09-30 12:05 UTC, acsonefho approved these changes
LGTM (Code only)

2019-10-07 09:06 UTC, lmignon approved these changes
LGTM (Code review + Functional tests)

2019-11-04 17:40 UTC, chienandalu approved these changes

2019-11-04 18:01 UTC, pedrobaeza commented
/ocabot merge

2019-11-04 18:24 UTC, merged