[10][IMP] sale_exception add field
OCA/sale-workflow pull request #780
Opened 2019-01-08 14:38 UTC by hparfr

Add a reverse field to leverage optimizations of base_exception.

Since base_exception@10.0.2.0.0, if there is a relation from exception.rule to a model, it will be used to write results once per rule instead of iterate through all the sale order records.

2019-01-08 16:07 UTC, PierrickBrun approved these changes

2019-01-08 16:36 UTC, chafique-delli approved these changes
Thank you @hparfr  for this improvement

2019-01-08 19:55 UTC, pedrobaeza commented
I think this is not going to be very useful when a bit of time has passed and you have tons of past orders in exception.

2019-01-08 19:56 UTC, pedrobaeza commented
And this will also slow down a lot the load of the exception form. This should go as an smart-button that navigates to list.

2019-01-09 09:38 UTC, hparfr commented
>I think this is not going to be very useful when a bit of time has passed and you have tons of past orders in exception.

The bigger len(sale.order)  / len(exception.rule) is, the bigger this commit will improve perfs.

>And this will also slow down a lot the load of the exception form. This should go as an smart-button that navigates to list.

I don't get it. Which form ? This one  https://github.com/OCA/server-tools/blob/10.0/base_exception/views/base_exception_view.xml#L18 ?

2019-01-13 15:56 UTC, pedrobaeza requested changes
See me previous comment.

2019-01-15 16:31 UTC, hparfr commented
Added test that can pass only after the following PR is merged in server-tools https://github.com/OCA/server-tools/pull/1480

It's not necessary anymore to scan all the sales to get accurate results.
It's useful when lot of sales can't be excluded by domain (like state=draft).

2019-01-16 04:53 UTC, nikul-serpentcs commented on sale_exception/__manifest__.py
>   'website': 'http://www.akretion.com',
URL Should be `https://github.com/OCA/sale-workflow`

2019-01-16 04:54 UTC, nikul-serpentcs commented on sale_exception/tests/__init__.py
> +from . import test_multi_records
@hparfr add a new blank line

2019-06-12 14:52 UTC, florian-dacosta commented
This PR depends on https://github.com/OCA/server-tools/pull/1601
It fixes the module after the last refactore.

@pedrobaeza Could you please recheck, I believe your request for change is outdated.

@bealdav @mourad-ehm @sebastienbeau

2019-06-12 14:52 UTC, florian-dacosta approved these changes

2019-06-12 16:04 UTC, bealdav approved these changes
LGTM

2019-06-13 08:43 UTC, mourad-ehm approved these changes

2019-06-13 12:15 UTC, florian-dacosta commented
I reverted oca_dependencies since https://github.com/OCA/server-tools/pull/1601 has been merged.

This PR is now ready to be merged.

2019-06-13 15:51 UTC, sebastienbeau approved these changes
LGTM code review

2019-06-13 15:51 UTC, sebastienbeau commented
@pedrobaeza it's ok for you?

2019-06-14 10:00 UTC, sebastienbeau commented
The same PR in 12 have been merged so let's merge it https://github.com/OCA/sale-workflow/pull/873

2019-06-14 10:00 UTC, merged