[10.0][ADD] Add module sale_delivery_note
OCA/sale-workflow pull request #843
Opened 2019-05-10 09:58 UTC by acsonefho

Add a `delivery_note` field on the `sale.order`.

2019-05-10 11:14 UTC, rousseldenis commented on sale_delivery_note/models/__init__.py
> +from . import stock_move
@acsonefho This makes tests failing

2019-05-10 11:16 UTC, rousseldenis commented
@acsonefho Isn't this a duplicate of https://github.com/OCA/sale-workflow/pull/822 ?

2019-05-10 11:25 UTC, acsonefho commented
> @acsonefho Isn't this a duplicate of #822 ?

@rousseldenis It seems a duplicate but in our case, the delivery_note is a new field (into sale and into picking (from another module)).
And I think picking_note is more like internal note (between employees) and delivery_note is more like an instruction from the end-customer.

2019-08-29 07:51 UTC, lmignon approved these changes
LGTM :+1:

2019-08-29 07:51 UTC, lmignon commented
PR rebased to see if the issue with sale_triple_discount is solved...

2019-08-29 12:07 UTC, rafaelbn commented
Is this module like sale_stock_picking_note ?

https://github.com/OCA/sale-workflow/tree/11.0/sale_stock_picking_note

2019-08-29 12:09 UTC, rafaelbn commented
Hi @acsonefho 

>  And I think picking_note is more like internal note (between employees) and delivery_note is more like an instruction from the end-customer.

https://github.com/OCA/sale-workflow/tree/11.0/sale_stock_picking_note is already in use to set notes in sale order and this notes are printed in the picking for end-customers

It looks like the same. Up to you not blocking

2019-08-30 06:15 UTC, rafaelbn requested changes
I have done more deep review (my best intention).

You can see the video **sale_stock_picking_note VS sale_delivery_note**

https://drive.google.com/file/d/1uughmWYqZD4GVAz8L0bgqRYoO6N45RrA/view?usp=sharing

The OCA goal here is: we have a module from v9 in production which is like the same of this one, but in the case this both modules are different objetive we should care of making both "compatible" at UX experience:

- [ ] Both fields together with sense
- [ ] Very well explained the differences so the user understand them (improve README and USAGE)
- [ ] Each field is printed correctly in the PDF reports

We could ( I have to check with @sergio-teruel and @carlosdauden in this moment in holidays) agree that:

- sale_stock_picking_note is for notes for making the picking, not for the customer, so this notes are printed in "Picking Operations" and not in "Delivery Slip"

- sale_delivery_note: is for notes for the "Delivery man" (distributor)


In my test (check video) in runbot:

- [ ] We talk in this module about delivery so Is it related to : https://github.com/OCA/delivery-carrier ?

|                                                                                                                                                                    |         sale_stock_picking_note        |                   sale_delivery_note                   |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------:|:------------------------------------------------------:|
| Usage section                                                                                                                                                      |                   YES                  |                           NO                           |
| position field in sale order                                                                                                                                       |  TAB "other information" (see image_1) | botton of sale order  (see image_2) - [ ] Fix position |
| printed in sale order                                                                                                                                              |                   NO                   |                           NO                           |
| position field in stock picking                                                                                                                                    |             doesn't appears            |        TAB "additional info" Notes (see image_3)       |
| printed in PDF "Picking operations"                                                                                                                                |                   YES                  |                           NO                           |
| printed in PDF "Delivery Slip"                                                                                                                                     |                   NO                   |                           NO                           |
| Can define the note in res.parner the note? (a) Take the info from partner_shipping_id in sale.order (b) The note goes from partner to sale order to stock.picking |                   NO                   |                           NO                           |

Image 1:
![2019-08-30_7-32-54](https://user-images.githubusercontent.com/8736623/63997119-d9230b80-cafd-11e9-9fea-b0dc5a1ffc42.png)

Image 2:
![2019-08-30_7-34-23](https://user-images.githubusercontent.com/8736623/63997129-e2ac7380-cafd-11e9-84d7-534466410949.png)

Image 3:
![2019-08-30_8-03-56](https://user-images.githubusercontent.com/8736623/63997149-ed670880-cafd-11e9-84ce-869539c678ed.png)

My best

2019-08-30 06:23 UTC, rafaelbn commented
IMHO the best is one single module, both are the same. The only difference is is the note is printed o not in the "Delivery slip", that's all.

2019-08-30 07:09 UTC, rousseldenis commented
@acsonefho @Cedric-Pigeon

2019-09-17 12:41 UTC, closed without merging