[12.0][IMP] sale exception
OCA/sale-workflow pull request #878
Opened 2019-06-18 12:05 UTC by ivantodorovich

Improve information messages when the order has exceptions:

![image](https://user-images.githubusercontent.com/1914185/59680571-f2403f80-91d1-11e9-8d1c-3af3feb2fef5.png)

---

This PR also contains this change: https://github.com/OCA/sale-workflow/pull/722 ([IMP] sale_exception: show menu only to Exception Rule Managers)

Depends on https://github.com/OCA/server-tools/pull/1609

2019-06-18 13:59 UTC, HaraldPanten requested changes
Can not install module on runbot:

`Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 1096, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `exception_ids_formatted` does not exist

Error context:
View `sale_exception.view_order_form`
[view_id: 1078, xml_id: n/a, model: sale.order, parent_id: 929]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/.repo_requirements/odoo/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/.repo_requirements/odoo/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/.repo_requirements/odoo/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/.repo_requirements/odoo/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/.repo_requirements/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField `exception_ids_formatted` does not exist\n\nError context:\nView `sale_exception.view_order_form`\n[view_id: 1078, xml_id: n/a, model: sale.order, parent_id: 929]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/.repo_requirements/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/.repo_requirements/odoo/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/.repo_requirements/odoo/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/.repo_re [...]

2019-06-18 16:02 UTC, ivantodorovich commented
@HaraldPanten it's because it depends on OCA/server-tools#1609

2019-07-09 13:16 UTC, hparfr reviewed
* why not using a custom many2many widget to achieve the same result without adding fields ?
* i'm not fan of the "ignore" directly (without wizard - without refresh of the rules). I fear users will dismiss this warning without even bother to refresh what rules still applies.

2019-07-09 13:44 UTC, ivantodorovich commented
@hparfr 

> why not using a custom many2many widget to achieve the same result without adding fields ?
It didn't occured to me, but still .. developping a custom m2m widget seems too much for this.

> i'm not fan of the "ignore" directly (without wizard - without refresh of the rules). I fear users will dismiss this warning without even bother to refresh what rules still applies.
Well.. the 'Ignore' button is shown only to Exception Managers. Normal users won't even see that button, only the warning. And still, we are showing all the exceptions in the alert-box, not just the main one. So if an Exception Manager clicks Ignore, he knows exactly what he's ignoring..

2019-07-09 13:49 UTC, hparfr commented
>It didn't occured to me, but still .. developping a custom m2m widget seems too much for this.

Yes but more reusable for all _exceptions modules. I agree it's a lot of effort.

2019-07-09 13:50 UTC, hparfr approved these changes
Non blocking remarks answered.
Didn't test it since it depends of another PR

2019-07-15 11:08 UTC, HaraldPanten approved these changes

2019-09-22 21:34 UTC, rafaelbn commented
This is WIP until https://github.com/OCA/server-tools/pull/1609 is merged

2019-10-14 08:16 UTC, ivantodorovich commented
https://github.com/OCA/server-tools/pull/1609 has been merged.
This is green now

2019-10-14 09:37 UTC, pedrobaeza requested changes

2019-10-14 09:37 UTC, pedrobaeza commented on sale_exception/__manifest__.py
> +              "Druidoo, "
This doesn't qualify for being co-author I'm afraid.

2019-10-14 09:43 UTC, ivantodorovich commented on sale_exception/__manifest__.py
> +              "Druidoo, "
Got it! :+1:

2019-10-14 10:06 UTC, pedrobaeza approved these changes

2019-10-14 10:06 UTC, merged