12.0 overdrawn quantities
OCA/sale-workflow pull request #933
Opened 2019-09-13 22:47 UTC by lmgr0312

2019-09-17 04:32 UTC, nikul-serpentcs reviewed
Nitpicking

2019-09-17 04:32 UTC, nikul-serpentcs commented on sale_request/__manifest__.py
> +    'license': 'LGPL-3',
@lmgr0312 Check license As per README

2019-09-22 16:11 UTC, rafaelbn requested changes
Hi @lmgr0312 , thank for this contribution.

- Please follow the migration guidelines in https://github.com/OCA/maintainer-tools/wiki#migration
- you are modifying in this PR 2 different modules `sale_product_set` and `sale_request`
- A better title in the PR will attract more reviewers
- A more detailed description in the PR about what are you doing will attract more reviewers

Please fix it

2022-02-10 10:38 UTC, rousseldenis commented
@lmgr0312 What's the status of this ?

2022-07-17 12:26 UTC, closed without merging