Migrated sale_order_general_discount to v13.
OCA/sale-workflow pull request #981
Opened 2019-11-02 13:04 UTC by sudhir-erpharbor

2020-01-24 10:53 UTC, sergio-teruel commented
@sudhir-erpharbor Are you going to continue this PR?

2020-01-24 11:02 UTC, sergio-teruel requested changes

2020-01-24 11:02 UTC, sergio-teruel commented on sale_order_general_discount/__manifest__.py
> +    "development_status": "Production/Stable",
Add maintainers key

2020-01-24 11:02 UTC, sergio-teruel commented on sale_order_general_discount/models/sale.py
> +    )
Make field compute, store, and readonly False... to change to new onchange behavior

2020-01-24 11:02 UTC, sergio-teruel commented on sale_order_general_discount/models/sale.py
> +    @api.onchange("partner_id")
```suggestion
    @api.depends("partner_id")
    def _compute_general_discount(self):
        for so in self:
            so.general_discount = so.partner_id.sale_discount
```

2020-01-24 11:02 UTC, sergio-teruel commented on sale_order_general_discount/models/sale.py
> +    @api.onchange("general_discount")
make the same....

2020-01-24 11:02 UTC, sergio-teruel commented on sale_order_general_discount/tests/test_sale_order_general_discount.py
> +        self.order.onchange_partner_id()
With changes commented is not needed

2020-01-24 11:11 UTC, sudhir-erpharbor commented
> @sudhir-erpharbor Are you going to continue this PR?

Yes, will make the changes as per your request.

2020-01-24 12:12 UTC, sergio-teruel commented
Ok... Thanks... :smile:

2020-01-24 15:24 UTC, sergio-teruel commented on sale_order_general_discount/models/sale.py
> +        digits=dp.get_precision("Discount"), string="Discount (%)"
get_precision method is deprecated... 
See --> https://github.com/odoo/odoo/blob/1a315e87b05fcbdefcb3db6d8d4837f6cc3e835c/odoo/addons/base/models/decimal_precision.py#L13

2020-02-03 14:17 UTC, sudhir-erpharbor commented on sale_order_general_discount/__manifest__.py
> +    "development_status": "Production/Stable",
@sergio-teruel What should I add in "maintainers"? Just my github user name or anything else?

2020-04-24 06:40 UTC, rousseldenis commented
@sudhir-erpharbor Do you plan to finish this or do you want to close this in favor of #1124 ?

2020-04-29 05:37 UTC, closed without merging